INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('laptop', 'dizüstü bilgisayar', 'hardware', 'beginner', 'en', 'I work on my laptop every day.', 'Her gün dizüstü bilgisayarımda çalışıyorum.'),
  ('monitor', 'monitör', 'hardware', 'beginner', 'en', 'A larger monitor helps my eyes.', 'Daha büyük bir monitör gözlerime iyi geliyor.'),
  ('printer', 'yazıcı', 'hardware', 'beginner', 'en', 'The printer ran out of ink.', 'Yazıcının mürekkebi bitti.'),
  ('router', 'yönlendirici', 'hardware', 'beginner', 'en', 'Restart the router if Wi-Fi is slow.', 'Wi-Fi yavaşsa yönlendiriciyi yeniden başlat.'),
  ('webcam', 'web kamerası', 'hardware', 'beginner', 'en', 'Cover the webcam when not in use.', 'Kullanmadığında web kamerasını kapat.'),
  ('microphone', 'mikrofon', 'hardware', 'beginner', 'en', 'Test the microphone before the call.', 'Görüşmeden önce mikrofonu test et.'),
  ('USB port', 'USB girişi', 'hardware', 'beginner', 'en', 'Plug the drive into a USB port.', 'Sürücüyü bir USB girişine tak.'),
  ('power cord', 'güç kablosu', 'hardware', 'beginner', 'en', 'The power cord is too short.', 'Güç kablosu çok kısa.'),
  ('adapter', 'adaptör', 'hardware', 'beginner', 'en', 'You need a travel adapter abroad.', 'Yurt dışında seyahat adaptörüne ihtiyacın var.'),
  ('tablet', 'tablet', 'hardware', 'beginner', 'en', 'She reads books on her tablet.', 'Kitapları tabletinden okuyor.'),
  ('smartphone', 'akıllı telefon', 'hardware', 'beginner', 'en', 'My smartphone takes great photos.', 'Akıllı telefonum harika fotoğraflar çekiyor.'),
  ('hard drive', 'sabit disk', 'hardware', 'beginner', 'en', 'Back up files to an external hard drive.', 'Dosyaları harici sabit diske yedekle.'),
  ('memory card', 'hafıza kartı', 'hardware', 'beginner', 'en', 'Insert the memory card carefully.', 'Hafıza kartını dikkatlice tak.'),
  ('touchscreen', 'dokunmatik ekran', 'hardware', 'beginner', 'en', 'The touchscreen stopped responding.', 'Dokunmatik ekran yanıt vermeyi bıraktı.'),
  ('bluetooth', 'bluetooth', 'hardware', 'beginner', 'en', 'Pair the speaker via Bluetooth.', 'Hoparlörü Bluetooth ile eşleştir.'),
  ('Wi-Fi', 'kablosuz internet', 'hardware', 'beginner', 'en', 'The Wi-Fi password is on the router.', 'Wi-Fi şifresi yönlendiricide.'),
  ('case', 'kılıf', 'hardware', 'beginner', 'en', 'A phone case prevents scratches.', 'Telefon kılıfı çizilmeleri önler.'),
  ('stand', 'stand', 'hardware', 'beginner', 'en', 'Use a laptop stand for better posture.', 'Daha iyi duruş için dizüstü standı kullan.'),
  ('fan', 'fan', 'hardware', 'beginner', 'en', 'The laptop fan is loud.', 'Dizüstü bilgisayarın fanı gürültülü.'),
  ('slot', 'yuva', 'hardware', 'beginner', 'en', 'The SIM card slot is on the side.', 'SIM kart yuvası yanda.'),
  ('plug', 'fiş', 'hardware', 'beginner', 'en', 'Unplug the device before cleaning.', 'Temizlemeden önce cihazın fişini çek.'),
  ('power supply', 'güç kaynağı', 'hardware', 'intermediate', 'en', 'Check the power supply wattage.', 'Güç kaynağının watt değerini kontrol et.'),
  ('CPU cooler', 'işlemci soğutucusu', 'hardware', 'intermediate', 'en', 'Install the CPU cooler correctly.', 'İşlemci soğutucusunu doğru tak.'),
  ('Ethernet cable', 'Ethernet kablosu', 'hardware', 'intermediate', 'en', 'Use an Ethernet cable for stable speed.', 'Kararlı hız için Ethernet kablosu kullan.'),
  ('HDMI port', 'HDMI girişi', 'hardware', 'intermediate', 'en', 'Connect the monitor to the HDMI port.', 'Monitörü HDMI girişine bağla.'),
  ('display port', 'DisplayPort', 'hardware', 'intermediate', 'en', 'This monitor supports DisplayPort.', 'Bu monitör DisplayPort destekliyor.'),
  ('BIOS', 'BIOS', 'hardware', 'intermediate', 'en', 'Update the BIOS for better compatibility.', 'Daha iyi uyumluluk için BIOS güncelle.'),
  ('driver', 'sürücü', 'hardware', 'intermediate', 'en', 'Install the latest graphics driver.', 'En son ekran kartı sürücüsünü yükle.'),
  ('overheating', 'aşırı ısınma', 'hardware', 'intermediate', 'en', 'Dust causes overheating inside the PC.', 'Toz bilgisayarın içinde aşırı ısınmaya neden olur.'),
  ('expansion slot', 'genişletme yuvası', 'hardware', 'intermediate', 'en', 'The expansion slot fits a new card.', 'Genişletme yuvasına yeni bir kart takılır.'),
  ('heat pipe', 'ısı borusu', 'hardware', 'intermediate', 'en', 'Heat pipes move heat away quickly.', 'Isı boruları ısıyı hızla uzaklaştırır.'),
  ('NVMe', 'NVMe', 'hardware', 'intermediate', 'en', 'NVMe drives are faster than SATA.', 'NVMe sürücüler SATA''dan daha hızlıdır.'),
  ('SATA cable', 'SATA kablosu', 'hardware', 'intermediate', 'en', 'Connect the drive with a SATA cable.', 'Sürücüyü SATA kablosu ile bağla.'),
  ('dual monitor', 'çift monitör', 'hardware', 'intermediate', 'en', 'A dual monitor setup boosts productivity.', 'Çift monitör kurulumu verimliliği artırır.'),
  ('wireless adapter', 'kablosuz adaptör', 'hardware', 'intermediate', 'en', 'A USB wireless adapter adds Wi-Fi.', 'USB kablosuz adaptör Wi-Fi ekler.'),
  ('optical drive', 'optik sürücü', 'hardware', 'intermediate', 'en', 'Few laptops include an optical drive now.', 'Artık az dizüstü bilgisayarda optik sürücü var.'),
  ('touchpad', 'dokunmatik yüzey', 'hardware', 'intermediate', 'en', 'The touchpad supports multi-touch gestures.', 'Dokunmatik yüzey çoklu dokunma hareketlerini destekliyor.'),
  ('web server', 'web sunucusu', 'hardware', 'intermediate', 'en', 'The web server handles incoming requests.', 'Web sunucusu gelen istekleri işler.'),
  ('cache memory', 'önbellek belleği', 'hardware', 'intermediate', 'en', 'Cache memory reduces load times.', 'Önbellek belleği yükleme sürelerini azaltır.'),
  ('form factor', 'form faktörü', 'hardware', 'intermediate', 'en', 'Choose the right form factor for your case.', 'Kasan için doğru form faktörünü seç.'),
  ('pixel density', 'piksel yoğunluğu', 'hardware', 'intermediate', 'en', 'High pixel density makes text crisp.', 'Yüksek piksel yoğunluğu metni netleştirir.'),
  ('surge protector', 'parafudr', 'hardware', 'intermediate', 'en', 'Plug expensive gear into a surge protector.', 'Pahalı ekipmanı parafudra tak.'),
  ('UPS', 'kesintisiz güç kaynağı', 'hardware', 'intermediate', 'en', 'A UPS saves work during power cuts.', 'Kesintisiz güç kaynağı elektrik kesintisinde işi kurtarır.'),
  ('throughput', 'verim', 'hardware', 'advanced', 'en', 'Network throughput dropped at peak hours.', 'Yoğun saatlerde ağ verimi düştü.'),
  ('I/O shield', 'G/Ç kalkanı', 'hardware', 'advanced', 'en', 'Install the I/O shield before the motherboard.', 'Anakarttan önce G/Ç kalkanını tak.'),
  ('chipset', 'yonga seti', 'hardware', 'advanced', 'en', 'The chipset controls data flow on the board.', 'Yonga seti karttaki veri akışını kontrol eder.'),
  ('ECC memory', 'ECC bellek', 'hardware', 'advanced', 'en', 'Servers often use ECC memory for reliability.', 'Sunucular güvenilirlik için genelde ECC bellek kullanır.'),
  ('RAID array', 'RAID dizisi', 'hardware', 'advanced', 'en', 'A RAID array mirrors data across drives.', 'RAID dizisi veriyi sürücüler arasında yansıtır.'),
  ('virtualization', 'sanallaştırma', 'hardware', 'advanced', 'en', 'Virtualization lets one PC run many systems.', 'Sanallaştırma bir bilgisayarın birçok sistem çalıştırmasını sağlar.'),
  ('hypervisor', 'hipervizör', 'hardware', 'advanced', 'en', 'The hypervisor manages virtual machines.', 'Hipervizör sanal makineleri yönetir.'),
  ('PCIe lane', 'PCIe kanalı', 'hardware', 'advanced', 'en', 'The GPU uses sixteen PCIe lanes.', 'Ekran kartı on altı PCIe kanalı kullanır.'),
  ('TDP', 'TDP', 'hardware', 'advanced', 'en', 'Check TDP before choosing a cooler.', 'Soğutucu seçmeden önce TDP''yi kontrol et.'),
  ('VRM', 'VRM', 'hardware', 'advanced', 'en', 'Quality VRMs deliver stable power to the CPU.', 'Kaliteli VRM''ler işlemciye kararlı güç verir.'),
  ('undervolting', 'voltaj düşürme', 'hardware', 'advanced', 'en', 'Undervolting can reduce heat safely.', 'Voltaj düşürme ısıyı güvenle azaltabilir.'),
  ('capacitor', 'kondansatör', 'hardware', 'advanced', 'en', 'Bulging capacitors signal board failure.', 'Şişmiş kondansatörler kart arızasına işaret eder.'),
  ('trace routing', 'iz yönlendirme', 'hardware', 'advanced', 'en', 'Trace routing affects signal quality.', 'İz yönlendirme sinyal kalitesini etkiler.'),
  ('jitter', 'titreşim', 'hardware', 'advanced', 'en', 'Network jitter disrupts video calls.', 'Ağ titreşimi görüntülü aramaları bozar.'),
  ('packet loss', 'paket kaybı', 'hardware', 'advanced', 'en', 'Packet loss causes lag in games.', 'Paket kaybı oyunlarda gecikmeye neden olur.'),
  ('load balancing', 'yük dengeleme', 'hardware', 'advanced', 'en', 'Load balancing spreads traffic across servers.', 'Yük dengeleme trafiği sunucular arasında dağıtır.'),
  ('failover', 'yedek devreye alma', 'hardware', 'advanced', 'en', 'Failover keeps the site online during outages.', 'Yedek devreye alma kesintilerde siteyi çevrimiçi tutar.'),
  ('edge computing', 'uç bilişim', 'hardware', 'advanced', 'en', 'Edge computing processes data closer to users.', 'Uç bilişim veriyi kullanıcılara daha yakın işler.'),
  ('quantum bit', 'kübit', 'hardware', 'advanced', 'en', 'A quantum bit can hold superposition states.', 'Bir kübit süperpozisyon durumlarını tutabilir.'),
  ('silicon wafer', 'silisyum plakası', 'hardware', 'advanced', 'en', 'Chips are cut from a silicon wafer.', 'Çipler silisyum plakasından kesilir.'),
  ('nanometer process', 'nanometre süreci', 'hardware', 'advanced', 'en', 'A smaller nanometer process saves power.', 'Daha küçük nanometre süreci güç tasarrufu sağlar.'),
  ('side-channel attack', 'yan kanal saldırısı', 'hardware', 'advanced', 'en', 'Firmware updates patch side-channel attacks.', 'Donanım yazılımı güncellemeleri yan kanal saldırılarını kapatır.'),
  ('chicken', 'tavuk', 'animals', 'beginner', 'en', 'The chicken laid an egg today.', 'Tavuk bugün bir yumurta yumurtladı.'),
  ('pig', 'domuz', 'animals', 'beginner', 'en', 'Pigs are very intelligent animals.', 'Domuzlar çok zeki hayvanlardır.'),
  ('goat', 'keçi', 'animals', 'beginner', 'en', 'The goat climbed the rocky path.', 'Keçi kayalık patikaya tırmandı.'),
  ('mouse', 'fare', 'animals', 'beginner', 'en', 'A tiny mouse hid under the bush.', 'Minicik bir fare çalı altına saklandı.'),
  ('elephant', 'fil', 'animals', 'beginner', 'en', 'An elephant never forgets.', 'Fil asla unutmaz.'),
  ('lion', 'aslan', 'animals', 'beginner', 'en', 'The lion roared loudly at dawn.', 'Aslan şafakta yüksek sesle kükredi.'),
  ('tiger', 'kaplan', 'animals', 'beginner', 'en', 'Tigers have striking orange stripes.', 'Kaplanların çarpıcı turuncu çizgileri vardır.'),
  ('bear', 'ayı', 'animals', 'beginner', 'en', 'Bears hibernate in cold winters.', 'Ayılar soğuk kışlarda kış uykusuna yatar.'),
  ('wolf', 'kurt', 'animals', 'beginner', 'en', 'Wolves hunt in packs.', 'Kurtlar sürü halinde avlanır.'),
  ('fox', 'tilki', 'animals', 'beginner', 'en', 'The fox slipped through the fence.', 'Tilki çitin arasından süzüldü.'),
  ('deer', 'geyik', 'animals', 'beginner', 'en', 'We spotted a deer in the forest.', 'Ormanda bir geyik gördük.'),
  ('monkey', 'maymun', 'animals', 'beginner', 'en', 'Monkeys swing from tree to tree.', 'Maymunlar ağaçtan ağaca sallanır.'),
  ('snake', 'yılan', 'animals', 'beginner', 'en', 'The snake slid across the warm rock.', 'Yılan sıcak kayanın üzerinden kaydı.'),
  ('turtle', 'kaplumbağa', 'animals', 'beginner', 'en', 'The turtle moved slowly toward the water.', 'Kaplumbağa suya doğru yavaşça ilerledi.'),
  ('frog', 'kurbağa', 'animals', 'beginner', 'en', 'Frogs croak after rain.', 'Kurbağalar yağmurdan sonra vıraklar.'),
  ('bee', 'arı', 'animals', 'beginner', 'en', 'Bees pollinate many flowers.', 'Arılar birçok çiçeği tozlaşır.'),
  ('butterfly', 'kelebek', 'animals', 'beginner', 'en', 'A butterfly landed on her shoulder.', 'Bir kelebek omzuna kondu.'),
  ('spider', 'örümcek', 'animals', 'beginner', 'en', 'The spider spun a delicate web.', 'Örümcek narin bir ağ ördü.'),
  ('whale', 'balina', 'animals', 'beginner', 'en', 'Whales migrate across oceans.', 'Balinalar okyanuslar boyunca göç eder.'),
  ('dolphin', 'yunus', 'animals', 'beginner', 'en', 'Dolphins are friendly and playful.', 'Yunuslar dost canlısı ve oyuncudur.'),
  ('penguin', 'penguen', 'animals', 'beginner', 'en', 'Penguins live in cold climates.', 'Penguenler soğuk iklimlerde yaşar.'),
  ('herbivore', 'otçul', 'animals', 'intermediate', 'en', 'Deer are herbivores that eat plants.', 'Geyikler bitki yiyen otçullardır.'),
  ('carnivore', 'etçil', 'animals', 'intermediate', 'en', 'Lions are carnivores at the top of the food chain.', 'Aslanlar besin zincirinin tepesindeki etçillerdir.'),
  ('omnivore', 'hepçil', 'animals', 'intermediate', 'en', 'Bears are omnivores with varied diets.', 'Ayılar çeşitli beslenen hepçillerdir.'),
  ('pack', 'sürü', 'animals', 'intermediate', 'en', 'A wolf pack cooperates during hunts.', 'Kurt sürüsü av sırasında iş birliği yapar.'),
  ('flock', 'sürü', 'animals', 'intermediate', 'en', 'A flock of geese flew south.', 'Bir kaz sürüsü güneye uçtu.'),
  ('den', 'in', 'animals', 'intermediate', 'en', 'Foxes raise pups in an underground den.', 'Tilkiler yavrularını yer altı ininde büyütür.'),
  ('nest', 'yuva', 'animals', 'intermediate', 'en', 'The bird built a nest in the tree.', 'Kuş ağaçta bir yuva yaptı.'),
  ('antlers', 'boynuz', 'animals', 'intermediate', 'en', 'Male deer grow antlers each year.', 'Erkek geyikler her yıl boynuz çıkarır.'),
  ('paw', 'pati', 'animals', 'intermediate', 'en', 'The dog left muddy paw prints.', 'Köpek çamurlu pati izleri bıraktı.'),
  ('beak', 'gaga', 'animals', 'intermediate', 'en', 'Parrots use their beak to crack nuts.', 'Papağanlar fındık kırmak için gagalarını kullanır.'),
  ('gills', 'solungaç', 'animals', 'intermediate', 'en', 'Fish breathe through their gills.', 'Balıklar solungaçlarıyla nefes alır.'),
  ('scales', 'pul', 'animals', 'intermediate', 'en', 'Snakes have dry scales on their skin.', 'Yılanların derisinde kuru pullar vardır.'),
  ('feathers', 'tüy', 'animals', 'intermediate', 'en', 'Birds preen their feathers daily.', 'Kuşlar tüylerini her gün düzler.'),
  ('wildlife', 'yaban hayatı', 'animals', 'intermediate', 'en', 'The park protects local wildlife.', 'Park yerel yaban hayatını korur.'),
  ('conservation', 'koruma', 'animals', 'intermediate', 'en', 'Conservation efforts saved the species.', 'Koruma çabaları türü kurtardı.'),
  ('sanctuary', 'barınak', 'animals', 'intermediate', 'en', 'The sanctuary rescues injured animals.', 'Barınak yaralı hayvanları kurtarıyor.'),
  ('poacher', 'kaçak avcı', 'animals', 'intermediate', 'en', 'Rangers caught a poacher near the reserve.', 'Korucular rezerv yakınında bir kaçak avcı yakaladı.'),
  ('ecosystem', 'ekosistem', 'animals', 'intermediate', 'en', 'Bees are vital to the ecosystem.', 'Arılar ekosistem için hayati önem taşır.'),
  ('adaptation', 'uyum', 'animals', 'intermediate', 'en', 'Camouflage is a useful adaptation.', 'Kamuflaj faydalı bir uyumdur.'),
  ('offspring', 'yavru', 'animals', 'intermediate', 'en', 'The lioness protects her offspring.', 'Dişi aslan yavrularını korur.'),
  ('lifespan', 'yaşam süresi', 'animals', 'intermediate', 'en', 'A tortoise can have a long lifespan.', 'Bir kaplumbağanın uzun bir yaşam süresi olabilir.'),
  ('domestic animal', 'evcil hayvan', 'animals', 'intermediate', 'en', 'Cats are popular domestic animals.', 'Kediler popüler evcil hayvanlardır.'),
  ('biodiversity', 'biyoçeşitlilik', 'animals', 'advanced', 'en', 'Rainforests hold rich biodiversity.', 'Yağmur ormanları zengin biyoçeşitlilik barındırır.'),
  ('mutualism', 'karşılıklılık', 'animals', 'advanced', 'en', 'Bees and flowers benefit through mutualism.', 'Arılar ve çiçekler karşılıklılık yoluyla fayda sağlar.'),
  ('parasitism', 'parazitlik', 'animals', 'advanced', 'en', 'Ticks survive through parasitism on hosts.', 'Keneler konakçılarda parazitlik yoluyla hayatta kalır.'),
  ('metamorphosis', 'başkalaşım', 'animals', 'advanced', 'en', 'Butterflies undergo complete metamorphosis.', 'Kelebekler tam başkalaşım geçirir.'),
  ('echolocation', 'yankı konumlandırma', 'animals', 'advanced', 'en', 'Bats hunt using echolocation.', 'Yarasalar yankı konumlandırma kullanarak avlanır.'),
  ('bioluminescence', 'biyolüminesans', 'animals', 'advanced', 'en', 'Deep-sea fish use bioluminescence to lure prey.', 'Derin deniz balıkları avı cezbetmek için biyolüminesans kullanır.'),
  ('keystone species', 'taş tür', 'animals', 'advanced', 'en', 'Sea otters are a keystone species in kelp forests.', 'Deniz samurları yosun ormanlarında taş türdür.'),
  ('invasive species', 'istilacı tür', 'animals', 'advanced', 'en', 'Invasive species upset local ecosystems.', 'İstilacı türler yerel ekosistemleri bozar.'),
  ('genetic diversity', 'genetik çeşitlilik', 'animals', 'advanced', 'en', 'Small populations lose genetic diversity.', 'Küçük popülasyonlar genetik çeşitliliği kaybeder.'),
  ('anthropogenic', 'insan kaynaklı', 'animals', 'advanced', 'en', 'Anthropogenic noise stresses whales.', 'İnsan kaynaklı gürültü balinaları strese sokar.'),
  ('poaching', 'kaçak avcılık', 'animals', 'advanced', 'en', 'Strict laws aim to stop poaching.', 'Sıkı yasalar kaçak avcılığı durdurmayı hedefler.'),
  ('reintroduction', 'yeniden doğaya salma', 'animals', 'advanced', 'en', 'Wolf reintroduction changed the ecosystem.', 'Kurt yeniden doğaya salması ekosistemi değiştirdi.'),
  ('microbiome', 'mikrobiyom', 'animals', 'advanced', 'en', 'Gut microbiome affects animal health.', 'Bağırsak mikrobiyomu hayvan sağlığını etkiler.'),
  ('endemic', 'endemik', 'animals', 'advanced', 'en', 'The lemur is endemic to Madagascar.', 'Lemur Madagaskar''a endemiktir.'),
  ('phenotype', 'fenotip', 'animals', 'advanced', 'en', 'Environment shapes an animal''s phenotype.', 'Çevre bir hayvanın fenotipini şekillendirir.'),
  ('social hierarchy', 'sosyal hiyerarşi', 'animals', 'advanced', 'en', 'Wolf packs have a clear social hierarchy.', 'Kurt sürülerinin belirgin bir sosyal hiyerarşisi vardır.'),
  ('altruism', 'özvericilik', 'animals', 'advanced', 'en', 'Dolphins sometimes show altruism toward humans.', 'Yunuslar bazen insanlara karşı özvericilik gösterir.'),
  ('speciation', 'türleşme', 'animals', 'advanced', 'en', 'Isolation can lead to speciation over time.', 'İzolasyon zamanla türleşmeye yol açabilir.'),
  ('trophic level', 'trofik seviye', 'animals', 'advanced', 'en', 'Each trophic level transfers less energy.', 'Her trofik seviye daha az enerji aktarır.'),
  ('zooplankton', 'zooplankton', 'animals', 'advanced', 'en', 'Whales feed on tiny zooplankton.', 'Balinalar minik zooplanktonla beslenir.'),
  ('anthropomorphism', 'insancıllaştırma', 'animals', 'advanced', 'en', 'Cartoons often use anthropomorphism.', 'Çizgi filmler sık sık insancıllaştırma kullanır.'),
  ('crypsis', 'gizlenme', 'animals', 'advanced', 'en', 'Leaf insects rely on crypsis to avoid predators.', 'Yaprak böcekleri yırtıcılardan kaçmak için gizlenmeye güvenir.'),
  ('dishes', 'bulaşık', 'daily life', 'beginner', 'en', 'Please wash the dishes after dinner.', 'Lütfen akşam yemeğinden sonra bulaşıkları yıka.'),
  ('keys', 'anahtar', 'daily life', 'beginner', 'en', 'I cannot find my keys.', 'Anahtarlarımı bulamıyorum.'),
  ('wallet', 'cüzdan', 'daily life', 'beginner', 'en', 'He left his wallet on the table.', 'Cüzdanını masada unuttu.'),
  ('mailbox', 'posta kutusu', 'daily life', 'beginner', 'en', 'Check the mailbox for letters.', 'Mektuplar için posta kutusunu kontrol et.'),
  ('doorbell', 'kapı zili', 'daily life', 'beginner', 'en', 'Someone rang the doorbell.', 'Biri kapı ziline bastı.'),
  ('curtain', 'perde', 'daily life', 'beginner', 'en', 'Close the curtains at night.', 'Gece perdeleri kapat.'),
  ('pillow', 'yastık', 'daily life', 'beginner', 'en', 'This pillow is very soft.', 'Bu yastık çok yumuşak.'),
  ('blanket', 'battaniye', 'daily life', 'beginner', 'en', 'Grab a blanket, it is cold.', 'Bir battaniye al, hava soğuk.'),
  ('toothbrush', 'diş fırçası', 'daily life', 'beginner', 'en', 'Replace your toothbrush every three months.', 'Diş fırçanı üç ayda bir değiştir.'),
  ('soap', 'sabun', 'daily life', 'beginner', 'en', 'We ran out of soap.', 'Sabunumuz bitti.'),
  ('towel', 'havlu', 'daily life', 'beginner', 'en', 'Hang your towel to dry.', 'Havlunu kuruması için as.'),
  ('mirror', 'ayna', 'daily life', 'beginner', 'en', 'She looked in the mirror before leaving.', 'Çıkmadan önce aynaya baktı.'),
  ('closet', 'dolap', 'daily life', 'beginner', 'en', 'My clothes are in the closet.', 'Kıyafetlerim dolapta.'),
  ('shelf', 'raf', 'daily life', 'beginner', 'en', 'Put the books on the shelf.', 'Kitapları rafa koy.'),
  ('light switch', 'ışık düğmesi', 'daily life', 'beginner', 'en', 'Turn off the light switch.', 'Işık düğmesini kapat.'),
  ('vacuum', 'elektrikli süpürge', 'daily life', 'beginner', 'en', 'I vacuum the carpet weekly.', 'Halıyı haftalık elektrikli süpürgeyle temizlerim.'),
  ('broom', 'süpürge', 'daily life', 'beginner', 'en', 'Sweep the floor with a broom.', 'Yeri süpürgeyle süpür.'),
  ('recycling', 'geri dönüşüm', 'daily life', 'beginner', 'en', 'Sort recycling every Tuesday.', 'Her salı geri dönüşümü ayır.'),
  ('package', 'paket', 'daily life', 'beginner', 'en', 'A package arrived at the door.', 'Kapıya bir paket geldi.'),
  ('delivery', 'teslimat', 'daily life', 'beginner', 'en', 'The delivery comes between noon and two.', 'Teslimat öğle ile iki arasında geliyor.'),
  ('appointment', 'randevu', 'daily life', 'beginner', 'en', 'I have a dentist appointment at three.', 'Saat üçte diş hekimi randevum var.'),
  ('maintenance', 'bakım', 'daily life', 'intermediate', 'en', 'Regular maintenance prevents costly repairs.', 'Düzenli bakım pahalı onarımları önler.'),
  ('landlord', 'ev sahibi', 'daily life', 'intermediate', 'en', 'We emailed the landlord about the leak.', 'Sızıntı hakkında ev sahibine e-posta attık.'),
  ('tenant', 'kiracı', 'daily life', 'intermediate', 'en', 'The tenant signed a one-year lease.', 'Kiracı bir yıllık kira sözleşmesi imzaladı.'),
  ('insurance', 'sigorta', 'daily life', 'intermediate', 'en', 'Home insurance covers storm damage.', 'Ev sigortası fırtına hasarını karşılar.'),
  ('mortgage', 'ipotek', 'daily life', 'intermediate', 'en', 'They pay their mortgage on the first.', 'İpoteklerini ayın birinde ödüyorlar.'),
  ('renovation', 'yenileme', 'daily life', 'intermediate', 'en', 'Kitchen renovation starts next week.', 'Mutfak yenilemesi gelecek hafta başlıyor.'),
  ('housewarming', 'ev açılışı', 'daily life', 'intermediate', 'en', 'We got gifts at our housewarming.', 'Ev açılışımızda hediyeler aldık.'),
  ('chore chart', 'ev işi tablosu', 'daily life', 'intermediate', 'en', 'Kids follow the chore chart each week.', 'Çocuklar her hafta ev işi tablosunu takip eder.'),
  ('meal prep', 'yemek hazırlığı', 'daily life', 'intermediate', 'en', 'Meal prep saves time on weekdays.', 'Yemek hazırlığı hafta içi zaman kazandırır.'),
  ('time management', 'zaman yönetimi', 'daily life', 'intermediate', 'en', 'Good time management reduces stress.', 'İyi zaman yönetimi stresi azaltır.'),
  ('work-life balance', 'iş-yaşam dengesi', 'daily life', 'intermediate', 'en', 'She prioritizes work-life balance.', 'İş-yaşam dengesine öncelik veriyor.'),
  ('childcare', 'çocuk bakımı', 'daily life', 'intermediate', 'en', 'Childcare costs are rising fast.', 'Çocuk bakımı maliyetleri hızla artıyor.'),
  ('pet care', 'evcil hayvan bakımı', 'daily life', 'intermediate', 'en', 'Pet care includes vet visits and food.', 'Evcil hayvan bakımı veteriner ziyaretleri ve mama içerir.'),
  ('home office', 'ev ofisi', 'daily life', 'intermediate', 'en', 'He set up a quiet home office.', 'Sessiz bir ev ofisi kurdu.'),
  ('declutter', 'sadeleştirmek', 'daily life', 'intermediate', 'en', 'We declutter the garage every spring.', 'Her bahar garajı sadeleştiririz.'),
  ('bulk shopping', 'toplu alışveriş', 'daily life', 'intermediate', 'en', 'Bulk shopping lowers the cost per item.', 'Toplu alışveriş birim maliyeti düşürür.'),
  ('loyalty program', 'sadakat programı', 'daily life', 'intermediate', 'en', 'The loyalty program gives small discounts.', 'Sadakat programı küçük indirimler verir.'),
  ('self-checkout', 'self servis kasa', 'daily life', 'intermediate', 'en', 'Self-checkout lines move quickly.', 'Self servis kasa sıraları hızlı ilerler.'),
  ('noise complaint', 'gürültü şikayeti', 'daily life', 'intermediate', 'en', 'The neighbor filed a noise complaint.', 'Komşu gürültü şikayetinde bulundu.'),
  ('HOA fee', 'site aidatı', 'daily life', 'intermediate', 'en', 'The HOA fee covers shared landscaping.', 'Site aidatı ortak peyzajı karşılar.'),
  ('smart home', 'akıllı ev', 'daily life', 'intermediate', 'en', 'A smart home controls lights by voice.', 'Akıllı ev ışıkları sesle kontrol eder.'),
  ('energy efficiency', 'enerji verimliliği', 'daily life', 'intermediate', 'en', 'Energy efficiency cuts monthly bills.', 'Enerji verimliliği aylık faturaları düşürür.'),
  ('minimalism', 'minimalizm', 'daily life', 'advanced', 'en', 'Minimalism focuses on what truly matters.', 'Minimalizm gerçekten önemli olana odaklanır.'),
  ('intentional living', 'bilinçli yaşam', 'daily life', 'advanced', 'en', 'Intentional living aligns actions with values.', 'Bilinçli yaşam eylemleri değerlerle uyumlar.'),
  ('burnout', 'tükenmişlik', 'daily life', 'advanced', 'en', 'Constant chores can lead to burnout.', 'Sürekli ev işleri tükenmişliğe yol açabilir.'),
  ('prioritization', 'önceliklendirme', 'daily life', 'advanced', 'en', 'Prioritization clears mental clutter.', 'Önceliklendirme zihinsel dağınıklığı temizler.'),
  ('delegation', 'devretme', 'daily life', 'advanced', 'en', 'Delegation shares household responsibility.', 'Devretme ev sorumluluğunu paylaştırır.'),
  ('habit stacking', 'alışkanlık yığınlama', 'daily life', 'advanced', 'en', 'Habit stacking links new routines to old ones.', 'Alışkanlık yığınlama yeni rutinleri eskilerine bağlar.'),
  ('decision fatigue', 'karar yorgunluğu', 'daily life', 'advanced', 'en', 'Decision fatigue hits after many small choices.', 'Karar yorgunluğu birçok küçük seçimden sonra gelir.'),
  ('financial literacy', 'finansal okuryazarlık', 'daily life', 'advanced', 'en', 'Financial literacy improves daily budgeting.', 'Finansal okuryazarlık günlük bütçelemeyi iyileştirir.'),
  ('emergency fund', 'acil durum fonu', 'daily life', 'advanced', 'en', 'An emergency fund covers sudden repairs.', 'Acil durum fonu ani onarımları karşılar.'),
  ('compound interest', 'bileşik faiz', 'daily life', 'advanced', 'en', 'Compound interest grows savings over years.', 'Bileşik faiz birikimleri yıllar içinde büyütür.'),
  ('lifestyle inflation', 'yaşam tarzı enflasyonu', 'daily life', 'advanced', 'en', 'Lifestyle inflation follows higher income.', 'Yaşam tarzı enflasyonu daha yüksek geliri takip eder.'),
  ('digital detox', 'dijital detoks', 'daily life', 'advanced', 'en', 'A digital detox improves sleep quality.', 'Dijital detoks uyku kalitesini artırır.'),
  ('cognitive load', 'bilişsel yük', 'daily life', 'advanced', 'en', 'Too many reminders increase cognitive load.', 'Çok fazla hatırlatıcı bilişsel yükü artırır.'),
  ('emotional labor', 'duygusal emek', 'daily life', 'advanced', 'en', 'Emotional labor often falls on one partner.', 'Duygusal emek genelde tek bir partnere düşer.'),
  ('intergenerational', 'nesiller arası', 'daily life', 'advanced', 'en', 'Intergenerational homes need clear boundaries.', 'Nesiller arası evler net sınırlar gerektirir.'),
  ('aging in place', 'evde yaşlanma', 'daily life', 'advanced', 'en', 'Aging in place requires home modifications.', 'Evde yaşlanma ev düzenlemeleri gerektirir.'),
  ('food insecurity', 'gıda güvensizliği', 'daily life', 'advanced', 'en', 'Food insecurity affects many households.', 'Gıda güvensizliği birçok haneyi etkiler.'),
  ('time poverty', 'zaman yoksulluğu', 'daily life', 'advanced', 'en', 'Time poverty limits leisure and rest.', 'Zaman yoksulluğu dinlenmeyi ve boş zamanı sınırlar.'),
  ('social capital', 'sosyal sermaye', 'daily life', 'advanced', 'en', 'Neighbors build social capital through trust.', 'Komşular güven yoluyla sosyal sermaye oluşturur.'),
  ('gentrification', 'soylulaştırma', 'daily life', 'advanced', 'en', 'Gentrification raises rents in old districts.', 'Soylulaştırma eski semtlerde kiraları artırır.'),
  ('workation', 'çalışmalı tatil', 'daily life', 'advanced', 'en', 'A workation blends remote work and travel.', 'Çalışmalı tatil uzaktan çalışmayı seyahatle birleştirir.'),
  ('hygge', 'hygge', 'daily life', 'advanced', 'en', 'They create hygge with candles and tea.', 'Mum ve çayla hygge yaratıyorlar.'),
  ('cashier', 'kasiyer', 'jobs', 'beginner', 'en', 'The cashier scanned my items quickly.', 'Kasiyer ürünlerimi hızlıca okuttu.'),
  ('waiter', 'garson', 'jobs', 'beginner', 'en', 'The waiter brought our drinks.', 'Garson içeceklerimizi getirdi.'),
  ('mechanic', 'tamirci', 'jobs', 'beginner', 'en', 'The mechanic fixed my car engine.', 'Tamirci araba motorumu tamir etti.'),
  ('farmer', 'çiftçi', 'jobs', 'beginner', 'en', 'The farmer harvests wheat in summer.', 'Çiftçi yazın buğday hasat eder.'),
  ('builder', 'inşaatçı', 'jobs', 'beginner', 'en', 'Builders started work on the new house.', 'İnşaatçılar yeni evde çalışmaya başladı.');
