INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('comorbidity', 'eş hastalık', 'health', 'advanced', 'en', 'Comorbidity complicates treatment plans.', 'Eş hastalık tedavi planlarını karmaşıklaştırır.'),
  ('prognosis', 'prognoz', 'health', 'advanced', 'en', 'The prognosis improved after therapy.', 'Prognoz tedaviden sonra iyileşti.'),
  ('pathology', 'patoloji', 'health', 'advanced', 'en', 'Pathology confirmed the diagnosis.', 'Patoloji tanıyı doğruladı.'),
  ('biomarker', 'biyobelirteç', 'health', 'advanced', 'en', 'Biomarkers guide personalized medicine.', 'Biyobelirteçler kişiselleştirilmiş tıbbı yönlendirir.'),
  ('placebo effect', 'plasebo etkisi', 'health', 'advanced', 'en', 'The placebo effect can reduce reported pain.', 'Plasebo etkisi bildirilen ağrıyı azaltabilir.'),
  ('antibody', 'antikor', 'health', 'advanced', 'en', 'Antibodies fight foreign invaders.', 'Antikorlar yabancı istilacılarla savaşır.'),
  ('autoimmune', 'otoimmün', 'health', 'advanced', 'en', 'Autoimmune diseases attack healthy tissue.', 'Otoimmün hastalıklar sağlıklı dokuya saldırır.'),
  ('metabolism', 'metabolizma', 'health', 'advanced', 'en', 'Metabolism slows with age for many people.', 'Birçok kişide metabolizma yaşla yavaşlar.'),
  ('homeostasis', 'homeostaz', 'health', 'advanced', 'en', 'The body maintains homeostasis through feedback.', 'Vücut geri bildirimle homeostazı korur.'),
  ('epidemiology', 'epidemiyoloji', 'health', 'advanced', 'en', 'Epidemiology tracks disease spread patterns.', 'Epidemiyoloji hastalık yayılım kalıplarını izler.'),
  ('palliative care', 'palyatif bakım', 'health', 'advanced', 'en', 'Palliative care focuses on comfort.', 'Palyatif bakım konfora odaklanır.'),
  ('informed consent', 'bilgilendirilmiş onam', 'health', 'advanced', 'en', 'Surgery requires informed consent.', 'Ameliyat bilgilendirilmiş onam gerektirir.'),
  ('clinical trial', 'klinik deneme', 'health', 'advanced', 'en', 'New drugs pass through clinical trials.', 'Yeni ilaçlar klinik denemelerden geçer.'),
  ('antimicrobial resistance', 'antimikrobiyal direnç', 'health', 'advanced', 'en', 'Antimicrobial resistance threatens global health.', 'Antimikrobiyal direnç küresel sağlığı tehdit eder.'),
  ('public health', 'halk sağlığı', 'health', 'advanced', 'en', 'Public health campaigns promote vaccination.', 'Halk sağlığı kampanyaları aşılamayı teşvik eder.'),
  ('health literacy', 'sağlık okuryazarlığı', 'health', 'advanced', 'en', 'Health literacy improves treatment adherence.', 'Sağlık okuryazarlığı tedaviye uyumu artırır.'),
  ('psychosomatic', 'psikosomatik', 'health', 'advanced', 'en', 'Stress can trigger psychosomatic symptoms.', 'Stres psikosomatik belirtileri tetikleyebilir.'),
  ('neuroplasticity', 'nöroplastisite', 'health', 'advanced', 'en', 'Neuroplasticity allows the brain to adapt.', 'Nöroplastisite beynin uyum sağlamasına izin verir.'),
  ('gut microbiome', 'bağırsak mikrobiyomu', 'health', 'advanced', 'en', 'The gut microbiome affects immunity.', 'Bağırsak mikrobiyomu bağışıklığı etkiler.'),
  ('telehealth parity', 'tele sağlık eşitliği', 'health', 'advanced', 'en', 'Telehealth parity expands rural access.', 'Tele sağlık eşitliği kırsal erişimi genişletir.'),
  ('precision medicine', 'hassas tıp', 'health', 'advanced', 'en', 'Precision medicine targets genetic profiles.', 'Hassas tıp genetik profillere odaklanır.'),
  ('health equity', 'sağlık eşitliği', 'health', 'advanced', 'en', 'Health equity reduces care gaps.', 'Sağlık eşitliği bakım boşluklarını azaltır.'),
  ('social determinants', 'sosyal belirleyiciler', 'health', 'advanced', 'en', 'Social determinants shape health outcomes.', 'Sosyal belirleyiciler sağlık sonuçlarını şekillendirir.'),
  ('longevity', 'uzun ömür', 'health', 'advanced', 'en', 'Exercise and diet support longevity.', 'Egzersiz ve diyet uzun ömürü destekler.'),
  ('oxidative stress', 'oksidatif stres', 'health', 'advanced', 'en', 'Antioxidants may reduce oxidative stress.', 'Antioksidanlar oksidatif stresi azaltabilir.'),
  ('hormonal imbalance', 'hormonal dengesizlik', 'health', 'advanced', 'en', 'Hormonal imbalance affects mood and energy.', 'Hormonal dengesizlik ruh halini ve enerjiyi etkiler.'),
  ('sleep hygiene', 'uyku hijyeni', 'health', 'advanced', 'en', 'Sleep hygiene includes a dark, cool room.', 'Uyku hijyeni karanlık, serin bir oda içerir.'),
  ('mindfulness therapy', 'farkındalık terapisi', 'health', 'advanced', 'en', 'Mindfulness therapy lowers stress markers.', 'Farkındalık terapisi stres belirteçlerini düşürür.'),
  ('rehabilitation protocol', 'rehabilitasyon protokolü', 'health', 'advanced', 'en', 'Follow the rehabilitation protocol daily.', 'Rehabilitasyon protokolünü her gün uygula.'),
  ('medical ethics', 'tıbbi etik', 'health', 'advanced', 'en', 'Medical ethics guides difficult decisions.', 'Tıbbi etik zor kararları yönlendirir.'),
  ('tree', 'ağaç', 'nature', 'beginner', 'en', 'The old tree shades the bench.', 'Eski ağaç bankı gölgeliyor.'),
  ('flower', 'çiçek', 'nature', 'beginner', 'en', 'She picked a red flower.', 'Kırmızı bir çiçek topladı.'),
  ('river', 'nehir', 'nature', 'beginner', 'en', 'The river flows to the sea.', 'Nehir denize akıyor.'),
  ('mountain', 'dağ', 'nature', 'beginner', 'en', 'Snow covers the mountain peak.', 'Kar dağ zirvesini kaplıyor.'),
  ('forest', 'orman', 'nature', 'beginner', 'en', 'We walked through a quiet forest.', 'Sessiz bir ormanda yürüdük.'),
  ('lake', 'göl', 'nature', 'beginner', 'en', 'The lake is calm at sunrise.', 'Göl gün doğumunda sakin.'),
  ('ocean', 'okyanus', 'nature', 'beginner', 'en', 'The ocean stretches beyond the horizon.', 'Okyanus ufkun ötesine uzanıyor.'),
  ('beach', 'plaj', 'nature', 'beginner', 'en', 'Children play on the sandy beach.', 'Çocuklar kumlu plajda oynuyor.'),
  ('sky', 'gökyüzü', 'nature', 'beginner', 'en', 'The sky turned pink at sunset.', 'Gün batımında gökyüzü pembe oldu.'),
  ('cloud', 'bulut', 'nature', 'beginner', 'en', 'Dark clouds mean rain soon.', 'Koyu bulutlar yakında yağmur demektir.'),
  ('rain', 'yağmur', 'nature', 'beginner', 'en', 'Light rain watered the garden.', 'Hafif yağmur bahçeyi suladı.'),
  ('snow', 'kar', 'nature', 'beginner', 'en', 'Snow fell all night.', 'Bütün gece kar yağdı.'),
  ('wind', 'rüzgar', 'nature', 'beginner', 'en', 'Strong wind bent the trees.', 'Kuvvetli rüzgar ağaçları eğdi.'),
  ('sun', 'güneş', 'nature', 'beginner', 'en', 'The sun rose over the hills.', 'Güneş tepelerin üzerinden doğdu.'),
  ('moon', 'ay', 'nature', 'beginner', 'en', 'The full moon lit the path.', 'Dolunay patikayı aydınlattı.'),
  ('star', 'yıldız', 'nature', 'beginner', 'en', 'Stars shine on clear nights.', 'Yıldızlar açık gecelerde parlar.'),
  ('rock', 'kaya', 'nature', 'beginner', 'en', 'He sat on a flat rock.', 'Düz bir kayanın üzerine oturdu.'),
  ('soil', 'toprak', 'nature', 'beginner', 'en', 'Rich soil helps plants grow.', 'Zengin toprak bitkilerin büyümesine yardım eder.'),
  ('grass', 'çimen', 'nature', 'beginner', 'en', 'Fresh grass smells sweet after rain.', 'Taze çimen yağmurdan sonra tatlı kokar.'),
  ('leaf', 'yaprak', 'nature', 'beginner', 'en', 'A yellow leaf fell slowly.', 'Sarı bir yaprak yavaşça düştü.'),
  ('seed', 'tohum', 'nature', 'beginner', 'en', 'Plant the seed in spring.', 'Tohumu ilkbaharda ek.'),
  ('hill', 'tepe', 'nature', 'beginner', 'en', 'We climbed the green hill.', 'Yeşil tepeye tırmandık.'),
  ('valley', 'vadi', 'nature', 'beginner', 'en', 'Mist filled the morning valley.', 'Sabah vadisini sis doldurdu.'),
  ('island', 'ada', 'nature', 'beginner', 'en', 'The island is reachable by ferry.', 'Adaya feribotla ulaşılır.'),
  ('desert', 'çöl', 'nature', 'beginner', 'en', 'The desert gets very hot by noon.', 'Çöl öğlene kadar çok ısınır.'),
  ('waterfall', 'şelale', 'nature', 'beginner', 'en', 'We heard the waterfall from far away.', 'Şelaleyi uzaktan duyduk.'),
  ('cave', 'mağara', 'nature', 'beginner', 'en', 'Bats live inside the cave.', 'Yarasalar mağaranın içinde yaşar.'),
  ('field', 'tarla', 'nature', 'beginner', 'en', 'Wheat waves in the open field.', 'Buğday açık tarlada dalgalanıyor.'),
  ('season', 'mevsim', 'nature', 'beginner', 'en', 'Each season changes the landscape.', 'Her mevsim manzarayı değiştirir.'),
  ('weather', 'hava', 'nature', 'beginner', 'en', 'Check the weather before hiking.', 'Yürüyüşten önce havayı kontrol et.'),
  ('ecosystem', 'ekosistem', 'nature', 'intermediate', 'en', 'Wetlands are fragile ecosystems.', 'Sulak alanlar kırılgan ekosistemlerdir.'),
  ('biodiversity', 'biyoçeşitlilik', 'nature', 'intermediate', 'en', 'Biodiversity keeps nature resilient.', 'Biyoçeşitlilik doğayı dayanıklı tutar.'),
  ('climate', 'iklim', 'nature', 'intermediate', 'en', 'Climate shapes regional plant life.', 'İklim bölgesel bitki örtüsünü şekillendirir.'),
  ('drought', 'kuraklık', 'nature', 'intermediate', 'en', 'Drought dried the riverbed.', 'Kuraklık nehir yatağını kuruttu.'),
  ('flood', 'sel', 'nature', 'intermediate', 'en', 'Heavy rain caused a flood.', 'Şiddetli yağmur sel yaptı.'),
  ('erosion', 'erozyon', 'nature', 'intermediate', 'en', 'Erosion washed soil down the slope.', 'Erozyon toprağı yamaçtan aşağı süpürdü.'),
  ('pollution', 'kirlilik', 'nature', 'intermediate', 'en', 'Pollution harms river wildlife.', 'Kirlilik nehir yaban hayatına zarar verir.'),
  ('recycle', 'geri dönüştürmek', 'nature', 'intermediate', 'en', 'Recycle paper to save trees.', 'Ağaçları korumak için kağıdı geri dönüştür.'),
  ('renewable energy', 'yenilenebilir enerji', 'nature', 'intermediate', 'en', 'Solar panels provide renewable energy.', 'Güneş panelleri yenilenebilir enerji sağlar.'),
  ('greenhouse gas', 'sera gazı', 'nature', 'intermediate', 'en', 'Greenhouse gases trap heat in the air.', 'Sera gazları havada ısıyı hapseder.'),
  ('carbon footprint', 'karbon ayak izi', 'nature', 'intermediate', 'en', 'Flying increases your carbon footprint.', 'Uçmak karbon ayak izini artırır.'),
  ('conservation', 'koruma', 'nature', 'intermediate', 'en', 'Conservation protects endangered forests.', 'Koruma nesli tükenmekte olan ormanları korur.'),
  ('habitat loss', 'yaşam alanı kaybı', 'nature', 'intermediate', 'en', 'Habitat loss threatens many species.', 'Yaşam alanı kaybı birçok türü tehdit eder.'),
  ('wildfire', 'ormansızlık yangını', 'nature', 'intermediate', 'en', 'A wildfire spread across the hills.', 'Orman yangını tepelere yayıldı.'),
  ('monsoon', 'muson', 'nature', 'intermediate', 'en', 'Monsoon rains refill the reservoirs.', 'Muson yağmurları rezervuarları doldurur.'),
  ('tide', 'gelgit', 'nature', 'intermediate', 'en', 'The tide rose quickly at dusk.', 'Alacakaranlıkta gelgit hızla yükseldi.'),
  ('glacier', 'buzul', 'nature', 'intermediate', 'en', 'The glacier melts faster each year.', 'Buzul her yıl daha hızlı eriyor.'),
  ('coral reef', 'mercan resifi', 'nature', 'intermediate', 'en', 'Coral reefs shelter colorful fish.', 'Mercan resifleri renkli balıklara barınak sağlar.'),
  ('wetland', 'sulak alan', 'nature', 'intermediate', 'en', 'Wetlands filter water naturally.', 'Sulak alanlar suyu doğal olarak filtreler.'),
  ('canopy', 'örtü', 'nature', 'intermediate', 'en', 'Monkeys move through the forest canopy.', 'Maymunlar orman örtüsünde hareket eder.'),
  ('pollination', 'tozlaşma', 'nature', 'intermediate', 'en', 'Bees support pollination in gardens.', 'Arılar bahçelerde tozlaşmayı destekler.'),
  ('compost', 'kompost', 'nature', 'intermediate', 'en', 'Compost turns scraps into rich soil.', 'Kompost artıkları zengin toprağa dönüştürür.'),
  ('sustainable', 'sürdürülebilir', 'nature', 'intermediate', 'en', 'Sustainable farming protects water sources.', 'Sürdürülebilir tarım su kaynaklarını korur.'),
  ('deforestation', 'ormansızlaşma', 'nature', 'intermediate', 'en', 'Deforestation reduces animal homes.', 'Ormansızlaşma hayvan yuvalarını azaltır.'),
  ('reforestation', 'ağaçlandırma', 'nature', 'intermediate', 'en', 'Reforestation restores damaged land.', 'Ağaçlandırma hasarlı araziyi iyileştirir.'),
  ('watershed', 'havza', 'nature', 'intermediate', 'en', 'The watershed feeds the city reservoir.', 'Havza şehir rezervuarını besler.'),
  ('air quality', 'hava kalitesi', 'nature', 'intermediate', 'en', 'Air quality worsens on busy roads.', 'Hava kalitesi yoğun yollarda kötüleşir.'),
  ('microclimate', 'mikro iklim', 'nature', 'intermediate', 'en', 'Valleys create a cooler microclimate.', 'Vadiler daha serin bir mikro iklim oluşturur.'),
  ('landslide', 'toprak kayması', 'nature', 'intermediate', 'en', 'Heavy rain triggered a landslide.', 'Şiddetli yağmur toprak kaymasını tetikledi.'),
  ('permafrost', 'donmuş toprak', 'nature', 'intermediate', 'en', 'Permafrost stores ancient carbon.', 'Donmuş toprak eski karbonu depolar.'),
  ('anthropocene', 'antroposen', 'nature', 'advanced', 'en', 'Scientists debate the start of the Anthropocene.', 'Bilim insanları Antroposen''in başlangıcını tartışıyor.'),
  ('biogeochemical cycle', 'biyojeokimyasal döngü', 'nature', 'advanced', 'en', 'The carbon cycle is a biogeochemical cycle.', 'Karbon döngüsü biyojeokimyasal bir döngüdür.'),
  ('ecological succession', 'ekolojik süksesyon', 'nature', 'advanced', 'en', 'Ecological succession rebuilds burned forests.', 'Ekolojik süksesyon yanmış ormanları yeniden kurar.'),
  ('keystone species', 'taş tür', 'nature', 'advanced', 'en', 'Beavers act as a keystone species.', 'Kunduzlar taş tür olarak işlev görür.'),
  ('trophic cascade', 'trofik domino', 'nature', 'advanced', 'en', 'Wolf reintroduction caused a trophic cascade.', 'Kurt yeniden doğaya salınması trofik domino etkisi yarattı.'),
  ('albedo effect', 'albedo etkisi', 'nature', 'advanced', 'en', 'Snow cover increases the albedo effect.', 'Kar örtüsü albedo etkisini artırır.'),
  ('ocean acidification', 'okyanus asitlenmesi', 'nature', 'advanced', 'en', 'Ocean acidification harms shell-forming life.', 'Okyanus asitlenmesi kabuk oluşturan canlılara zarar verir.'),
  ('desertification', 'çölleşme', 'nature', 'advanced', 'en', 'Overgrazing speeds desertification.', 'Aşırı otlatma çölleşmeyi hızlandırır.'),
  ('carbon sequestration', 'karbon tutma', 'nature', 'advanced', 'en', 'Forests aid carbon sequestration.', 'Ormanlar karbon tutmaya yardım eder.');