INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('sugar', 'şeker', 'foods', 'beginner', 'en', 'Too much sugar is unhealthy.', 'Çok şeker sağlıksızdır.'),
  ('butter', 'tereyağı', 'foods', 'beginner', 'en', 'Spread butter on warm toast.', 'Sıcak tostun üzerine tereyağı sür.'),
  ('yogurt', 'yoğurt', 'foods', 'beginner', 'en', 'Greek yogurt is thick and creamy.', 'Yunan yoğurdu koyu ve kremalıdır.'),
  ('honey', 'bal', 'foods', 'beginner', 'en', 'Honey sweetens tea naturally.', 'Bal çayı doğal olarak tatlandırır.'),
  ('olive oil', 'zeytinyağı', 'foods', 'beginner', 'en', 'Drizzle olive oil over the salad.', 'Salatanın üzerine zeytinyağı gezdir.'),
  ('pasta', 'makarna', 'foods', 'beginner', 'en', 'We cook pasta for dinner tonight.', 'Bu akşam akşam yemeği için makarna pişiriyoruz.'),
  ('soup', 'çorba', 'foods', 'beginner', 'en', 'Hot soup warms you in winter.', 'Sıcak çorba kışın ısıtır.'),
  ('salad', 'salata', 'foods', 'beginner', 'en', 'A green salad is light and fresh.', 'Yeşil salata hafif ve tazedir.'),
  ('meat', 'et', 'foods', 'beginner', 'en', 'They avoid red meat for health.', 'Sağlık için kırmızı etten kaçınıyorlar.'),
  ('lentil', 'mercimek', 'foods', 'beginner', 'en', 'Lentil soup is popular here.', 'Mercimek çorbası burada popülerdir.'),
  ('appetizer', 'meze', 'foods', 'intermediate', 'en', 'We ordered appetizers before the main course.', 'Ana yemekten önce meze sipariş ettik.'),
  ('marinate', 'marine etmek', 'foods', 'intermediate', 'en', 'Marinate the meat overnight.', 'Eti bir gece marine et.'),
  ('seasoning', 'baharat', 'foods', 'intermediate', 'en', 'Use seasoning sparingly at first.', 'Başta baharatı az kullan.'),
  ('gluten-free', 'glütensiz', 'foods', 'intermediate', 'en', 'This bakery sells gluten-free bread.', 'Bu fırın glütensiz ekmek satıyor.'),
  ('organic', 'organik', 'foods', 'intermediate', 'en', 'Organic vegetables cost a bit more.', 'Organik sebzeler biraz daha pahalı.'),
  ('preservative', 'koruyucu madde', 'foods', 'intermediate', 'en', 'Check labels for preservatives.', 'Etiketlerde koruyucu maddeleri kontrol et.'),
  ('fermentation', 'fermentasyon', 'foods', 'intermediate', 'en', 'Fermentation gives yogurt its tang.', 'Fermentasyon yoğurda ekşiliğini verir.'),
  ('pastry', 'hamur işi', 'foods', 'intermediate', 'en', 'The pastry was flaky and buttery.', 'Hamur işi gevrek ve tereyağlıydı.'),
  ('grill', 'ızgara', 'foods', 'intermediate', 'en', 'Grill the vegetables until tender.', 'Sebzeleri yumuşayana kadar ızgarada pişir.'),
  ('simmer', 'kısık ateşte pişirmek', 'foods', 'intermediate', 'en', 'Simmer the sauce for twenty minutes.', 'Sosu yirmi dakika kısık ateşte pişir.'),
  ('dough', 'hamur', 'foods', 'intermediate', 'en', 'Let the dough rise for an hour.', 'Hamurun bir saat mayalanmasına izin ver.'),
  ('broccoli', 'brokoli', 'foods', 'intermediate', 'en', 'Steam broccoli to keep nutrients.', 'Besinleri korumak için brokoliyi buharda pişir.'),
  ('spinach', 'ıspanak', 'foods', 'intermediate', 'en', 'Spinach works well in omelets.', 'Ispanak omletlerde iyi gider.'),
  ('avocado', 'avokado', 'foods', 'intermediate', 'en', 'Avocado adds creaminess to toast.', 'Avokado tosta kremalılık katar.'),
  ('seafood', 'deniz ürünleri', 'foods', 'intermediate', 'en', 'The restaurant specializes in seafood.', 'Restoran deniz ürünlerinde uzmanlaşmış.'),
  ('dairy', 'süt ürünleri', 'foods', 'intermediate', 'en', 'Some people avoid dairy products.', 'Bazı insanlar süt ürünlerinden kaçınır.'),
  ('whole grain', 'tam tahıl', 'foods', 'intermediate', 'en', 'Whole grain bread has more fiber.', 'Tam tahıl ekmeğin daha fazla lifi vardır.'),
  ('food allergy', 'gıda alerjisi', 'foods', 'intermediate', 'en', 'Nut food allergy can be serious.', 'Kuruyemiş gıda alerjisi ciddi olabilir.'),
  ('portion size', 'porsiyon boyutu', 'foods', 'intermediate', 'en', 'Watch portion size to avoid overeating.', 'Aşırı yememek için porsiyon boyutuna dikkat et.'),
  ('leftovers', 'artık yemek', 'foods', 'intermediate', 'en', 'Store leftovers in the fridge.', 'Artık yemeği buzdolabında sakla.'),
  ('takeout', 'paket servis', 'foods', 'intermediate', 'en', 'We ordered takeout on busy nights.', 'Yoğun gecelerde paket servis sipariş ettik.'),
  ('buffet', 'açık büfe', 'foods', 'intermediate', 'en', 'The hotel buffet had many options.', 'Otel açık büfesinde birçok seçenek vardı.'),
  ('cuisine', 'mutfak', 'foods', 'intermediate', 'en', 'Turkish cuisine uses rich spices.', 'Türk mutfağı zengin baharatlar kullanır.'),
  ('recipe', 'tarif', 'foods', 'intermediate', 'en', 'Follow the recipe step by step.', 'Tarifi adım adım takip et.'),
  ('ripe', 'olgun', 'foods', 'intermediate', 'en', 'Pick ripe tomatoes for sauce.', 'Sos için olgun domates seç.'),
  ('spoil', 'bozulmak', 'foods', 'intermediate', 'en', 'Milk can spoil quickly in heat.', 'Süt sıcakta hızla bozulabilir.'),
  ('pantry staple', 'kiler temeli', 'foods', 'intermediate', 'en', 'Rice is a pantry staple in many homes.', 'Pirinç birçok evde kiler temelidir.'),
  ('herb', 'ot', 'foods', 'intermediate', 'en', 'Fresh herbs improve any dish.', 'Taze otlar her yemeği iyileştirir.'),
  ('spice blend', 'baharat karışımı', 'foods', 'intermediate', 'en', 'This spice blend is for kebabs.', 'Bu baharat karışımı kebap içindir.'),
  ('food processor', 'mutfak robotu', 'foods', 'intermediate', 'en', 'A food processor chops nuts fast.', 'Mutfak robotu kuruyemişleri hızlı doğrar.');
