INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('ecosystem', 'ekosistem', 'nature', 'intermediate', 'en', 'Wetlands are fragile ecosystems.', 'Sulak alanlar kırılgan ekosistemlerdir.'),
  ('biodiversity', 'biyoçeşitlilik', 'nature', 'intermediate', 'en', 'Biodiversity keeps nature resilient.', 'Biyoçeşitlilik doğayı dayanıklı tutar.'),
  ('climate', 'iklim', 'nature', 'intermediate', 'en', 'Climate shapes regional plant life.', 'İklim bölgesel bitki örtüsünü şekillendirir.'),
  ('drought', 'kuraklık', 'nature', 'intermediate', 'en', 'Drought dried the riverbed.', 'Kuraklık nehir yatağını kuruttu.'),
  ('flood', 'sel', 'nature', 'intermediate', 'en', 'Heavy rain caused a flood.', 'Şiddetli yağmur sel yaptı.'),
  ('erosion', 'erozyon', 'nature', 'intermediate', 'en', 'Erosion washed soil down the slope.', 'Erozyon toprağı yamaçtan aşağı süpürdü.'),
  ('pollution', 'kirlilik', 'nature', 'intermediate', 'en', 'Pollution harms river wildlife.', 'Kirlilik nehir yaban hayatına zarar verir.'),
  ('recycle', 'geri dönüştürmek', 'nature', 'intermediate', 'en', 'Recycle paper to save trees.', 'Ağaçları korumak için kağıdı geri dönüştür.'),
  ('renewable energy', 'yenilenebilir enerji', 'nature', 'intermediate', 'en', 'Solar panels provide renewable energy.', 'Güneş panelleri yenilenebilir enerji sağlar.'),
  ('greenhouse gas', 'sera gazı', 'nature', 'intermediate', 'en', 'Greenhouse gases trap heat in the air.', 'Sera gazları havada ısıyı hapseder.'),
  ('carbon footprint', 'karbon ayak izi', 'nature', 'intermediate', 'en', 'Flying increases your carbon footprint.', 'Uçmak karbon ayak izini artırır.'),
  ('conservation', 'koruma', 'nature', 'intermediate', 'en', 'Conservation protects endangered forests.', 'Koruma nesli tükenmekte olan ormanları korur.'),
  ('habitat loss', 'yaşam alanı kaybı', 'nature', 'intermediate', 'en', 'Habitat loss threatens many species.', 'Yaşam alanı kaybı birçok türü tehdit eder.'),
  ('wildfire', 'ormansızlık yangını', 'nature', 'intermediate', 'en', 'A wildfire spread across the hills.', 'Orman yangını tepelere yayıldı.'),
  ('monsoon', 'muson', 'nature', 'intermediate', 'en', 'Monsoon rains refill the reservoirs.', 'Muson yağmurları rezervuarları doldurur.'),
  ('tide', 'gelgit', 'nature', 'intermediate', 'en', 'The tide rose quickly at dusk.', 'Alacakaranlıkta gelgit hızla yükseldi.'),
  ('glacier', 'buzul', 'nature', 'intermediate', 'en', 'The glacier melts faster each year.', 'Buzul her yıl daha hızlı eriyor.'),
  ('coral reef', 'mercan resifi', 'nature', 'intermediate', 'en', 'Coral reefs shelter colorful fish.', 'Mercan resifleri renkli balıklara barınak sağlar.'),
  ('wetland', 'sulak alan', 'nature', 'intermediate', 'en', 'Wetlands filter water naturally.', 'Sulak alanlar suyu doğal olarak filtreler.'),
  ('canopy', 'örtü', 'nature', 'intermediate', 'en', 'Monkeys move through the forest canopy.', 'Maymunlar orman örtüsünde hareket eder.'),
  ('pollination', 'tozlaşma', 'nature', 'intermediate', 'en', 'Bees support pollination in gardens.', 'Arılar bahçelerde tozlaşmayı destekler.'),
  ('compost', 'kompost', 'nature', 'intermediate', 'en', 'Compost turns scraps into rich soil.', 'Kompost artıkları zengin toprağa dönüştürür.'),
  ('sustainable', 'sürdürülebilir', 'nature', 'intermediate', 'en', 'Sustainable farming protects water sources.', 'Sürdürülebilir tarım su kaynaklarını korur.'),
  ('deforestation', 'ormansızlaşma', 'nature', 'intermediate', 'en', 'Deforestation reduces animal homes.', 'Ormansızlaşma hayvan yuvalarını azaltır.'),
  ('reforestation', 'ağaçlandırma', 'nature', 'intermediate', 'en', 'Reforestation restores damaged land.', 'Ağaçlandırma hasarlı araziyi iyileştirir.'),
  ('watershed', 'havza', 'nature', 'intermediate', 'en', 'The watershed feeds the city reservoir.', 'Havza şehir rezervuarını besler.'),
  ('air quality', 'hava kalitesi', 'nature', 'intermediate', 'en', 'Air quality worsens on busy roads.', 'Hava kalitesi yoğun yollarda kötüleşir.'),
  ('microclimate', 'mikro iklim', 'nature', 'intermediate', 'en', 'Valleys create a cooler microclimate.', 'Vadiler daha serin bir mikro iklim oluşturur.'),
  ('landslide', 'toprak kayması', 'nature', 'intermediate', 'en', 'Heavy rain triggered a landslide.', 'Şiddetli yağmur toprak kaymasını tetikledi.'),
  ('permafrost', 'donmuş toprak', 'nature', 'intermediate', 'en', 'Permafrost stores ancient carbon.', 'Donmuş toprak eski karbonu depolar.'),
  ('anthropocene', 'antroposen', 'nature', 'advanced', 'en', 'Scientists debate the start of the Anthropocene.', 'Bilim insanları Antroposen''in başlangıcını tartışıyor.'),
  ('biogeochemical cycle', 'biyojeokimyasal döngü', 'nature', 'advanced', 'en', 'The carbon cycle is a biogeochemical cycle.', 'Karbon döngüsü biyojeokimyasal bir döngüdür.'),
  ('ecological succession', 'ekolojik süksesyon', 'nature', 'advanced', 'en', 'Ecological succession rebuilds burned forests.', 'Ekolojik süksesyon yanmış ormanları yeniden kurar.'),
  ('keystone species', 'taş tür', 'nature', 'advanced', 'en', 'Beavers act as a keystone species.', 'Kunduzlar taş tür olarak işlev görür.'),
  ('trophic cascade', 'trofik domino', 'nature', 'advanced', 'en', 'Wolf reintroduction caused a trophic cascade.', 'Kurt yeniden doğaya salınması trofik domino etkisi yarattı.'),
  ('albedo effect', 'albedo etkisi', 'nature', 'advanced', 'en', 'Snow cover increases the albedo effect.', 'Kar örtüsü albedo etkisini artırır.'),
  ('ocean acidification', 'okyanus asitlenmesi', 'nature', 'advanced', 'en', 'Ocean acidification harms shell-forming life.', 'Okyanus asitlenmesi kabuk oluşturan canlılara zarar verir.'),
  ('desertification', 'çölleşme', 'nature', 'advanced', 'en', 'Overgrazing speeds desertification.', 'Aşırı otlatma çölleşmeyi hızlandırır.'),
  ('carbon sequestration', 'karbon tutma', 'nature', 'advanced', 'en', 'Forests aid carbon sequestration.', 'Ormanlar karbon tutmaya yardım eder.'),
  ('mitigation', 'hafifletme', 'nature', 'advanced', 'en', 'Climate mitigation requires global cooperation.', 'İklim hafifletmesi küresel iş birliği gerektirir.');
