INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('proportional dressing', 'orantılı giyinme', 'clothes', 'advanced', 'en', 'Proportional dressing balances silhouette.', 'Orantılı giyinme silueti dengeler.'),
  ('monochrome styling', 'monokrom stil', 'clothes', 'advanced', 'en', 'Monochrome styling looks sleek and modern.', 'Monokrom stil şık ve modern görünür.'),
  ('archival fashion', 'arşiv modası', 'clothes', 'advanced', 'en', 'Collectors hunt rare archival fashion pieces.', 'Koleksiyoncular nadir arşiv modası parçalarını arar.'),
  ('fashion forecasting', 'moda öngörüsü', 'clothes', 'advanced', 'en', 'Fashion forecasting guides next season colors.', 'Moda öngörüsü gelecek sezon renklerini yönlendirir.'),
  ('lookbook', 'lookbook', 'clothes', 'advanced', 'en', 'The lookbook showcases the new line.', 'Lookbook yeni koleksiyonu sergiliyor.'),
  ('runway collection', 'podyum koleksiyonu', 'clothes', 'advanced', 'en', 'The runway collection debuted in Milan.', 'Podyum koleksiyonu Milano''da tanıtıldı.'),
  ('fashion merchandising', 'moda merchandising', 'clothes', 'advanced', 'en', 'Fashion merchandising plans store displays.', 'Moda merchandising mağaza vitrinlerini planlar.'),
  ('size inclusivity', 'beden kapsayıcılığı', 'clothes', 'advanced', 'en', 'Size inclusivity expands available ranges.', 'Beden kapsayıcılığı mevcut aralıkları genişletir.'),
  ('gender-neutral design', 'cinsiyetsiz tasarım', 'clothes', 'advanced', 'en', 'Gender-neutral design avoids rigid labels.', 'Cinsiyetsiz tasarım katı etiketlerden kaçınır.'),
  ('anti-fit philosophy', 'anti-fit felsefesi', 'clothes', 'advanced', 'en', 'Anti-fit philosophy rejects tight tailoring.', 'Anti-fit felsefesi dar terziliği reddeder.'),
  ('friend', 'arkadaş', 'relationships', 'beginner', 'en', 'She is my closest friend.', 'O en yakın arkadaşım.'),
  ('family', 'aile', 'relationships', 'beginner', 'en', 'Family dinners happen every Sunday.', 'Aile yemekleri her pazar olur.'),
  ('mother', 'anne', 'relationships', 'beginner', 'en', 'My mother calls me every week.', 'Annem beni her hafta arar.'),
  ('father', 'baba', 'relationships', 'beginner', 'en', 'His father taught him to ride a bike.', 'Babası ona bisiklete binmeyi öğretti.'),
  ('sister', 'kız kardeş', 'relationships', 'beginner', 'en', 'My sister lives in another city.', 'Kız kardeşim başka bir şehirde yaşıyor.'),
  ('brother', 'erkek kardeş', 'relationships', 'beginner', 'en', 'My brother plays guitar well.', 'Erkek kardeşim iyi gitar çalar.'),
  ('son', 'oğul', 'relationships', 'beginner', 'en', 'Their son starts school this year.', 'Oğulları bu yıl okula başlıyor.'),
  ('daughter', 'kız evlat', 'relationships', 'beginner', 'en', 'Their daughter loves painting.', 'Kız evlatları resim yapmayı seviyor.'),
  ('husband', 'koca', 'relationships', 'beginner', 'en', 'Her husband cooks on weekends.', 'Kocası hafta sonları yemek yapar.'),
  ('wife', 'eş', 'relationships', 'beginner', 'en', 'His wife works as a nurse.', 'Eşi hemşire olarak çalışıyor.'),
  ('baby', 'bebek', 'relationships', 'beginner', 'en', 'The baby slept through the night.', 'Bebek gece boyunca uyudu.'),
  ('grandmother', 'büyükanne', 'relationships', 'beginner', 'en', 'Grandmother told us old stories.', 'Büyükanne bize eski hikayeler anlattı.'),
  ('grandfather', 'büyükbaba', 'relationships', 'beginner', 'en', 'Grandfather walks in the park daily.', 'Büyükbaba her gün parkta yürür.'),
  ('uncle', 'amca/dayı', 'relationships', 'beginner', 'en', 'My uncle visited from abroad.', 'Amcam yurt dışından ziyarete geldi.'),
  ('aunt', 'teyze/hala', 'relationships', 'beginner', 'en', 'Aunt Mary baked a cake for us.', 'Teyze Mary bize kek yaptı.'),
  ('cousin', 'kuzen', 'relationships', 'beginner', 'en', 'We played with cousins at the reunion.', 'Buluşmada kuzenlerle oynadık.'),
  ('neighbor', 'komşu', 'relationships', 'beginner', 'en', 'Our neighbor watered our plants.', 'Komşumuz bitkilerimizi suladı.'),
  ('partner', 'partner', 'relationships', 'beginner', 'en', 'She introduced her partner to us.', 'Partnerini bize tanıttı.'),
  ('boyfriend', 'erkek arkadaş', 'relationships', 'beginner', 'en', 'Her boyfriend sent flowers.', 'Erkek arkadaşı çiçek gönderdi.'),
  ('girlfriend', 'kız arkadaş', 'relationships', 'beginner', 'en', 'His girlfriend studies medicine.', 'Kız arkadaşı tıp okuyor.'),
  ('classmate', 'sınıf arkadaşı', 'relationships', 'beginner', 'en', 'A classmate helped with homework.', 'Bir sınıf arkadaşı ev ödevinde yardım etti.'),
  ('colleague', 'iş arkadaşı', 'relationships', 'beginner', 'en', 'Colleagues joined the celebration.', 'İş arkadaşları kutlamaya katıldı.'),
  ('trust', 'güven', 'relationships', 'beginner', 'en', 'Trust is the base of friendship.', 'Güven dostluğun temelidir.'),
  ('love', 'sevgi', 'relationships', 'beginner', 'en', 'They show love through small acts.', 'Küçük davranışlarla sevgi gösteriyorlar.'),
  ('respect', 'saygı', 'relationships', 'beginner', 'en', 'Respect each other''s opinions.', 'Birbirinizin görüşlerine saygı gösterin.'),
  ('support', 'destek', 'relationships', 'beginner', 'en', 'Friends offer support in hard times.', 'Arkadaşlar zor zamanlarda destek sunar.'),
  ('argument', 'tartışma', 'relationships', 'beginner', 'en', 'They had a small argument yesterday.', 'Dün küçük bir tartışma yaşadılar.'),
  ('apology', 'özür', 'relationships', 'beginner', 'en', 'A sincere apology heals hurt feelings.', 'Samimi bir özür incinen duyguları iyileştirir.'),
  ('gift', 'hediye', 'relationships', 'beginner', 'en', 'She gave a thoughtful gift.', 'Düşünceli bir hediye verdi.'),
  ('invitation', 'davet', 'relationships', 'beginner', 'en', 'We sent an invitation to neighbors.', 'Komşulara davet gönderdik.');
