INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('adaptation strategy', 'uyum stratejisi', 'nature', 'advanced', 'en', 'Coastal cities need an adaptation strategy.', 'Kıyı şehirlerinin bir uyum stratejisine ihtiyacı var.'),
  ('biodiversity hotspot', 'biyoçeşitlilik noktası', 'nature', 'advanced', 'en', 'The region is a biodiversity hotspot.', 'Bölge bir biyoçeşitlilik noktasıdır.'),
  ('invasive species', 'istilacı tür', 'nature', 'advanced', 'en', 'Invasive species outcompete natives.', 'İstilacı türler yerli türlerle rekabet eder.'),
  ('phenology', 'fenoloji', 'nature', 'advanced', 'en', 'Phenology tracks seasonal biological events.', 'Fenoloji mevsimsel biyolojik olayları izler.'),
  ('symbiotic relationship', 'symbiyotik ilişki', 'nature', 'advanced', 'en', 'Lichens show a symbiotic relationship.', 'Likenler symbiyotik bir ilişki gösterir.'),
  ('watershed management', 'havza yönetimi', 'nature', 'advanced', 'en', 'Watershed management protects drinking water.', 'Havza yönetimi içme suyunu korur.'),
  ('rewilding', 'yeniden vahşileştirme', 'nature', 'advanced', 'en', 'Rewilding restores native predators.', 'Yeniden vahşileştirme yerli yırtıcıları geri getirir.'),
  ('net zero', 'net sıfır', 'nature', 'advanced', 'en', 'Many nations target net zero emissions.', 'Birçok ülke net sıfır emisyon hedefliyor.'),
  ('geoengineering', 'jeomühendislik', 'nature', 'advanced', 'en', 'Geoengineering raises ethical questions.', 'Jeomühendislik etik soruları gündeme getirir.'),
  ('intertidal zone', 'gelgit bölgesi', 'nature', 'advanced', 'en', 'Crabs thrive in the intertidal zone.', 'Yengeçler gelgit bölgesinde gelişir.'),
  ('old-growth forest', 'ilkel orman', 'nature', 'advanced', 'en', 'Old-growth forest stores vast carbon.', 'İlkel orman büyük miktarda karbon depolar.'),
  ('riparian buffer', 'kıyı tamponu', 'nature', 'advanced', 'en', 'A riparian buffer filters farm runoff.', 'Kıyı tamponu tarla akıntısını filtreler.'),
  ('ecological footprint', 'ekolojik ayak izi', 'nature', 'advanced', 'en', 'Urban lifestyles enlarge ecological footprint.', 'Kentsel yaşam tarzları ekolojik ayak izini büyütür.'),
  ('climate resilience', 'iklim dayanıklılığı', 'nature', 'advanced', 'en', 'Climate resilience plans protect coastal towns.', 'İklim dayanıklılığı planları kıyı kasabalarını korur.'),
  ('methane emissions', 'metan emisyonları', 'nature', 'advanced', 'en', 'Landfills release methane emissions.', 'Çöplükler metan emisyonları salar.'),
  ('photochemical smog', 'fotokimyasal duman', 'nature', 'advanced', 'en', 'Sunlight creates photochemical smog in cities.', 'Güneş ışığı şehirlerde fotokimyasal duman oluşturur.'),
  ('ecological indicator', 'ekolojik gösterge', 'nature', 'advanced', 'en', 'Frogs serve as an ecological indicator.', 'Kurbağalar ekolojik gösterge olarak işlev görür.'),
  ('transboundary pollution', 'sınır ötesi kirlilik', 'nature', 'advanced', 'en', 'Transboundary pollution crosses national borders.', 'Sınır ötesi kirlilik ulusal sınırları aşar.'),
  ('environmental stewardship', 'çevresel sorumluluk', 'nature', 'advanced', 'en', 'Environmental stewardship begins locally.', 'Çevresel sorumluluk yerelde başlar.'),
  ('planetary boundary', 'gezegen sınırı', 'nature', 'advanced', 'en', 'Scientists define key planetary boundaries.', 'Bilim insanları temel gezegen sınırlarını tanımlar.'),
  ('happy', 'mutlu', 'emotions', 'beginner', 'en', 'She felt happy after the good news.', 'İyi haberden sonra mutlu hissetti.'),
  ('sad', 'üzgün', 'emotions', 'beginner', 'en', 'He looked sad at the farewell.', 'Vedada üzgün görünüyordu.'),
  ('angry', 'kızgın', 'emotions', 'beginner', 'en', 'Do not speak when you are angry.', 'Kızgınken konuşma.'),
  ('scared', 'korkmuş', 'emotions', 'beginner', 'en', 'The child was scared of the dark.', 'Çocuk karanlıktan korkuyordu.'),
  ('excited', 'heyecanlı', 'emotions', 'beginner', 'en', 'We were excited about the trip.', 'Geziden heyecanlıydık.'),
  ('tired', 'yorgun', 'emotions', 'beginner', 'en', 'I am too tired to go out.', 'Dışarı çıkmak için çok yorgunum.'),
  ('nervous', 'gergin', 'emotions', 'beginner', 'en', 'She felt nervous before the exam.', 'Sınavdan önce gergin hissetti.'),
  ('calm', 'sakin', 'emotions', 'beginner', 'en', 'Deep breaths keep me calm.', 'Derin nefesler beni sakin tutar.'),
  ('proud', 'gururlu', 'emotions', 'beginner', 'en', 'Parents felt proud of their son.', 'Ebeveynler oğullarıyla gurur duydu.'),
  ('lonely', 'yalnız', 'emotions', 'beginner', 'en', 'He felt lonely in the new city.', 'Yeni şehirde yalnız hissetti.'),
  ('love', 'aşk', 'emotions', 'beginner', 'en', 'Love grows with trust and care.', 'Aşk güven ve ilgiyle büyür.'),
  ('hope', 'umut', 'emotions', 'beginner', 'en', 'Never lose hope during hard times.', 'Zor zamanlarda umudunu kaybetme.'),
  ('joy', 'sevinç', 'emotions', 'beginner', 'en', 'Their joy filled the whole room.', 'Sevinçleri tüm odayı doldurdu.'),
  ('fear', 'korku', 'emotions', 'beginner', 'en', 'Fear can stop you from trying.', 'Korku denemeni engelleyebilir.'),
  ('surprise', 'sürpriz', 'emotions', 'beginner', 'en', 'The party was a lovely surprise.', 'Parti güzel bir sürprizdi.'),
  ('worry', 'endişe', 'emotions', 'beginner', 'en', 'Worry keeps her awake at night.', 'Endişe onu gece uyutmayor.'),
  ('relief', 'rahatlama', 'emotions', 'beginner', 'en', 'Relief washed over him after the call.', 'Aramadan sonra rahatlama onu sardı.'),
  ('shame', 'utanç', 'emotions', 'beginner', 'en', 'Shame made her face turn red.', 'Utanç yüzünün kızarmasına neden oldu.'),
  ('guilt', 'suçluluk', 'emotions', 'beginner', 'en', 'He felt guilt after the argument.', 'Tartışmadan sonra suçluluk hissetti.'),
  ('jealous', 'kıskanç', 'emotions', 'beginner', 'en', 'She felt jealous of their success.', 'Başarılarına kıskançlık duydu.');
