INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('catharsis', 'arınma', 'emotions', 'advanced', 'en', 'Writing offered a sense of catharsis.', 'Yazmak bir arınma hissi sundu.'),
  ('ambivalence', 'belirsizlik', 'emotions', 'advanced', 'en', 'She felt ambivalence about moving abroad.', 'Yurt dışına taşınma konusunda belirsizlik hissetti.'),
  ('euphoria', 'öfori', 'emotions', 'advanced', 'en', 'Victory brought a wave of euphoria.', 'Zafer bir öfori dalgası getirdi.'),
  ('despair', 'çaresizlik', 'emotions', 'advanced', 'en', 'Support pulled him out of despair.', 'Destek onu çaresizlikten çıkardı.'),
  ('existential dread', 'varoluşsal korku', 'emotions', 'advanced', 'en', 'Late nights sometimes trigger existential dread.', 'Geç saatler bazen varoluşsal korkuyu tetikler.'),
  ('cognitive dissonance', 'bilişsel çelişki', 'emotions', 'advanced', 'en', 'Cognitive dissonance follows conflicting beliefs.', 'Bilişsel çelişki çatışan inançları takip eder.'),
  ('emotional regulation', 'duygusal düzenleme', 'emotions', 'advanced', 'en', 'Therapy teaches emotional regulation skills.', 'Terapi duygusal düzenleme becerileri öğretir.'),
  ('alexithymia', 'alexithymia', 'emotions', 'advanced', 'en', 'Alexithymia makes feelings hard to name.', 'Alexithymia duyguları adlandırmayı zorlaştırır.'),
  ('rumination', 'sürekli düşünme', 'emotions', 'advanced', 'en', 'Rumination deepens anxiety over time.', 'Sürekli düşünme zamanla kaygıyı derinleştirir.'),
  ('affective empathy', 'duygusal empati', 'emotions', 'advanced', 'en', 'Affective empathy mirrors others'' pain.', 'Duygusal empati başkalarının acısını yansıtır.'),
  ('cognitive empathy', 'bilişsel empati', 'emotions', 'advanced', 'en', 'Cognitive empathy understands another perspective.', 'Bilişsel empati başka bir bakış açısını anlar.'),
  ('emotional labor', 'duygusal emek', 'emotions', 'advanced', 'en', 'Customer service involves heavy emotional labor.', 'Müşteri hizmetleri yoğun duygusal emek içerir.'),
  ('gaslighting', 'gaslighting', 'emotions', 'advanced', 'en', 'Gaslighting makes victims doubt reality.', 'Gaslighting kurbanların gerçeği sorgulamasına neden olur.'),
  ('trauma response', 'travma tepkisi', 'emotions', 'advanced', 'en', 'A loud bang triggered a trauma response.', 'Yüksek bir patlama travma tepkisini tetikledi.'),
  ('hypervigilance', 'aşırı tetikte olma', 'emotions', 'advanced', 'en', 'Hypervigilance exhausts the nervous system.', 'Aşırı tetikte olma sinir sistemini yorar.'),
  ('emotional numbness', 'duygusal uyuşukluk', 'emotions', 'advanced', 'en', 'Burnout can cause emotional numbness.', 'Tükenmişlik duygusal uyuşukluğa neden olabilir.'),
  ('schadenfreude', 'schadenfreude', 'emotions', 'advanced', 'en', 'Schadenfreude is pleasure in others'' misfortune.', 'Schadenfreude başkalarının talihsizliğinden zevk almaktır.'),
  ('sublimation', 'sublimasyon', 'emotions', 'advanced', 'en', 'Art can channel anger through sublimation.', 'Sanat öfkeyi sublimasyon yoluyla yönlendirebilir.'),
  ('projection', 'yansıtma', 'emotions', 'advanced', 'en', 'Projection blames others for inner feelings.', 'Yansıtma iç duyguları başkalarına yükler.'),
  ('emotional resilience', 'duygusal dayanıklılık', 'emotions', 'advanced', 'en', 'Emotional resilience grows with practice.', 'Duygusal dayanıklılık pratikle gelişir.'),
  ('liminal emotion', 'eşik duygusu', 'emotions', 'advanced', 'en', 'Graduation brings a liminal emotion of change.', 'Mezuniyet değişimin eşik duygusunu getirir.'),
  ('bittersweet', 'acı-tatlı', 'emotions', 'advanced', 'en', 'Farewells often feel bittersweet.', 'Vedalar genelde acı-tatlı hissettirir.'),
  ('emotional contagion', 'duygusal bulaşma', 'emotions', 'advanced', 'en', 'Laughter spreads through emotional contagion.', 'Kahkaha duygusal bulaşmayla yayılır.'),
  ('affect regulation', 'duygu düzenleme', 'emotions', 'advanced', 'en', 'Children learn affect regulation from caregivers.', 'Çocuklar duygu düzenlemeyi bakıcılardan öğrenir.'),
  ('moral outrage', 'ahlaki öfke', 'emotions', 'advanced', 'en', 'Injustice sparked moral outrage online.', 'Adaletsizlik çevrimiçi ahlaki öfke yarattı.'),
  ('compassion fatigue', 'merhamet yorgunluğu', 'emotions', 'advanced', 'en', 'Nurses risk compassion fatigue.', 'Hemşireler merhamet yorgunluğu riski taşır.'),
  ('emotional granularity', 'duygusal ayrıntılılık', 'emotions', 'advanced', 'en', 'Emotional granularity improves self-awareness.', 'Duygusal ayrıntılılık öz farkındalığı artırır.'),
  ('post-traumatic growth', 'travma sonrası büyüme', 'emotions', 'advanced', 'en', 'Some report post-traumatic growth after hardship.', 'Bazıları zorluktan sonra travma sonrası büyüme bildirir.'),
  ('emotional validation', 'duygusal onaylama', 'emotions', 'advanced', 'en', 'Emotional validation calms heated talks.', 'Duygusal onaylama hararetli konuşmaları sakinleştirir.'),
  ('dysthymia', 'distimi', 'emotions', 'advanced', 'en', 'Dysthymia involves chronic low mood.', 'Distimi kronik düşük ruh hali içerir.'),
  ('school', 'okul', 'education', 'beginner', 'en', 'School starts at eight o''clock.', 'Okul saat sekizde başlar.'),
  ('teacher', 'öğretmen', 'education', 'beginner', 'en', 'Our teacher explains lessons clearly.', 'Öğretmenimiz dersleri net anlatıyor.'),
  ('student', 'öğrenci', 'education', 'beginner', 'en', 'Every student needs a notebook.', 'Her öğrencinin bir deftere ihtiyacı var.'),
  ('class', 'sınıf', 'education', 'beginner', 'en', 'The class meets in room twelve.', 'Sınıf on iki numaralı odada buluşuyor.'),
  ('book', 'kitap', 'education', 'beginner', 'en', 'Read the book before the test.', 'Sınavdan önce kitabı oku.'),
  ('pen', 'kalem', 'education', 'beginner', 'en', 'Borrow a pen if you forgot yours.', 'Kalemini unuttuysan bir kalem ödünç al.'),
  ('pencil', 'kurşun kalem', 'education', 'beginner', 'en', 'Use a pencil for the diagram.', 'Şema için kurşun kalem kullan.'),
  ('homework', 'ev ödevi', 'education', 'beginner', 'en', 'Finish your homework before dinner.', 'Akşam yemeğinden önce ev ödevini bitir.'),
  ('exam', 'sınav', 'education', 'beginner', 'en', 'The math exam is on Friday.', 'Matematik sınavı cuma.'),
  ('grade', 'not', 'education', 'beginner', 'en', 'She earned a high grade.', 'Yüksek bir not aldı.');
