INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('immune system', 'bağışıklık sistemi', 'health', 'intermediate', 'en', 'Sleep supports the immune system.', 'Uyku bağışıklık sistemini destekler.'),
  ('inflammation', 'iltihap', 'health', 'intermediate', 'en', 'Ice reduces inflammation in joints.', 'Buz eklemlerdeki iltihabı azaltır.'),
  ('chronic pain', 'kronik ağrı', 'health', 'intermediate', 'en', 'Chronic pain affects daily life.', 'Kronik ağrı günlük yaşamı etkiler.'),
  ('mental health', 'ruh sağlığı', 'health', 'intermediate', 'en', 'Mental health matters as much as physical health.', 'Ruh sağlığı fiziksel sağlık kadar önemlidir.'),
  ('anxiety', 'kaygı', 'health', 'intermediate', 'en', 'Talk therapy helps with anxiety.', 'Konuşma terapisi kaygıya yardım eder.'),
  ('depression', 'depresyon', 'health', 'intermediate', 'en', 'Depression is treatable with support.', 'Depresyon destekle tedavi edilebilir.'),
  ('insomnia', 'uykusuzluk', 'health', 'intermediate', 'en', 'Insomnia often follows high stress.', 'Uykusuzluk genelde yüksek stresi takip eder.'),
  ('nutrition', 'beslenme', 'health', 'intermediate', 'en', 'Good nutrition prevents many diseases.', 'İyi beslenme birçok hastalığı önler.'),
  ('calorie', 'kalori', 'health', 'intermediate', 'en', 'Track calories to manage weight.', 'Kilo yönetimi için kalorileri takip et.'),
  ('protein', 'protein', 'health', 'intermediate', 'en', 'Protein repairs muscle after workouts.', 'Protein antrenman sonrası kası onarır.'),
  ('vitamin', 'vitamin', 'health', 'intermediate', 'en', 'Vitamin D comes from sunlight.', 'D vitamini güneş ışığından gelir.'),
  ('mineral', 'mineral', 'health', 'intermediate', 'en', 'Iron is an essential mineral.', 'Demir temel bir mineraldir.'),
  ('hydration', 'hidrasyon', 'health', 'intermediate', 'en', 'Proper hydration aids kidney function.', 'Doğru hidrasyon böbrek işlevine yardım eder.'),
  ('posture', 'duruş', 'health', 'intermediate', 'en', 'Poor posture causes back pain.', 'Kötü duruş sırt ağrısına neden olur.'),
  ('first aid', 'ilk yardım', 'health', 'intermediate', 'en', 'Learn first aid for emergencies.', 'Acil durumlar için ilk yardım öğren.'),
  ('CPR', 'CPR', 'health', 'intermediate', 'en', 'CPR can save a life before help arrives.', 'CPR yardım gelmeden önce hayat kurtarabilir.'),
  ('rehabilitation', 'rehabilitasyon', 'health', 'intermediate', 'en', 'Rehabilitation follows major surgery.', 'Rehabilitasyon büyük ameliyatı takip eder.'),
  ('screening', 'tarama', 'health', 'intermediate', 'en', 'Cancer screening detects problems early.', 'Kanser taraması sorunları erken tespit eder.'),
  ('preventive care', 'koruyucu bakım', 'health', 'intermediate', 'en', 'Preventive care lowers long-term costs.', 'Koruyucu bakım uzun vadeli maliyetleri düşürür.'),
  ('telemedicine', 'telemedicine', 'health', 'intermediate', 'en', 'Telemedicine offers remote consultations.', 'Telemedicine uzaktan konsültasyon sunar.'),
  ('comorbidity', 'eş hastalık', 'health', 'advanced', 'en', 'Comorbidity complicates treatment plans.', 'Eş hastalık tedavi planlarını karmaşıklaştırır.'),
  ('prognosis', 'prognoz', 'health', 'advanced', 'en', 'The prognosis improved after therapy.', 'Prognoz tedaviden sonra iyileşti.'),
  ('pathology', 'patoloji', 'health', 'advanced', 'en', 'Pathology confirmed the diagnosis.', 'Patoloji tanıyı doğruladı.'),
  ('biomarker', 'biyobelirteç', 'health', 'advanced', 'en', 'Biomarkers guide personalized medicine.', 'Biyobelirteçler kişiselleştirilmiş tıbbı yönlendirir.'),
  ('placebo effect', 'plasebo etkisi', 'health', 'advanced', 'en', 'The placebo effect can reduce reported pain.', 'Plasebo etkisi bildirilen ağrıyı azaltabilir.'),
  ('antibody', 'antikor', 'health', 'advanced', 'en', 'Antibodies fight foreign invaders.', 'Antikorlar yabancı istilacılarla savaşır.'),
  ('autoimmune', 'otoimmün', 'health', 'advanced', 'en', 'Autoimmune diseases attack healthy tissue.', 'Otoimmün hastalıklar sağlıklı dokuya saldırır.'),
  ('metabolism', 'metabolizma', 'health', 'advanced', 'en', 'Metabolism slows with age for many people.', 'Birçok kişide metabolizma yaşla yavaşlar.'),
  ('homeostasis', 'homeostaz', 'health', 'advanced', 'en', 'The body maintains homeostasis through feedback.', 'Vücut geri bildirimle homeostazı korur.'),
  ('epidemiology', 'epidemiyoloji', 'health', 'advanced', 'en', 'Epidemiology tracks disease spread patterns.', 'Epidemiyoloji hastalık yayılım kalıplarını izler.'),
  ('palliative care', 'palyatif bakım', 'health', 'advanced', 'en', 'Palliative care focuses on comfort.', 'Palyatif bakım konfora odaklanır.'),
  ('informed consent', 'bilgilendirilmiş onam', 'health', 'advanced', 'en', 'Surgery requires informed consent.', 'Ameliyat bilgilendirilmiş onam gerektirir.'),
  ('clinical trial', 'klinik deneme', 'health', 'advanced', 'en', 'New drugs pass through clinical trials.', 'Yeni ilaçlar klinik denemelerden geçer.'),
  ('antimicrobial resistance', 'antimikrobiyal direnç', 'health', 'advanced', 'en', 'Antimicrobial resistance threatens global health.', 'Antimikrobiyal direnç küresel sağlığı tehdit eder.'),
  ('public health', 'halk sağlığı', 'health', 'advanced', 'en', 'Public health campaigns promote vaccination.', 'Halk sağlığı kampanyaları aşılamayı teşvik eder.'),
  ('health literacy', 'sağlık okuryazarlığı', 'health', 'advanced', 'en', 'Health literacy improves treatment adherence.', 'Sağlık okuryazarlığı tedaviye uyumu artırır.'),
  ('psychosomatic', 'psikosomatik', 'health', 'advanced', 'en', 'Stress can trigger psychosomatic symptoms.', 'Stres psikosomatik belirtileri tetikleyebilir.'),
  ('neuroplasticity', 'nöroplastisite', 'health', 'advanced', 'en', 'Neuroplasticity allows the brain to adapt.', 'Nöroplastisite beynin uyum sağlamasına izin verir.'),
  ('gut microbiome', 'bağırsak mikrobiyomu', 'health', 'advanced', 'en', 'The gut microbiome affects immunity.', 'Bağırsak mikrobiyomu bağışıklığı etkiler.'),
  ('telehealth parity', 'tele sağlık eşitliği', 'health', 'advanced', 'en', 'Telehealth parity expands rural access.', 'Tele sağlık eşitliği kırsal erişimi genişletir.');
