INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('lesson', 'ders', 'education', 'beginner', 'en', 'Today''s lesson covers verbs.', 'Bugünkü ders fiilleri kapsıyor.'),
  ('desk', 'sıra', 'education', 'beginner', 'en', 'Keep your desk tidy.', 'Sıranı düzenli tut.'),
  ('board', 'tahta', 'education', 'beginner', 'en', 'The teacher wrote on the board.', 'Öğretmen tahtaya yazdı.'),
  ('library', 'kütüphane', 'education', 'beginner', 'en', 'Study quietly in the library.', 'Kütüphanede sessizce çalış.'),
  ('subject', 'ders', 'education', 'beginner', 'en', 'Math is my favorite subject.', 'Matematik en sevdiğim ders.'),
  ('question', 'soru', 'education', 'beginner', 'en', 'Raise your hand to ask a question.', 'Soru sormak için elini kaldır.'),
  ('answer', 'cevap', 'education', 'beginner', 'en', 'Write the answer in full sentences.', 'Cevabı tam cümlelerle yaz.'),
  ('study', 'çalışmak', 'education', 'beginner', 'en', 'Study a little every day.', 'Her gün biraz çalış.'),
  ('learn', 'öğrenmek', 'education', 'beginner', 'en', 'Children learn languages quickly.', 'Çocuklar dilleri hızlı öğrenir.'),
  ('read', 'okumak', 'education', 'beginner', 'en', 'Read the instructions carefully.', 'Talimatları dikkatlice oku.'),
  ('write', 'yazmak', 'education', 'beginner', 'en', 'Write your name at the top.', 'Adını en üste yaz.'),
  ('spell', 'hecelemek', 'education', 'beginner', 'en', 'Can you spell your surname?', 'Soyadını heceleyebilir misin?'),
  ('dictionary', 'sözlük', 'education', 'beginner', 'en', 'Use a dictionary for new words.', 'Yeni kelimeler için sözlük kullan.'),
  ('notebook', 'defter', 'education', 'beginner', 'en', 'Copy notes into your notebook.', 'Notları defterine kopyala.'),
  ('break', 'teneffüs', 'education', 'beginner', 'en', 'We play outside during break.', 'Teneffüste dışarıda oynuyoruz.'),
  ('uniform', 'üniforma', 'education', 'beginner', 'en', 'Students wear a blue uniform.', 'Öğrenciler mavi üniforma giyer.'),
  ('principal', 'müdür', 'education', 'beginner', 'en', 'The principal spoke at assembly.', 'Müdür toplantıda konuştu.'),
  ('classmate', 'sınıf arkadaşı', 'education', 'beginner', 'en', 'My classmate shared her notes.', 'Sınıf arkadaşım notlarını paylaştı.'),
  ('schedule', 'program', 'education', 'beginner', 'en', 'Check the schedule for room changes.', 'Oda değişiklikleri için programı kontrol et.'),
  ('quiz', 'kısa sınav', 'education', 'beginner', 'en', 'We have a short quiz tomorrow.', 'Yarın kısa bir sınavımız var.'),
  ('curriculum', 'müfredat', 'education', 'intermediate', 'en', 'The curriculum includes coding basics.', 'Müfredat kodlama temellerini içeriyor.'),
  ('syllabus', 'ders programı', 'education', 'intermediate', 'en', 'The syllabus lists all assignments.', 'Ders programı tüm ödevleri listeler.'),
  ('lecture', 'ders', 'education', 'intermediate', 'en', 'The lecture lasted ninety minutes.', 'Ders doksan dakika sürdü.'),
  ('seminar', 'seminer', 'education', 'intermediate', 'en', 'Students discuss texts in the seminar.', 'Öğrenciler seminerde metinleri tartışır.'),
  ('thesis', 'tez', 'education', 'intermediate', 'en', 'She is writing her master''s thesis.', 'Yüksek lisans tezini yazıyor.'),
  ('research', 'araştırma', 'education', 'intermediate', 'en', 'Research requires reliable sources.', 'Araştırma güvenilir kaynaklar gerektirir.'),
  ('citation', 'atıf', 'education', 'intermediate', 'en', 'Include a citation for each quote.', 'Her alıntı için atıf ekle.'),
  ('plagiarism', 'intihal', 'education', 'intermediate', 'en', 'Plagiarism leads to serious penalties.', 'İntihal ciddi cezalara yol açar.'),
  ('scholarship', 'burs', 'education', 'intermediate', 'en', 'He won a scholarship for excellence.', 'Başarı için burs kazandı.'),
  ('tuition', 'öğrenim ücreti', 'education', 'intermediate', 'en', 'Tuition fees rise each year.', 'Öğrenim ücretleri her yıl artıyor.'),
  ('enrollment', 'kayıt', 'education', 'intermediate', 'en', 'Enrollment closes at the end of August.', 'Kayıt ağustos sonunda kapanır.'),
  ('attendance', 'devam', 'education', 'intermediate', 'en', 'Attendance affects your final grade.', 'Devam final notunu etkiler.'),
  ('deadline', 'son teslim tarihi', 'education', 'intermediate', 'en', 'Submit essays before the deadline.', 'Denemeleri son teslim tarihinden önce gönder.'),
  ('peer review', 'akran değerlendirmesi', 'education', 'intermediate', 'en', 'Peer review improves draft quality.', 'Akran değerlendirmesi taslak kalitesini artırır.'),
  ('rubric', 'değerlendirme ölçütü', 'education', 'intermediate', 'en', 'Check the rubric before submitting.', 'Göndermeden önce değerlendirme ölçütünü kontrol et.'),
  ('extracurricular', 'ders dışı', 'education', 'intermediate', 'en', 'Extracurricular clubs meet after school.', 'Ders dışı kulüpler okul sonrası buluşur.'),
  ('literacy', 'okuryazarlık', 'education', 'intermediate', 'en', 'Early literacy programs help young kids.', 'Erken okuryazarlık programları küçük çocuklara yardım eder.'),
  ('numeracy', 'sayısal okuryazarlık', 'education', 'intermediate', 'en', 'Numeracy skills support daily budgeting.', 'Sayısal okuryazarlık günlük bütçelemeyi destekler.'),
  ('STEM', 'STEM', 'education', 'intermediate', 'en', 'STEM fields need creative problem solvers.', 'STEM alanları yaratıcı problem çözücülere ihtiyaç duyar.'),
  ('humanities', 'beşeri bilimler', 'education', 'intermediate', 'en', 'Humanities explore culture and history.', 'Beşeri bilimler kültür ve tarihi inceler.');
