INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('doctor', 'doktor', 'health', 'beginner', 'en', 'See a doctor if fever lasts.', 'Ateş sürerse doktora git.'),
  ('hospital', 'hastane', 'health', 'beginner', 'en', 'The hospital is near the park.', 'Hastane parkın yakınında.'),
  ('medicine', 'ilaç', 'health', 'beginner', 'en', 'Take your medicine after meals.', 'İlacını yemeklerden sonra al.'),
  ('pain', 'ağrı', 'health', 'beginner', 'en', 'She felt pain in her knee.', 'Dizinde ağrı hissetti.'),
  ('fever', 'ateş', 'health', 'beginner', 'en', 'A high fever needs rest.', 'Yüksek ateş dinlenme gerektirir.'),
  ('headache', 'baş ağrısı', 'health', 'beginner', 'en', 'Stress can cause a headache.', 'Stres baş ağrısına neden olabilir.'),
  ('cough', 'öksürük', 'health', 'beginner', 'en', 'Drink warm tea for a cough.', 'Öksürük için sıcak çay iç.'),
  ('cold', 'soğuk algınlığı', 'health', 'beginner', 'en', 'I caught a cold last week.', 'Geçen hafta soğuk algınlığına yakalandım.'),
  ('flu', 'grip', 'health', 'beginner', 'en', 'Flu spreads quickly in winter.', 'Grip kışın hızla yayılır.'),
  ('injury', 'yaralanma', 'health', 'beginner', 'en', 'Rest the injury for two days.', 'Yaralanmayı iki gün dinlendir.'),
  ('bandage', 'bandaj', 'health', 'beginner', 'en', 'Wrap a bandage around the cut.', 'Kesik etrafına bandaj sar.'),
  ('blood', 'kan', 'health', 'beginner', 'en', 'The nurse took a blood sample.', 'Hemşire kan örneği aldı.'),
  ('heart', 'kalp', 'health', 'beginner', 'en', 'Exercise keeps the heart healthy.', 'Egzersiz kalbi sağlıklı tutar.'),
  ('lung', 'akciğer', 'health', 'beginner', 'en', 'Smoking harms the lungs.', 'Sigara akciğerlere zarar verir.'),
  ('bone', 'kemik', 'health', 'beginner', 'en', 'Calcium strengthens bones.', 'Kalsiyum kemikleri güçlendirir.'),
  ('muscle', 'kas', 'health', 'beginner', 'en', 'Stretch to relax sore muscles.', 'Ağrıyan kasları gevşetmek için esne.'),
  ('skin', 'cilt', 'health', 'beginner', 'en', 'Use sunscreen to protect skin.', 'Cildi korumak için güneş kremi kullan.'),
  ('tooth', 'diş', 'health', 'beginner', 'en', 'Brush each tooth carefully.', 'Her dişi dikkatlice fırçala.'),
  ('sleep', 'uyku', 'health', 'beginner', 'en', 'Good sleep improves mood.', 'İyi uyku ruh halini iyileştirir.'),
  ('exercise', 'egzersiz', 'health', 'beginner', 'en', 'Daily exercise boosts energy.', 'Günlük egzersiz enerjiyi artırır.'),
  ('diet', 'diyet', 'health', 'beginner', 'en', 'A balanced diet supports health.', 'Dengeli diyet sağlığı destekler.'),
  ('weight', 'kilo', 'health', 'beginner', 'en', 'Track your weight weekly.', 'Kilonu haftalık takip et.'),
  ('stress', 'stres', 'health', 'beginner', 'en', 'Deep breathing reduces stress.', 'Derin nefes stresi azaltır.'),
  ('allergy', 'alerji', 'health', 'beginner', 'en', 'Pollen allergy peaks in spring.', 'Polen alerjisi ilkbaharda zirve yapar.'),
  ('vaccine', 'aşı', 'health', 'beginner', 'en', 'Children receive routine vaccines.', 'Çocuklar rutin aşıları alır.'),
  ('pharmacy', 'eczane', 'health', 'beginner', 'en', 'The pharmacy opens at eight.', 'Eczane sekizde açılıyor.'),
  ('appointment', 'randevu', 'health', 'beginner', 'en', 'Book a doctor appointment online.', 'Çevrimiçi doktor randevusu al.'),
  ('symptom', 'belirti', 'health', 'beginner', 'en', 'List every symptom for the doctor.', 'Doktor için her belirtiyi listele.'),
  ('healthy', 'sağlıklı', 'health', 'beginner', 'en', 'Eat healthy food every day.', 'Her gün sağlıklı yemek ye.'),
  ('sick', 'hasta', 'health', 'beginner', 'en', 'He stayed home because he was sick.', 'Hasta olduğu için evde kaldı.'),
  ('blood pressure', 'tansiyon', 'health', 'intermediate', 'en', 'High blood pressure needs monitoring.', 'Yüksek tansiyon takip gerektirir.'),
  ('cholesterol', 'kolesterol', 'health', 'intermediate', 'en', 'Diet affects cholesterol levels.', 'Diyet kolesterol seviyelerini etkiler.'),
  ('diabetes', 'diyabet', 'health', 'intermediate', 'en', 'Diabetes requires regular checkups.', 'Diyabet düzenli kontroller gerektirir.'),
  ('insulin', 'insülin', 'health', 'intermediate', 'en', 'Insulin helps control blood sugar.', 'İnsülin kan şekerini kontrol etmeye yardım eder.'),
  ('prescription', 'reçete', 'health', 'intermediate', 'en', 'The doctor wrote a prescription.', 'Doktor reçete yazdı.'),
  ('antibiotic', 'antibiyotik', 'health', 'intermediate', 'en', 'Finish the full antibiotic course.', 'Antibiyotik kürünü tamamla.'),
  ('side effect', 'yan etki', 'health', 'intermediate', 'en', 'Drowsiness is a common side effect.', 'Uyuşukluk yaygın bir yan etkidir.'),
  ('physical therapy', 'fizik tedavi', 'health', 'intermediate', 'en', 'Physical therapy restored her mobility.', 'Fizik tedavi hareketliliğini geri kazandırdı.'),
  ('X-ray', 'röntgen', 'health', 'intermediate', 'en', 'An X-ray showed a small fracture.', 'Röntgen küçük bir kırığı gösterdi.'),
  ('MRI scan', 'MR taraması', 'health', 'intermediate', 'en', 'The MRI scan took forty minutes.', 'MR taraması kırk dakika sürdü.');
