INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('wine', 'şarap', 'drinks', 'beginner', 'en', 'Red wine pairs well with steak.', 'Kırmızı şarap biftekle iyi gider.'),
  ('cocktail', 'kokteyl', 'drinks', 'beginner', 'en', 'They mixed a simple cocktail.', 'Basit bir kokteyl karıştırdılar.'),
  ('mineral water', 'maden suyu', 'drinks', 'beginner', 'en', 'Mineral water bubbles on the tongue.', 'Maden suyu dilde köpürür.'),
  ('sparkling water', 'maden suyu', 'drinks', 'beginner', 'en', 'Sparkling water replaces soda for her.', 'Maden suyu onun için gazlı içeceğin yerini alıyor.'),
  ('herbal tea', 'bitki çayı', 'drinks', 'beginner', 'en', 'Herbal tea helps me relax.', 'Bitki çayı rahatlamama yardım eder.'),
  ('espresso', 'espresso', 'drinks', 'beginner', 'en', 'Espresso gives a quick caffeine boost.', 'Espresso hızlı bir kafein desteği verir.'),
  ('latte', 'latte', 'drinks', 'beginner', 'en', 'She ordered a vanilla latte.', 'Vanilyalı latte sipariş etti.'),
  ('cappuccino', 'kapuçino', 'drinks', 'beginner', 'en', 'Cappuccino has thick foam on top.', 'Kapuçinonun üstünde kalın köpük vardır.'),
  ('iced tea', 'soğuk çay', 'drinks', 'beginner', 'en', 'Iced tea is perfect in summer.', 'Soğuk çay yazın mükemmeldir.'),
  ('milkshake', 'milkshake', 'drinks', 'beginner', 'en', 'The chocolate milkshake was creamy.', 'Çikolatalı milkshake kremalıydı.'),
  ('energy drink', 'enerji içeceği', 'drinks', 'beginner', 'en', 'Energy drinks contain high caffeine.', 'Enerji içecekleri yüksek kafein içerir.'),
  ('cider', 'elma şarabı', 'drinks', 'beginner', 'en', 'Apple cider tastes sweet and crisp.', 'Elma şarabı tatlı ve ferah tadılır.'),
  ('whiskey', 'viski', 'drinks', 'beginner', 'en', 'Whiskey is often served with ice.', 'Viski genelde buzla servis edilir.'),
  ('vodka', 'votka', 'drinks', 'beginner', 'en', 'Vodka mixes well in cocktails.', 'Votka kokteyllerde iyi karışır.'),
  ('rum', 'rom', 'drinks', 'beginner', 'en', 'Rum adds sweetness to tropical drinks.', 'Rom tropikal içeceklere tatlılık katar.'),
  ('syrup', 'şurup', 'drinks', 'beginner', 'en', 'Add syrup to sweeten the drink.', 'İçeceği tatlandırmak için şurup ekle.'),
  ('ice cube', 'buz küpü', 'drinks', 'beginner', 'en', 'Drop an ice cube into the glass.', 'Bardağa bir buz küpü at.'),
  ('straw', 'pipet', 'drinks', 'beginner', 'en', 'Paper straws are better for the environment.', 'Kağıt pipetler çevre için daha iyidir.'),
  ('cup', 'fincan', 'drinks', 'beginner', 'en', 'Fill the cup halfway with tea.', 'Fincanı yarıya kadar çayla doldur.'),
  ('bottle', 'şişe', 'drinks', 'beginner', 'en', 'Recycle the glass bottle.', 'Cam şişeyi geri dönüştür.'),
  ('brew', 'demlemek', 'drinks', 'intermediate', 'en', 'Brew the tea for five minutes.', 'Çayı beş dakika demle.'),
  ('steep', 'demlenmek', 'drinks', 'intermediate', 'en', 'Let the leaves steep in hot water.', 'Yaprakların sıcak suda demlenmesine izin ver.'),
  ('ferment', 'fermente etmek', 'drinks', 'intermediate', 'en', 'They ferment grapes to make wine.', 'Şarap yapmak için üzümleri fermente ederler.'),
  ('distill', 'damıtmak', 'drinks', 'intermediate', 'en', 'Distill spirits in copper stills.', 'İçkileri bakır imbiklerde damıt.'),
  ('carbonated', 'karbondioksitli', 'drinks', 'intermediate', 'en', 'Carbonated drinks feel fizzy.', 'Karbondioksitli içecekler köpüklü hissettirir.'),
  ('decaf', 'kafeinsiz', 'drinks', 'intermediate', 'en', 'She prefers decaf coffee at night.', 'Gece kafeinsiz kahveyi tercih eder.'),
  ('bitters', 'bitter', 'drinks', 'intermediate', 'en', 'A few drops of bitters change the flavor.', 'Birkaç damla bitter tadı değiştirir.'),
  ('garnish', 'süsleme', 'drinks', 'intermediate', 'en', 'Add lemon as a garnish.', 'Süsleme olarak limon ekle.'),
  ('infusion', 'infüzyon', 'drinks', 'intermediate', 'en', 'Mint infusion is calming.', 'Nane infüzyonu sakinleştiricidir.'),
  ('mocktail', 'alkolsüz kokteyl', 'drinks', 'intermediate', 'en', 'The mocktail looks like a real cocktail.', 'Alkolsüz kokteyl gerçek kokteyl gibi görünüyor.'),
  ('single origin', 'tek köken', 'drinks', 'intermediate', 'en', 'Single origin coffee highlights regional taste.', 'Tek köken kahve bölgesel tadı öne çıkarır.'),
  ('cold brew', 'soğuk demleme', 'drinks', 'intermediate', 'en', 'Cold brew takes hours to prepare.', 'Soğuk demleme hazırlanması saatler sürer.'),
  ('tonic water', 'tonik', 'drinks', 'intermediate', 'en', 'Tonic water pairs with gin.', 'Tonik cin ile iyi gider.'),
  ('sake', 'sake', 'drinks', 'intermediate', 'en', 'Sake is served warm or chilled.', 'Sake sıcak veya soğuk servis edilir.'),
  ('matcha', 'matcha', 'drinks', 'intermediate', 'en', 'Matcha powder whisked into hot water.', 'Matcha tozu sıcak suya çırpılır.'),
  ('rooibos', 'rooibos', 'drinks', 'intermediate', 'en', 'Rooibos is naturally caffeine-free.', 'Rooibos doğal olarak kafeinsizdir.'),
  ('kombucha', 'kombucha', 'drinks', 'intermediate', 'en', 'Kombucha has a tangy fermented taste.', 'Kombuchanın ekşi fermente bir tadı vardır.'),
  ('prosecco', 'prosecco', 'drinks', 'intermediate', 'en', 'They toasted with prosecco.', 'Prosecco ile kadeh kaldırdılar.'),
  ('champagne', 'şampanya', 'drinks', 'intermediate', 'en', 'Champagne popped at midnight.', 'Gece yarısı şampanya patladı.'),
  ('ale', 'ale', 'drinks', 'intermediate', 'en', 'Dark ale has a rich malt flavor.', 'Koyu ale zengin malt aromasına sahiptir.');
