INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('denim', 'denim', 'clothes', 'intermediate', 'en', 'Denim fades with frequent washing.', 'Denim sık yıkamayla soluyor.'),
  ('leather', 'deri', 'clothes', 'intermediate', 'en', 'Leather boots need regular care.', 'Deri botlar düzenli bakım gerektirir.'),
  ('waterproof', 'su geçirmez', 'clothes', 'intermediate', 'en', 'Buy a waterproof jacket for hiking.', 'Yürüyüş için su geçirmez ceket al.'),
  ('breathable', 'nefes alabilir', 'clothes', 'intermediate', 'en', 'Breathable fabrics reduce sweat.', 'Nefes alabilir kumaşlar terlemeyi azaltır.'),
  ('layering', 'katmanlama', 'clothes', 'intermediate', 'en', 'Layering works well in changing weather.', 'Katmanlama değişken havada iyi işler.'),
  ('business casual', 'iş günlük', 'clothes', 'intermediate', 'en', 'Business casual allows neat chinos.', 'İş günlük düzenli chino pantolonlara izin verir.'),
  ('formal wear', 'resmi kıyafet', 'clothes', 'intermediate', 'en', 'Formal wear is required at the gala.', 'Galada resmi kıyafet gereklidir.'),
  ('sportswear', 'spor giyim', 'clothes', 'intermediate', 'en', 'Sportswear dries quickly after workouts.', 'Spor giyim antrenman sonrası hızla kurur.'),
  ('fast fashion', 'hızlı moda', 'clothes', 'intermediate', 'en', 'Fast fashion creates textile waste.', 'Hızlı moda tekstil atığı oluşturur.'),
  ('sustainable fashion', 'sürdürülebilir moda', 'clothes', 'intermediate', 'en', 'Sustainable fashion uses ethical materials.', 'Sürdürülebilir moda etik malzemeler kullanır.'),
  ('secondhand', 'ikinci el', 'clothes', 'intermediate', 'en', 'Secondhand shops offer unique finds.', 'İkinci el dükkanlar benzersiz parçalar sunar.'),
  ('dry clean', 'kuru temizleme', 'clothes', 'intermediate', 'en', 'Dry clean the wool coat only.', 'Yün paltoyu sadece kuru temizle.'),
  ('stain', 'leke', 'clothes', 'intermediate', 'en', 'Treat the stain before it sets.', 'Leke oturmadan müdahale et.'),
  ('bleach', 'ağartıcı', 'clothes', 'intermediate', 'en', 'Do not bleach colored clothes.', 'Renkli kıyafetleri ağartma.'),
  ('detergent', 'deterjan', 'clothes', 'intermediate', 'en', 'Use mild detergent for delicates.', 'Hassas kumaşlar için hafif deterjan kullan.'),
  ('lint roller', 'tüy alıcı rulo', 'clothes', 'intermediate', 'en', 'A lint roller removes pet hair.', 'Tüy alıcı rulo evcil hayvan tüyünü temizler.'),
  ('measurement', 'ölçü', 'clothes', 'intermediate', 'en', 'Take accurate measurements before ordering.', 'Sipariş vermeden önce doğru ölçü al.'),
  ('unisex', 'unisex', 'clothes', 'intermediate', 'en', 'The brand released a unisex collection.', 'Marka unisex bir koleksiyon çıkardı.'),
  ('oversized', 'oversize', 'clothes', 'intermediate', 'en', 'Oversized hoodies feel cozy.', 'Oversize kapüşonlular rahat hissettirir.'),
  ('slim fit', 'slim fit', 'clothes', 'intermediate', 'en', 'Slim fit pants taper at the ankle.', 'Slim fit pantolon bilekte daralır.'),
  ('haute couture', 'haute couture', 'clothes', 'advanced', 'en', 'Haute couture pieces are made to order.', 'Haute couture parçalar sipariş üzerine yapılır.'),
  ('prêt-à-porter', 'hazır giyim', 'clothes', 'advanced', 'en', 'Prêt-à-porter lines reach wider markets.', 'Hazır giyim koleksiyonları daha geniş pazarlara ulaşır.'),
  ('capsule wardrobe', 'kapsül gardırop', 'clothes', 'advanced', 'en', 'A capsule wardrobe reduces daily choices.', 'Kapsül gardırop günlük seçimleri azaltır.'),
  ('textile engineering', 'tekstil mühendisliği', 'clothes', 'advanced', 'en', 'Textile engineering improves fabric durability.', 'Tekstil mühendisliği kumaş dayanıklılığını artırır.'),
  ('garment construction', 'giysi yapımı', 'clothes', 'advanced', 'en', 'Garment construction affects longevity.', 'Giysi yapımı ömrü etkiler.'),
  ('draping', 'drapaj', 'clothes', 'advanced', 'en', 'Designers use draping on mannequins.', 'Tasarımcılar mankenlerde drapaj kullanır.'),
  ('pattern grading', 'kalıp derecelendirme', 'clothes', 'advanced', 'en', 'Pattern grading scales sizes accurately.', 'Kalıp derecelendirme bedenleri doğru ölçekler.'),
  ('bias cut', 'çapraz kesim', 'clothes', 'advanced', 'en', 'Bias cut fabric drapes elegantly.', 'Çapraz kesim kumaş zarif dökülür.'),
  ('millinery', 'şapka yapımı', 'clothes', 'advanced', 'en', 'Millinery requires precise hand stitching.', 'Şapka yapımı hassas el dikişi gerektirir.'),
  ('colorfastness', 'renk haslığı', 'clothes', 'advanced', 'en', 'Test colorfastness before washing reds.', 'Kırmızıları yıkamadan önce renk haslığını test et.'),
  ('pilling', 'tüylenme', 'clothes', 'advanced', 'en', 'Cheap knits suffer from pilling.', 'Ucuz trikolar tüylenmeden muzdarip olur.'),
  ('moisture-wicking', 'nem emici', 'clothes', 'advanced', 'en', 'Moisture-wicking shirts dry fast during runs.', 'Nem emici tişörtler koşuda hızla kurur.'),
  ('Gore-Tex', 'Gore-Tex', 'clothes', 'advanced', 'en', 'Gore-Tex jackets block rain and wind.', 'Gore-Tex ceketler yağmur ve rüzgarı keser.'),
  ('ethical sourcing', 'etik tedarik', 'clothes', 'advanced', 'en', 'Ethical sourcing audits factory conditions.', 'Etik tedarik fabrika koşullarını denetler.'),
  ('circular fashion', 'döngüsel moda', 'clothes', 'advanced', 'en', 'Circular fashion recycles old garments.', 'Döngüsel moda eski giysileri geri dönüştürür.'),
  ('greenwashing', 'yeşil aklama', 'clothes', 'advanced', 'en', 'Some brands risk greenwashing claims.', 'Bazı markalar yeşil aklama iddiaları riski taşır.'),
  ('traceability', 'izlenebilirlik', 'clothes', 'advanced', 'en', 'Traceability tracks cotton from farm to shirt.', 'İzlenebilirlik pamuğu tarladan gömleğe takip eder.'),
  ('vegan leather', 'vegan deri', 'clothes', 'advanced', 'en', 'Vegan leather uses plant-based coatings.', 'Vegan deri bitki bazlı kaplamalar kullanır.'),
  ('upcycling', 'upcycling', 'clothes', 'advanced', 'en', 'Upcycling turns old jeans into bags.', 'Upcycling eski kotları çantaya dönüştürür.'),
  ('sartorial', 'giyimle ilgili', 'clothes', 'advanced', 'en', 'His sartorial taste favors classic cuts.', 'Giyim zevki klasik kesimleri tercih ediyor.');
