INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('grateful', 'minnettar', 'emotions', 'beginner', 'en', 'I am grateful for your help.', 'Yardımın için minnettarım.'),
  ('bored', 'sıkılmış', 'emotions', 'beginner', 'en', 'The lecture made students bored.', 'Ders öğrencileri sıktı.'),
  ('confused', 'kafası karışık', 'emotions', 'beginner', 'en', 'New rules left him confused.', 'Yeni kurallar onu kafası karışık bıraktı.'),
  ('confident', 'kendinden emin', 'emotions', 'beginner', 'en', 'Practice made her more confident.', 'Pratik onu daha kendinden emin yaptı.'),
  ('shy', 'utangaç', 'emotions', 'beginner', 'en', 'The shy boy hid behind his mother.', 'Utangaç çocuk annesinin arkasına saklandı.'),
  ('curious', 'meraklı', 'emotions', 'beginner', 'en', 'Curious minds ask many questions.', 'Meraklı zihinler çok soru sorar.'),
  ('peaceful', 'huzurlu', 'emotions', 'beginner', 'en', 'The garden felt peaceful at dawn.', 'Bahçe şafakta huzurlu hissettiriyordu.'),
  ('hurt', 'incinmiş', 'emotions', 'beginner', 'en', 'Her words left him hurt.', 'Sözleri onu incitti.'),
  ('smile', 'gülümseme', 'emotions', 'beginner', 'en', 'A warm smile changed the mood.', 'Sıcak bir gülümseme havayı değiştirdi.'),
  ('cry', 'ağlamak', 'emotions', 'beginner', 'en', 'It is okay to cry sometimes.', 'Bazen ağlamak normaldir.'),
  ('anxious', 'kaygılı', 'emotions', 'intermediate', 'en', 'She felt anxious before the interview.', 'Görüşmeden önce kaygılı hissetti.'),
  ('frustrated', 'hayal kırıklığına uğramış', 'emotions', 'intermediate', 'en', 'Delays left commuters frustrated.', 'Gecikmeler yolcuları hayal kırıklığına uğrattı.'),
  ('embarrassed', 'mahcup', 'emotions', 'intermediate', 'en', 'He was embarrassed by his mistake.', 'Hatasından mahcup oldu.'),
  ('disappointed', 'hayal kırıklığına uğramış', 'emotions', 'intermediate', 'en', 'Fans were disappointed by the score.', 'Taraftarlar skordan hayal kırıklığına uğradı.'),
  ('overwhelmed', 'bunalmış', 'emotions', 'intermediate', 'en', 'Too many tasks left her overwhelmed.', 'Çok fazla görev onu bunaltı.'),
  ('content', 'memnun', 'emotions', 'intermediate', 'en', 'Simple routines keep him content.', 'Basit rutinler onu memnun tutuyor.'),
  ('nostalgic', 'nostaljik', 'emotions', 'intermediate', 'en', 'Old photos made her nostalgic.', 'Eski fotoğraflar onu nostaljik yaptı.'),
  ('optimistic', 'iyimser', 'emotions', 'intermediate', 'en', 'Stay optimistic despite setbacks.', 'Aksiliklere rağmen iyimser kal.'),
  ('pessimistic', 'kötümser', 'emotions', 'intermediate', 'en', 'Pessimistic thoughts drain energy.', 'Kötümser düşünceler enerjiyi tüketir.'),
  ('empathy', 'empati', 'emotions', 'intermediate', 'en', 'Empathy helps resolve conflicts.', 'Empati anlaşmazlıkları çözmeye yardım eder.'),
  ('sympathy', 'sempati', 'emotions', 'intermediate', 'en', 'They expressed sympathy for the family.', 'Aileye sempati gösterdiler.'),
  ('compassion', 'merhamet', 'emotions', 'intermediate', 'en', 'Compassion guides her volunteer work.', 'Merhamet gönüllü çalışmasını yönlendirir.'),
  ('resentment', 'kin', 'emotions', 'intermediate', 'en', 'Resentment grew after unfair treatment.', 'Adaletsiz muameleden sonra kin büyüdü.'),
  ('regret', 'pişmanlık', 'emotions', 'intermediate', 'en', 'He spoke with deep regret.', 'Derin pişmanlıkla konuştu.'),
  ('enthusiasm', 'heves', 'emotions', 'intermediate', 'en', 'Her enthusiasm inspired the team.', 'Hevesi takımı motive etti.'),
  ('motivation', 'motivasyon', 'emotions', 'intermediate', 'en', 'Clear goals boost motivation.', 'Net hedefler motivasyonu artırır.'),
  ('insecurity', 'güvensizlik', 'emotions', 'intermediate', 'en', 'Insecurity often hides behind anger.', 'Güvensizlik genelde öfkenin arkasında gizlenir.'),
  ('self-esteem', 'özgüven', 'emotions', 'intermediate', 'en', 'Praise can raise self-esteem.', 'Övgü özgüveni artırabilir.'),
  ('mood swing', 'ruh hali değişimi', 'emotions', 'intermediate', 'en', 'Lack of sleep causes mood swings.', 'Uyku eksikliği ruh hali değişimine neden olur.'),
  ('stress relief', 'stres giderme', 'emotions', 'intermediate', 'en', 'Walking offers quick stress relief.', 'Yürümek hızlı stres giderme sağlar.'),
  ('emotional support', 'duygusal destek', 'emotions', 'intermediate', 'en', 'Friends provide emotional support.', 'Arkadaşlar duygusal destek sağlar.'),
  ('heartbroken', 'kalbi kırık', 'emotions', 'intermediate', 'en', 'She felt heartbroken after the breakup.', 'Ayrılıktan sonra kalbi kırık hissetti.'),
  ('thrilled', 'coşkun', 'emotions', 'intermediate', 'en', 'They were thrilled to hear the news.', 'Haberi duyunca coşkundular.'),
  ('irritated', 'sinirli', 'emotions', 'intermediate', 'en', 'Noise from construction irritated neighbors.', 'İnşaat gürültüsü komşuları sinirlendirdi.'),
  ('gratitude', 'minnettarlık', 'emotions', 'intermediate', 'en', 'Gratitude improves daily outlook.', 'Minnettarlık günlük bakış açısını iyileştirir.'),
  ('patience', 'sabır', 'emotions', 'intermediate', 'en', 'Patience helps during long waits.', 'Sabır uzun beklemelerde yardımcı olur.'),
  ('envy', 'kıskançlık', 'emotions', 'intermediate', 'en', 'Envy can poison friendships.', 'Kıskançlık dostlukları zehirleyebilir.'),
  ('affection', 'sevgi', 'emotions', 'intermediate', 'en', 'Small gestures show affection.', 'Küçük jestler sevgiyi gösterir.'),
  ('melancholy', 'melankoli', 'emotions', 'intermediate', 'en', 'Rainy days bring a quiet melancholy.', 'Yağmurlu günler sessiz bir melankoli getirir.'),
  ('serenity', 'sükunet', 'emotions', 'intermediate', 'en', 'Meditation brought her serenity.', 'Meditasyon ona sükunet getirdi.');
