INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('stout', 'stout', 'drinks', 'intermediate', 'en', 'Stout feels heavy and creamy.', 'Stout ağır ve kremalı hissettirir.'),
  ('sports drink', 'spor içeceği', 'drinks', 'intermediate', 'en', 'Sports drinks replace electrolytes.', 'Spor içecekleri elektrolitleri yerine koyar.'),
  ('hydration', 'hidrasyon', 'drinks', 'intermediate', 'en', 'Good hydration improves focus.', 'İyi hidrasyon odaklanmayı artırır.'),
  ('dehydration', 'dehidrasyon', 'drinks', 'intermediate', 'en', 'Dehydration causes headaches.', 'Dehidrasyon baş ağrısına neden olur.'),
  ('barista', 'barista', 'drinks', 'intermediate', 'en', 'The barista drew art in the foam.', 'Barista köpüğe sanat çizdi.'),
  ('tap water', 'musluk suyu', 'drinks', 'intermediate', 'en', 'Tap water is safe to drink here.', 'Burada musluk suyu içmek güvenlidir.'),
  ('filtered water', 'filtrelenmiş su', 'drinks', 'intermediate', 'en', 'Filtered water removes chlorine taste.', 'Filtrelenmiş su klor tadını giderir.'),
  ('pitcher', 'sürahi', 'drinks', 'intermediate', 'en', 'Fill the pitcher with iced tea.', 'Sürahibi soğuk çayla doldur.'),
  ('shaker', 'çalkalayıcı', 'drinks', 'intermediate', 'en', 'Shake the cocktail in a metal shaker.', 'Kokteyli metal çalkalayıcıda çalkala.'),
  ('wine glass', 'şarap kadehi', 'drinks', 'intermediate', 'en', 'Hold the wine glass by the stem.', 'Şarap kadehini sapından tut.'),
  ('mouthfeel', 'ağız hissi', 'drinks', 'advanced', 'en', 'Mouthfeel describes texture in wine.', 'Ağız hissi şarapta dokuyu tanımlar.'),
  ('tannins', 'tanen', 'drinks', 'advanced', 'en', 'High tannins make wine taste dry.', 'Yüksek tanen şarabı kuru tadar.'),
  ('terroir', 'terroir', 'drinks', 'advanced', 'en', 'Terroir shapes grape character.', 'Terroir üzüm karakterini şekillendirir.'),
  ('oxidation', 'oksidasyon', 'drinks', 'advanced', 'en', 'Oxidation can spoil opened wine.', 'Oksidasyon açılmış şarabı bozabilir.'),
  ('fortified wine', 'fortifiye şarap', 'drinks', 'advanced', 'en', 'Fortified wine contains added spirits.', 'Fortifiye şarap ek distile içki içerir.'),
  ('mixology', 'mixology', 'drinks', 'advanced', 'en', 'Mixology blends science and creativity.', 'Mixology bilim ve yaratıcılığı birleştirir.'),
  ('palate cleanser', 'damak temizleyici', 'drinks', 'advanced', 'en', 'Sorbet acts as a palate cleanser.', 'Sorbet damak temizleyici görevi görür.'),
  ('astringency', 'burukluk', 'drinks', 'advanced', 'en', 'Tea astringency comes from tannins.', 'Çay burukluğu tanenlerden gelir.'),
  ('microfoam', 'mikro köpük', 'drinks', 'advanced', 'en', 'Microfoam makes latte art possible.', 'Mikro köpük latte sanatını mümkün kılar.'),
  ('extraction yield', 'ekstraksiyon verimi', 'drinks', 'advanced', 'en', 'Baristas tune extraction yield carefully.', 'Baristalar ekstraksiyon verimini dikkatle ayarlar.'),
  ('dry hopping', 'kuru şerbetçi otu', 'drinks', 'advanced', 'en', 'Dry hopping adds aroma without bitterness.', 'Kuru şerbetçi otu acılık olmadan aroma ekler.'),
  ('barrel aging', 'fıçıda olgunlaştırma', 'drinks', 'advanced', 'en', 'Barrel aging adds vanilla notes to whiskey.', 'Fıçıda olgunlaştırma viskiye vanilya notaları katar.'),
  ('proof', 'alkol derecesi', 'drinks', 'advanced', 'en', 'Higher proof spirits burn slightly.', 'Daha yüksek alkol dereceli içkiler hafif yakıcıdır.'),
  ('hangover', 'akşamdan kalma', 'drinks', 'advanced', 'en', 'Hydration helps reduce hangover symptoms.', 'Hidrasyon akşamdan kalma belirtilerini azaltmaya yardım eder.'),
  ('responsible drinking', 'sorumlu içme', 'drinks', 'advanced', 'en', 'Responsible drinking means knowing your limits.', 'Sorumlu içme sınırlarını bilmek demektir.'),
  ('blood alcohol level', 'kan alkol seviyesi', 'drinks', 'advanced', 'en', 'Blood alcohol level affects driving ability.', 'Kan alkol seviyesi sürüş yeteneğini etkiler.'),
  ('dehydrating effect', 'susuzlaştırıcı etki', 'drinks', 'advanced', 'en', 'Alcohol has a dehydrating effect.', 'Alkol susuzlaştırıcı bir etkiye sahiptir.'),
  ('electrolyte balance', 'elektrolit dengesi', 'drinks', 'advanced', 'en', 'Sports drinks restore electrolyte balance.', 'Spor içecekleri elektrolit dengesini geri kazandırır.'),
  ('water footprint', 'su ayak izi', 'drinks', 'advanced', 'en', 'Coffee has a large water footprint.', 'Kahvenin büyük bir su ayak izi vardır.'),
  ('third-wave coffee', 'üçüncü dalga kahve', 'drinks', 'advanced', 'en', 'Third-wave coffee treats beans like craft.', 'Üçüncü dalga kahve çekirdekleri zanaat gibi ele alır.'),
  ('nitro cold brew', 'nitro soğuk demleme', 'drinks', 'advanced', 'en', 'Nitro cold brew pours creamy from the tap.', 'Nitro soğuk demleme musluktan kremalı akar.'),
  ('sommelier', 'sommelier', 'drinks', 'advanced', 'en', 'The sommelier recommended a local red.', 'Sommelier yerel bir kırmızı önerdi.'),
  ('decanting', 'dekantasyon', 'drinks', 'advanced', 'en', 'Decanting aerates young red wine.', 'Dekantasyon genç kırmızı şarabı havalandırır.'),
  ('mouth-coating', 'ağız kaplama', 'drinks', 'advanced', 'en', 'Rich stout has a mouth-coating texture.', 'Zengin stout ağız kaplayan bir dokuya sahiptir.'),
  ('quaffable', 'kolay içilen', 'drinks', 'advanced', 'en', 'This lager is light and quaffable.', 'Bu lager hafif ve kolay içilendir.'),
  ('session beer', 'session birası', 'drinks', 'advanced', 'en', 'Session beer has lower alcohol.', 'Session birasının alkolü daha düşüktür.'),
  ('cask-conditioned', 'fıçıda koşullandırılmış', 'drinks', 'advanced', 'en', 'Cask-conditioned ale feels naturally soft.', 'Fıçıda koşullandırılmış ale doğal yumuşak hissettirir.'),
  ('mouth-puckering', 'buruk yapan', 'drinks', 'advanced', 'en', 'Unripe fruit can be mouth-puckering.', 'Ham meyve buruk yapabilir.'),
  ('zero-proof spirit', 'sıfır alkol ruhu', 'drinks', 'advanced', 'en', 'Zero-proof spirits mimic gin flavor.', 'Sıfır alkol ruhları cin tadını taklit eder.'),
  ('hydration strategy', 'hidrasyon stratejisi', 'drinks', 'advanced', 'en', 'Athletes plan a hydration strategy for races.', 'Sporcular yarışlar için hidrasyon stratejisi planlar.');
