INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('relationship', 'ilişki', 'relationships', 'intermediate', 'en', 'Healthy relationships need communication.', 'Sağlıklı ilişkiler iletişim gerektirir.'),
  ('commitment', 'bağlılık', 'relationships', 'intermediate', 'en', 'Commitment grows over shared experiences.', 'Bağlılık paylaşılan deneyimlerle büyür.'),
  ('breakup', 'ayrılık', 'relationships', 'intermediate', 'en', 'The breakup was painful but necessary.', 'Ayrılık acı vericiydi ama gerekliydi.'),
  ('reconciliation', 'barışma', 'relationships', 'intermediate', 'en', 'Reconciliation took honest conversations.', 'Barışma dürüst konuşmalar gerektirdi.'),
  ('long-distance', 'uzak mesafe', 'relationships', 'intermediate', 'en', 'Long-distance couples schedule video calls.', 'Uzak mesafe çiftler görüntülü arama planlar.'),
  ('boundaries', 'sınırlar', 'relationships', 'intermediate', 'en', 'Clear boundaries protect mental health.', 'Net sınırlar ruh sağlığını korur.'),
  ('compromise', 'uzlaşma', 'relationships', 'intermediate', 'en', 'Marriage often requires compromise.', 'Evlilik genelde uzlaşma gerektirir.'),
  ('intimacy', 'yakınlık', 'relationships', 'intermediate', 'en', 'Emotional intimacy builds slowly.', 'Duygusal yakınlık yavaşça oluşur.'),
  ('jealousy', 'kıskançlık', 'relationships', 'intermediate', 'en', 'Jealousy can damage trust quickly.', 'Kıskançlık güveni hızla zedeleyebilir.'),
  ('forgiveness', 'affetme', 'relationships', 'intermediate', 'en', 'Forgiveness does not erase memory.', 'Affetme hafızayı silmez.'),
  ('loyalty', 'sadakat', 'relationships', 'intermediate', 'en', 'Loyalty shows in difficult moments.', 'Sadakat zor anlarda görülür.'),
  ('misunderstanding', 'yanlış anlama', 'relationships', 'intermediate', 'en', 'A misunderstanding caused the fight.', 'Yanlış anlama kavgaya neden oldu.'),
  ('family gathering', 'aile buluşması', 'relationships', 'intermediate', 'en', 'The family gathering lasted all day.', 'Aile buluşması bütün gün sürdü.'),
  ('in-laws', 'kayınvalide/kayınpeder', 'relationships', 'intermediate', 'en', 'She gets along well with her in-laws.', 'Kayınvalide ve kayınpederiyle iyi anlaşıyor.'),
  ('stepparent', 'üvey ebeveyn', 'relationships', 'intermediate', 'en', 'A stepparent joined the family last year.', 'Geçen yıl bir üvey ebeveyn aileye katıldı.'),
  ('blended family', 'karma aile', 'relationships', 'intermediate', 'en', 'A blended family needs patience and rules.', 'Karma aile sabır ve kurallar gerektirir.'),
  ('single parent', 'bekar ebeveyn', 'relationships', 'intermediate', 'en', 'Single parents juggle work and childcare.', 'Bekar ebeveynler iş ve çocuk bakımını dengeler.'),
  ('co-parenting', 'ortak ebeveynlik', 'relationships', 'intermediate', 'en', 'Co-parenting works with clear schedules.', 'Ortak ebeveynlik net programlarla işler.'),
  ('engagement', 'nişan', 'relationships', 'intermediate', 'en', 'They announced their engagement online.', 'Nişanlarını çevrimiçi duyurdular.'),
  ('household chores', 'ev işleri', 'relationships', 'intermediate', 'en', 'Share household chores fairly.', 'Ev işlerini adil paylaşın.'),
  ('quality time', 'kaliteli zaman', 'relationships', 'intermediate', 'en', 'Quality time matters more than gifts.', 'Kaliteli zaman hediyelerden daha önemlidir.'),
  ('active listening', 'aktif dinleme', 'relationships', 'intermediate', 'en', 'Active listening prevents many fights.', 'Aktif dinleme birçok kavgayı önler.'),
  ('conflict resolution', 'çatışma çözümü', 'relationships', 'intermediate', 'en', 'Conflict resolution skills help couples.', 'Çatışma çözümü becerileri çiftlere yardım eder.'),
  ('trust issue', 'güven sorunu', 'relationships', 'intermediate', 'en', 'Past lies created a trust issue.', 'Geçmiş yalanlar güven sorunu yarattı.'),
  ('social circle', 'sosyal çevre', 'relationships', 'intermediate', 'en', 'Her social circle changed after moving.', 'Taşındıktan sonra sosyal çevresi değişti.'),
  ('mentor', 'mentor', 'relationships', 'intermediate', 'en', 'A mentor guided his early career.', 'Bir mentor erken kariyerinde yol gösterdi.'),
  ('acquaintance', 'tanıdık', 'relationships', 'intermediate', 'en', 'An acquaintance introduced them.', 'Bir tanıdık onları tanıştırdı.'),
  ('best friend', 'en iyi arkadaş', 'relationships', 'intermediate', 'en', 'My best friend knows all my secrets.', 'En iyi arkadaşım tüm sırlarımı biliyor.'),
  ('roommate', 'ev arkadaşı', 'relationships', 'intermediate', 'en', 'Roommates split rent and bills.', 'Ev arkadaşları kira ve faturaları paylaşır.'),
  ('pen pal', 'mektup arkadaşı', 'relationships', 'intermediate', 'en', 'She kept a pen pal for years.', 'Yıllarca bir mektup arkadaşı tuttu.'),
  ('attachment style', 'bağlanma stili', 'relationships', 'advanced', 'en', 'Attachment style shapes adult relationships.', 'Bağlanma stili yetişkin ilişkilerini şekillendirir.'),
  ('secure attachment', 'güvenli bağlanma', 'relationships', 'advanced', 'en', 'Secure attachment fosters stable bonds.', 'Güvenli bağlanma kararlı bağları destekler.'),
  ('anxious attachment', 'kaygılı bağlanma', 'relationships', 'advanced', 'en', 'Anxious attachment fears abandonment.', 'Kaygılı bağlanma terk edilmekten korkar.'),
  ('avoidant attachment', 'kaçınan bağlanma', 'relationships', 'advanced', 'en', 'Avoidant attachment keeps emotional distance.', 'Kaçınan bağlanma duygusal mesafe korur.'),
  ('codependency', 'bağımlılık', 'relationships', 'advanced', 'en', 'Codependency blurs personal boundaries.', 'Bağımlılık kişisel sınırları bulanıklaştırır.'),
  ('emotional availability', 'duygusal erişilebilirlik', 'relationships', 'advanced', 'en', 'Emotional availability deepens trust.', 'Duygusal erişilebilirlik güveni derinleştirir.'),
  ('love language', 'sevgi dili', 'relationships', 'advanced', 'en', 'Learn your partner''s love language.', 'Partnerinin sevgi dilini öğren.'),
  ('narcissistic behavior', 'narsist davranış', 'relationships', 'advanced', 'en', 'Narcissistic behavior ignores others'' needs.', 'Narsist davranış başkalarının ihtiyaçlarını görmezden gelir.'),
  ('toxic relationship', 'toksik ilişki', 'relationships', 'advanced', 'en', 'A toxic relationship drains self-esteem.', 'Toksik ilişki özgüveni tüketir.'),
  ('emotional abuse', 'duygusal istismar', 'relationships', 'advanced', 'en', 'Emotional abuse often hides behind jokes.', 'Duygusal istismar genelde şakaların arkasında gizlenir.');
