INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('vocational training', 'mesleki eğitim', 'education', 'intermediate', 'en', 'Vocational training prepares skilled workers.', 'Mesleki eğitim nitelikli işçiler yetiştirir.'),
  ('online learning', 'çevrimiçi öğrenme', 'education', 'intermediate', 'en', 'Online learning offers flexible schedules.', 'Çevrimiçi öğrenme esnek programlar sunar.'),
  ('blended learning', 'harmanlanmış öğrenme', 'education', 'intermediate', 'en', 'Blended learning mixes video and class time.', 'Harmanlanmış öğrenme video ve sınıf süresini karıştırır.'),
  ('formative assessment', 'biçimlendirici değerlendirme', 'education', 'intermediate', 'en', 'Formative assessment guides daily teaching.', 'Biçimlendirici değerlendirme günlük öğretimi yönlendirir.'),
  ('summative assessment', 'özet değerlendirme', 'education', 'intermediate', 'en', 'Final exams are summative assessment.', 'Final sınavları özet değerlendirmedir.'),
  ('learning objective', 'öğrenme hedefi', 'education', 'intermediate', 'en', 'Each lesson states a learning objective.', 'Her ders bir öğrenme hedefi belirtir.'),
  ('critical thinking', 'eleştirel düşünme', 'education', 'intermediate', 'en', 'Critical thinking questions assumptions.', 'Eleştirel düşünme varsayımları sorgular.'),
  ('study group', 'çalışma grubu', 'education', 'intermediate', 'en', 'Our study group meets on Wednesdays.', 'Çalışma grubumuz çarşamba buluşuyor.'),
  ('office hours', 'danışma saati', 'education', 'intermediate', 'en', 'Visit professors during office hours.', 'Danışma saatinde profesörleri ziyaret et.'),
  ('dean', 'dekan', 'education', 'intermediate', 'en', 'The dean approved the new program.', 'Dekan yeni programı onayladı.'),
  ('pedagogy', 'pedagoji', 'education', 'advanced', 'en', 'Modern pedagogy favors active learning.', 'Modern pedagoji aktif öğrenmeyi tercih eder.'),
  ('andragogy', 'andragoji', 'education', 'advanced', 'en', 'Andragogy focuses on adult learners.', 'Andragoji yetişkin öğrenenlere odaklanır.'),
  ('constructivism', 'yapılandırmacılık', 'education', 'advanced', 'en', 'Constructivism builds knowledge through experience.', 'Yapılandırmacılık bilgiyi deneyimle inşa eder.'),
  ('metacognition', 'üstbiliş', 'education', 'advanced', 'en', 'Metacognition improves study strategies.', 'Üstbiliş çalışma stratejilerini iyileştirir.'),
  ('scaffolding', 'iskele kurma', 'education', 'advanced', 'en', 'Teachers use scaffolding for complex tasks.', 'Öğretmenler karmaşık görevler için iskele kurma kullanır.'),
  ('differentiated instruction', 'farklılaştırılmış öğretim', 'education', 'advanced', 'en', 'Differentiated instruction meets diverse needs.', 'Farklılaştırılmış öğretim çeşitli ihtiyaçları karşılar.'),
  ('inclusive education', 'kapsayıcı eğitim', 'education', 'advanced', 'en', 'Inclusive education welcomes all abilities.', 'Kapsayıcı eğitim tüm yetenekleri kucaklar.'),
  ('learning analytics', 'öğrenme analitiği', 'education', 'advanced', 'en', 'Learning analytics track student progress online.', 'Öğrenme analitiği öğrenci ilerlemesini çevrimiçi izler.'),
  ('competency-based education', 'yetkinlik temelli eğitim', 'education', 'advanced', 'en', 'Competency-based education measures skills gained.', 'Yetkinlik temelli eğitim kazanılan becerileri ölçer.'),
  ('epistemology', 'epistemoloji', 'education', 'advanced', 'en', 'Epistemology asks how we know truth.', 'Epistemoloji gerçeği nasıl bildiğimizi sorar.'),
  ('heuristic', 'sezgisel yöntem', 'education', 'advanced', 'en', 'A useful heuristic speeds problem solving.', 'Faydalı bir sezgisel yöntem problem çözmeyi hızlandırır.'),
  ('cognitive load theory', 'bilişsel yük teorisi', 'education', 'advanced', 'en', 'Cognitive load theory limits slide text.', 'Bilişsel yük teorisi slayt metnini sınırlar.'),
  ('spaced repetition', 'aralıklı tekrar', 'education', 'advanced', 'en', 'Spaced repetition boosts long-term memory.', 'Aralıklı tekrar uzun süreli hafızayı güçlendirir.'),
  ('interdisciplinary', 'disiplinler arası', 'education', 'advanced', 'en', 'Interdisciplinary courses blend science and art.', 'Disiplinler arası dersler bilim ve sanatı birleştirir.'),
  ('doctoral candidacy', 'doktora adaylığı', 'education', 'advanced', 'en', 'Doctoral candidacy follows qualifying exams.', 'Doktora adaylığı yeterlilik sınavlarını takip eder.'),
  ('dissertation defense', 'tez savunması', 'education', 'advanced', 'en', 'Her dissertation defense lasts several hours.', 'Her tez savunması birkaç saat sürer.'),
  ('grant funding', 'hibe fonu', 'education', 'advanced', 'en', 'Grant funding supports university research.', 'Hibe fonu üniversite araştırmasını destekler.'),
  ('tenure track', 'kadrolu akademik yol', 'education', 'advanced', 'en', 'She joined a tenure track position.', 'Kadrolu akademik yola geçen bir pozisyona girdi.'),
  ('open educational resources', 'açık eğitim kaynakları', 'education', 'advanced', 'en', 'Open educational resources reduce textbook costs.', 'Açık eğitim kaynakları ders kitabı maliyetlerini düşürür.'),
  ('MOOC', 'MOOC', 'education', 'advanced', 'en', 'A MOOC reached learners worldwide.', 'Bir MOOC dünya çapında öğrenenlere ulaştı.'),
  ('flipped classroom', 'ters yüz sınıf', 'education', 'advanced', 'en', 'The flipped classroom assigns videos at home.', 'Ters yüz sınıf evde video ödevi verir.'),
  ('experiential learning', 'deneyimsel öğrenme', 'education', 'advanced', 'en', 'Experiential learning uses real-world projects.', 'Deneyimsel öğrenme gerçek dünya projeleri kullanır.'),
  ('standardized testing', 'standart test', 'education', 'advanced', 'en', 'Standardized testing draws ongoing debate.', 'Standart test süregelen tartışma yaratır.'),
  ('achievement gap', 'başarı farkı', 'education', 'advanced', 'en', 'Policies aim to close the achievement gap.', 'Politikalar başarı farkını kapatmayı hedefler.'),
  ('socioeconomic disparity', 'sosyoekonomik eşitsizlik', 'education', 'advanced', 'en', 'Socioeconomic disparity affects school access.', 'Sosyoekonomik eşitsizlik okula erişimi etkiler.'),
  ('neuroeducation', 'nöroeğitim', 'education', 'advanced', 'en', 'Neuroeducation links brain science to teaching.', 'Nöroeğitim beyin bilimini öğretime bağlar.'),
  ('formative feedback loop', 'biçimlendirici geri bildirim döngüsü', 'education', 'advanced', 'en', 'A formative feedback loop guides revision.', 'Biçimlendirici geri bildirim döngüsü revizyonu yönlendirir.'),
  ('academic integrity', 'akademik dürüstlük', 'education', 'advanced', 'en', 'Academic integrity forbids cheating.', 'Akademik dürüstlük kopya çekmeyi yasaklar.'),
  ('institutional review board', 'kurumsal inceleme kurulu', 'education', 'advanced', 'en', 'Research needs institutional review board approval.', 'Araştırma kurumsal inceleme kurulu onayı gerektirir.'),
  ('lifelong learning', 'yaşam boyu öğrenme', 'education', 'advanced', 'en', 'Lifelong learning keeps skills current.', 'Yaşam boyu öğrenme becerileri güncel tutar.');
