INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('intellectual property', 'fikri mülkiyet', 'jobs', 'advanced', 'en', 'Contracts define intellectual property rights.', 'Sözleşmeler fikri mülkiyet haklarını tanımlar.'),
  ('due diligence', 'durum tespiti', 'jobs', 'advanced', 'en', 'Investors perform due diligence before funding.', 'Yatırımcılar fonlamadan önce durum tespiti yapar.'),
  ('corporate governance', 'kurumsal yönetim', 'jobs', 'advanced', 'en', 'Strong corporate governance builds trust.', 'Güçlü kurumsal yönetim güven oluşturur.'),
  ('succession planning', 'halefiyet planlaması', 'jobs', 'advanced', 'en', 'Succession planning prepares future leaders.', 'Halefiyet planlaması gelecek liderleri hazırlar.'),
  ('organizational culture', 'örgüt kültürü', 'jobs', 'advanced', 'en', 'Organizational culture shapes daily behavior.', 'Örgüt kültürü günlük davranışı şekillendirir.'),
  ('KPI', 'KPI', 'jobs', 'advanced', 'en', 'Managers track KPIs every quarter.', 'Yöneticiler her çeyrek KPI''ları takip eder.'),
  ('stakeholder', 'paydaş', 'jobs', 'advanced', 'en', 'Stakeholders approved the merger plan.', 'Paydaşlar birleşme planını onayladı.'),
  ('merger', 'birleşme', 'jobs', 'advanced', 'en', 'The merger created a larger company.', 'Birleşme daha büyük bir şirket oluşturdu.'),
  ('acquisition', 'satın alma', 'jobs', 'advanced', 'en', 'The acquisition expanded market share.', 'Satın alma pazar payını genişletti.'),
  ('downsizing', 'küçülme', 'jobs', 'advanced', 'en', 'Downsizing eliminated several departments.', 'Küçülme birkaç departmanı kaldırdı.'),
  ('restructuring', 'yeniden yapılandırma', 'jobs', 'advanced', 'en', 'Restructuring aimed to cut overhead.', 'Yeniden yapılandırma genel giderleri kesmeyi hedefledi.'),
  ('equity stake', 'hisse payı', 'jobs', 'advanced', 'en', 'Founders kept a large equity stake.', 'Kurucular büyük bir hisse payını tuttu.'),
  ('vesting schedule', 'hak kazanma takvimi', 'jobs', 'advanced', 'en', 'The vesting schedule spans four years.', 'Hak kazanma takvimi dört yıl sürer.'),
  ('non-disclosure agreement', 'gizlilik sözleşmesi', 'jobs', 'advanced', 'en', 'Employees signed a non-disclosure agreement.', 'Çalışanlar gizlilik sözleşmesi imzaladı.'),
  ('arbitration', 'tahkim', 'jobs', 'advanced', 'en', 'The contract requires arbitration for disputes.', 'Sözleşme anlaşmazlıklar için tahkim gerektirir.'),
  ('compliance officer', 'uyum görevlisi', 'jobs', 'advanced', 'en', 'The compliance officer audits internal rules.', 'Uyum görevlisi iç kuralları denetler.'),
  ('occupational hazard', 'mesleki tehlike', 'jobs', 'advanced', 'en', 'Construction has many occupational hazards.', 'İnşaatın birçok mesleki tehlikesi vardır.'),
  ('glass ceiling', 'cam tavan', 'jobs', 'advanced', 'en', 'She broke the glass ceiling in her firm.', 'Firmasında cam tavanı kırdı.'),
  ('pay gap', 'ücret farkı', 'jobs', 'advanced', 'en', 'Reports highlight the gender pay gap.', 'Raporlar cinsiyet ücret farkını vurguluyor.'),
  ('industrial action', 'sendikal eylem', 'jobs', 'advanced', 'en', 'Industrial action delayed production.', 'Sendikal eylem üretimi geciktirdi.'),
  ('apple', 'elma', 'foods', 'beginner', 'en', 'I eat an apple every morning.', 'Her sabah bir elma yerim.'),
  ('bread', 'ekmek', 'foods', 'beginner', 'en', 'Fresh bread smells wonderful.', 'Taze ekmek harika kokuyor.'),
  ('cheese', 'peynir', 'foods', 'beginner', 'en', 'She added cheese to the sandwich.', 'Sandviçe peynir ekledi.'),
  ('egg', 'yumurta', 'foods', 'beginner', 'en', 'Boil the eggs for eight minutes.', 'Yumurtaları sekiz dakika haşla.'),
  ('rice', 'pirinç', 'foods', 'beginner', 'en', 'We serve rice with grilled chicken.', 'Izgara tavukla pirinç servis ediyoruz.'),
  ('chicken', 'tavuk', 'foods', 'beginner', 'en', 'Roast chicken is my favorite meal.', 'Fırın tavuk en sevdiğim yemek.'),
  ('fish', 'balık', 'foods', 'beginner', 'en', 'Grilled fish is healthy and light.', 'Izgara balık sağlıklı ve hafiftir.'),
  ('tomato', 'domates', 'foods', 'beginner', 'en', 'Slice the tomato for the salad.', 'Salata için domatesi dilimle.'),
  ('potato', 'patates', 'foods', 'beginner', 'en', 'Mashed potato goes well with steak.', 'Patates püresi biftekle iyi gider.'),
  ('onion', 'soğan', 'foods', 'beginner', 'en', 'Chop the onion finely.', 'Soğanı ince doğra.'),
  ('carrot', 'havuç', 'foods', 'beginner', 'en', 'Carrots are rich in vitamins.', 'Havuç vitamin açısından zengindir.'),
  ('banana', 'muz', 'foods', 'beginner', 'en', 'A banana is a quick snack.', 'Muz hızlı bir atıştırmalıktır.'),
  ('orange', 'portakal', 'foods', 'beginner', 'en', 'Squeeze fresh orange juice.', 'Taze portakal suyu sık.'),
  ('grape', 'üzüm', 'foods', 'beginner', 'en', 'These grapes are very sweet.', 'Bu üzümler çok tatlı.'),
  ('strawberry', 'çilek', 'foods', 'beginner', 'en', 'Strawberries taste best in summer.', 'Çilekler yazın en iyi tadılır.'),
  ('watermelon', 'karpuz', 'foods', 'beginner', 'en', 'Watermelon is refreshing on hot days.', 'Karpuz sıcak günlerde ferahlatıcıdır.'),
  ('lemon', 'limon', 'foods', 'beginner', 'en', 'Add lemon to the tea.', 'Çaya limon ekle.'),
  ('garlic', 'sarımsak', 'foods', 'beginner', 'en', 'Garlic gives the soup more flavor.', 'Sarımsak çorbaya daha fazla lezzet verir.'),
  ('pepper', 'biber', 'foods', 'beginner', 'en', 'Red pepper adds color to the dish.', 'Kırmızı biber yemeğe renk katar.'),
  ('salt', 'tuz', 'foods', 'beginner', 'en', 'Add a pinch of salt.', 'Bir tutam tuz ekle.');
