INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('precision medicine', 'hassas tıp', 'health', 'advanced', 'en', 'Precision medicine targets genetic profiles.', 'Hassas tıp genetik profillere odaklanır.'),
  ('health equity', 'sağlık eşitliği', 'health', 'advanced', 'en', 'Health equity reduces care gaps.', 'Sağlık eşitliği bakım boşluklarını azaltır.'),
  ('social determinants', 'sosyal belirleyiciler', 'health', 'advanced', 'en', 'Social determinants shape health outcomes.', 'Sosyal belirleyiciler sağlık sonuçlarını şekillendirir.'),
  ('longevity', 'uzun ömür', 'health', 'advanced', 'en', 'Exercise and diet support longevity.', 'Egzersiz ve diyet uzun ömürü destekler.'),
  ('oxidative stress', 'oksidatif stres', 'health', 'advanced', 'en', 'Antioxidants may reduce oxidative stress.', 'Antioksidanlar oksidatif stresi azaltabilir.'),
  ('hormonal imbalance', 'hormonal dengesizlik', 'health', 'advanced', 'en', 'Hormonal imbalance affects mood and energy.', 'Hormonal dengesizlik ruh halini ve enerjiyi etkiler.'),
  ('sleep hygiene', 'uyku hijyeni', 'health', 'advanced', 'en', 'Sleep hygiene includes a dark, cool room.', 'Uyku hijyeni karanlık, serin bir oda içerir.'),
  ('mindfulness therapy', 'farkındalık terapisi', 'health', 'advanced', 'en', 'Mindfulness therapy lowers stress markers.', 'Farkındalık terapisi stres belirteçlerini düşürür.'),
  ('rehabilitation protocol', 'rehabilitasyon protokolü', 'health', 'advanced', 'en', 'Follow the rehabilitation protocol daily.', 'Rehabilitasyon protokolünü her gün uygula.'),
  ('medical ethics', 'tıbbi etik', 'health', 'advanced', 'en', 'Medical ethics guides difficult decisions.', 'Tıbbi etik zor kararları yönlendirir.'),
  ('tree', 'ağaç', 'nature', 'beginner', 'en', 'The old tree shades the bench.', 'Eski ağaç bankı gölgeliyor.'),
  ('flower', 'çiçek', 'nature', 'beginner', 'en', 'She picked a red flower.', 'Kırmızı bir çiçek topladı.'),
  ('river', 'nehir', 'nature', 'beginner', 'en', 'The river flows to the sea.', 'Nehir denize akıyor.'),
  ('mountain', 'dağ', 'nature', 'beginner', 'en', 'Snow covers the mountain peak.', 'Kar dağ zirvesini kaplıyor.'),
  ('forest', 'orman', 'nature', 'beginner', 'en', 'We walked through a quiet forest.', 'Sessiz bir ormanda yürüdük.'),
  ('lake', 'göl', 'nature', 'beginner', 'en', 'The lake is calm at sunrise.', 'Göl gün doğumunda sakin.'),
  ('ocean', 'okyanus', 'nature', 'beginner', 'en', 'The ocean stretches beyond the horizon.', 'Okyanus ufkun ötesine uzanıyor.'),
  ('beach', 'plaj', 'nature', 'beginner', 'en', 'Children play on the sandy beach.', 'Çocuklar kumlu plajda oynuyor.'),
  ('sky', 'gökyüzü', 'nature', 'beginner', 'en', 'The sky turned pink at sunset.', 'Gün batımında gökyüzü pembe oldu.'),
  ('cloud', 'bulut', 'nature', 'beginner', 'en', 'Dark clouds mean rain soon.', 'Koyu bulutlar yakında yağmur demektir.'),
  ('rain', 'yağmur', 'nature', 'beginner', 'en', 'Light rain watered the garden.', 'Hafif yağmur bahçeyi suladı.'),
  ('snow', 'kar', 'nature', 'beginner', 'en', 'Snow fell all night.', 'Bütün gece kar yağdı.'),
  ('wind', 'rüzgar', 'nature', 'beginner', 'en', 'Strong wind bent the trees.', 'Kuvvetli rüzgar ağaçları eğdi.'),
  ('sun', 'güneş', 'nature', 'beginner', 'en', 'The sun rose over the hills.', 'Güneş tepelerin üzerinden doğdu.'),
  ('moon', 'ay', 'nature', 'beginner', 'en', 'The full moon lit the path.', 'Dolunay patikayı aydınlattı.'),
  ('star', 'yıldız', 'nature', 'beginner', 'en', 'Stars shine on clear nights.', 'Yıldızlar açık gecelerde parlar.'),
  ('rock', 'kaya', 'nature', 'beginner', 'en', 'He sat on a flat rock.', 'Düz bir kayanın üzerine oturdu.'),
  ('soil', 'toprak', 'nature', 'beginner', 'en', 'Rich soil helps plants grow.', 'Zengin toprak bitkilerin büyümesine yardım eder.'),
  ('grass', 'çimen', 'nature', 'beginner', 'en', 'Fresh grass smells sweet after rain.', 'Taze çimen yağmurdan sonra tatlı kokar.'),
  ('leaf', 'yaprak', 'nature', 'beginner', 'en', 'A yellow leaf fell slowly.', 'Sarı bir yaprak yavaşça düştü.'),
  ('seed', 'tohum', 'nature', 'beginner', 'en', 'Plant the seed in spring.', 'Tohumu ilkbaharda ek.'),
  ('hill', 'tepe', 'nature', 'beginner', 'en', 'We climbed the green hill.', 'Yeşil tepeye tırmandık.'),
  ('valley', 'vadi', 'nature', 'beginner', 'en', 'Mist filled the morning valley.', 'Sabah vadisini sis doldurdu.'),
  ('island', 'ada', 'nature', 'beginner', 'en', 'The island is reachable by ferry.', 'Adaya feribotla ulaşılır.'),
  ('desert', 'çöl', 'nature', 'beginner', 'en', 'The desert gets very hot by noon.', 'Çöl öğlene kadar çok ısınır.'),
  ('waterfall', 'şelale', 'nature', 'beginner', 'en', 'We heard the waterfall from far away.', 'Şelaleyi uzaktan duyduk.'),
  ('cave', 'mağara', 'nature', 'beginner', 'en', 'Bats live inside the cave.', 'Yarasalar mağaranın içinde yaşar.'),
  ('field', 'tarla', 'nature', 'beginner', 'en', 'Wheat waves in the open field.', 'Buğday açık tarlada dalgalanıyor.'),
  ('season', 'mevsim', 'nature', 'beginner', 'en', 'Each season changes the landscape.', 'Her mevsim manzarayı değiştirir.'),
  ('weather', 'hava', 'nature', 'beginner', 'en', 'Check the weather before hiking.', 'Yürüyüşten önce havayı kontrol et.');
