INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('shirt', 'gömlek', 'clothes', 'beginner', 'en', 'He wore a clean white shirt.', 'Temiz beyaz bir gömlek giydi.'),
  ('pants', 'pantolon', 'clothes', 'beginner', 'en', 'These pants are too long.', 'Bu pantolon çok uzun.'),
  ('dress', 'elbise', 'clothes', 'beginner', 'en', 'She bought a blue dress.', 'Mavi bir elbise aldı.'),
  ('skirt', 'etek', 'clothes', 'beginner', 'en', 'The skirt has floral patterns.', 'Eteğin çiçek desenleri var.'),
  ('jacket', 'ceket', 'clothes', 'beginner', 'en', 'Take a jacket, it is windy.', 'Bir ceket al, rüzgarlı.'),
  ('coat', 'palto', 'clothes', 'beginner', 'en', 'Hang your coat by the door.', 'Paltonu kapının yanına as.'),
  ('shoes', 'ayakkabı', 'clothes', 'beginner', 'en', 'Comfortable shoes help on long walks.', 'Rahat ayakkabılar uzun yürüyüşlerde yardımcı olur.'),
  ('socks', 'çorap', 'clothes', 'beginner', 'en', 'I need warm socks for winter.', 'Kış için sıcak çoraplara ihtiyacım var.'),
  ('hat', 'şapka', 'clothes', 'beginner', 'en', 'Wear a hat in strong sun.', 'Güçlü güneşte şapka tak.'),
  ('scarf', 'atkı', 'clothes', 'beginner', 'en', 'A wool scarf keeps your neck warm.', 'Yün atkı boynunu sıcak tutar.'),
  ('gloves', 'eldiven', 'clothes', 'beginner', 'en', 'Put on gloves before going out.', 'Dışarı çıkmadan önce eldiven giy.'),
  ('belt', 'kemer', 'clothes', 'beginner', 'en', 'Tighten your belt one notch.', 'Kemerini bir delik sık.'),
  ('jeans', 'kot pantolon', 'clothes', 'beginner', 'en', 'Jeans are perfect for casual days.', 'Kot pantolon günlük günler için mükemmel.'),
  ('T-shirt', 'tişört', 'clothes', 'beginner', 'en', 'He packed a plain T-shirt.', 'Düz bir tişört paketledi.'),
  ('sweater', 'kazak', 'clothes', 'beginner', 'en', 'This sweater is soft and warm.', 'Bu kazak yumuşak ve sıcak.'),
  ('shorts', 'şort', 'clothes', 'beginner', 'en', 'Shorts are fine for the beach.', 'Şort plaj için uygundur.'),
  ('boots', 'bot', 'clothes', 'beginner', 'en', 'Wear boots in the rain.', 'Yağmurda bot giy.'),
  ('sandals', 'sandalet', 'clothes', 'beginner', 'en', 'Sandals are cool in summer heat.', 'Sandalet yaz sıcağında serindir.'),
  ('pajamas', 'pijama', 'clothes', 'beginner', 'en', 'Change into pajamas before bed.', 'Yatmadan önce pijamaya geç.'),
  ('underwear', 'iç çamaşırı', 'clothes', 'beginner', 'en', 'Pack extra underwear for the trip.', 'Gezi için fazladan iç çamaşırı koy.'),
  ('tie', 'kravat', 'clothes', 'beginner', 'en', 'He adjusted his tie before the meeting.', 'Toplantıdan önce kravatını düzeltti.'),
  ('suit', 'takım elbise', 'clothes', 'beginner', 'en', 'A dark suit looks formal.', 'Koyu takım elbise resmi görünür.'),
  ('button', 'düğme', 'clothes', 'beginner', 'en', 'A button fell off my coat.', 'Paltomdan bir düğme düştü.'),
  ('zipper', 'fermuar', 'clothes', 'beginner', 'en', 'The zipper stuck halfway.', 'Fermuar yarıda takıldı.'),
  ('pocket', 'cep', 'clothes', 'beginner', 'en', 'Keys are in my left pocket.', 'Anahtarlar sol cebimde.'),
  ('size', 'beden', 'clothes', 'beginner', 'en', 'What size shoes do you wear?', 'Kaç numara ayakkabı giyiyorsun?'),
  ('color', 'renk', 'clothes', 'beginner', 'en', 'Choose a color that suits you.', 'Sana uyan bir renk seç.'),
  ('fabric', 'kumaş', 'clothes', 'beginner', 'en', 'Cotton fabric breathes well.', 'Pamuk kumaş iyi nefes alır.'),
  ('laundry', 'çamaşır', 'clothes', 'beginner', 'en', 'Sort laundry by color.', 'Çamaşırı renge göre ayır.'),
  ('iron', 'ütü', 'clothes', 'beginner', 'en', 'Iron the shirt on low heat.', 'Gömleği düşük ısıda ütüle.'),
  ('wardrobe', 'gardırop', 'clothes', 'intermediate', 'en', 'Organize your wardrobe by season.', 'Gardırobunu mevsime göre düzenle.'),
  ('outfit', 'kıyafet kombinasyonu', 'clothes', 'intermediate', 'en', 'She planned her outfit for the event.', 'Etkinlik için kıyafet kombinasyonunu planladı.'),
  ('accessory', 'aksesuar', 'clothes', 'intermediate', 'en', 'A simple accessory completes the look.', 'Basit bir aksesuar görünümü tamamlar.'),
  ('tailor', 'terzi', 'clothes', 'intermediate', 'en', 'The tailor shortened the sleeves.', 'Terzi kolları kısalttı.'),
  ('alteration', 'düzeltme', 'clothes', 'intermediate', 'en', 'Minor alterations improve the fit.', 'Küçük düzeltmeler oturmayı iyileştirir.'),
  ('hem', 'paça', 'clothes', 'intermediate', 'en', 'The hem of the skirt was uneven.', 'Eteğin paçası düzgün değildi.'),
  ('seam', 'dikiş', 'clothes', 'intermediate', 'en', 'Check the seam for loose threads.', 'Dikişte gevşek iplikleri kontrol et.'),
  ('linen', 'keten', 'clothes', 'intermediate', 'en', 'Linen keeps you cool in heat.', 'Keten sıcakta serin tutar.'),
  ('wool', 'yün', 'clothes', 'intermediate', 'en', 'Wool sweaters shrink if washed hot.', 'Yün kazaklar sıcak yıkanırsa çeker.'),
  ('silk', 'ipek', 'clothes', 'intermediate', 'en', 'Silk feels smooth on the skin.', 'İpek ciltte pürüzsüz hissettirir.');
