INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('artist', 'sanatçı', 'jobs', 'beginner', 'en', 'The artist sold a painting online.', 'Sanatçı çevrimiçi bir tablo sattı.'),
  ('writer', 'yazar', 'jobs', 'beginner', 'en', 'The writer published a new novel.', 'Yazar yeni bir roman yayınladı.'),
  ('dentist', 'diş hekimi', 'jobs', 'beginner', 'en', 'I visit the dentist twice a year.', 'Yılda iki kez diş hekimine giderim.'),
  ('police officer', 'polis memuru', 'jobs', 'beginner', 'en', 'A police officer directed traffic.', 'Bir polis memuru trafiği yönlendirdi.'),
  ('firefighter', 'itfaiyeci', 'jobs', 'beginner', 'en', 'Firefighters rescued people from the fire.', 'İtfaiyeciler yangından insanları kurtardı.'),
  ('receptionist', 'resepsiyonist', 'jobs', 'beginner', 'en', 'The receptionist greeted every visitor.', 'Resepsiyonist her ziyaretçiyi karşıladı.'),
  ('manager', 'yönetici', 'jobs', 'beginner', 'en', 'Our manager holds weekly meetings.', 'Yöneticimiz haftalık toplantılar yapar.'),
  ('salesperson', 'satış elemanı', 'jobs', 'beginner', 'en', 'The salesperson helped me choose a laptop.', 'Satış elemanı dizüstü bilgisayar seçmeme yardım etti.'),
  ('barber', 'berber', 'jobs', 'beginner', 'en', 'I get a haircut at the barber every month.', 'Her ay berberde saç kestiririm.'),
  ('photographer', 'fotoğrafçı', 'jobs', 'beginner', 'en', 'The photographer captured the wedding.', 'Fotoğrafçı düğünü fotoğrafladı.'),
  ('journalist', 'gazeteci', 'jobs', 'beginner', 'en', 'The journalist wrote about local news.', 'Gazeteci yerel haberler hakkında yazdı.'),
  ('architect', 'mimar', 'jobs', 'beginner', 'en', 'An architect designed the new library.', 'Bir mimar yeni kütüphaneyi tasarladı.'),
  ('plumber', 'tesisatçı', 'jobs', 'beginner', 'en', 'We called a plumber for the leak.', 'Sızıntı için bir tesisatçı çağırdık.'),
  ('electrician', 'elektrikçi', 'jobs', 'beginner', 'en', 'The electrician rewired the kitchen.', 'Elektrikçi mutfağın kablolarını yeniledi.'),
  ('scientist', 'bilim insanı', 'jobs', 'beginner', 'en', 'The scientist published her research.', 'Bilim insanı araştırmasını yayınladı.'),
  ('translator', 'çevirmen', 'jobs', 'beginner', 'en', 'A translator helped at the meeting.', 'Toplantıda bir çevirmen yardım etti.'),
  ('overtime', 'fazla mesai', 'jobs', 'intermediate', 'en', 'Overtime pay is higher on holidays.', 'Tatillerde fazla mesai ücreti daha yüksektir.'),
  ('benefits', 'yan haklar', 'jobs', 'intermediate', 'en', 'The job offers health benefits.', 'İş sağlık yan hakları sunuyor.'),
  ('payroll', 'bordro', 'jobs', 'intermediate', 'en', 'Payroll runs on the last day of the month.', 'Bordro ayın son günü işlenir.'),
  ('onboarding', 'işe alıştırma', 'jobs', 'intermediate', 'en', 'Onboarding lasts two weeks here.', 'Burada işe alıştırma iki hafta sürer.'),
  ('probation', 'deneme süresi', 'jobs', 'intermediate', 'en', 'New hires have a three-month probation.', 'Yeni işe alınanların üç aylık deneme süresi vardır.'),
  ('performance review', 'performans değerlendirmesi', 'jobs', 'intermediate', 'en', 'My performance review is in December.', 'Performans değerlendirmem aralıkta.'),
  ('team lead', 'takım lideri', 'jobs', 'intermediate', 'en', 'The team lead assigns daily tasks.', 'Takım lideri günlük görevleri dağıtır.'),
  ('job description', 'iş tanımı', 'jobs', 'intermediate', 'en', 'Read the job description carefully.', 'İş tanımını dikkatlice oku.'),
  ('reference letter', 'referans mektubu', 'jobs', 'intermediate', 'en', 'She asked for a reference letter.', 'Referans mektubu istedi.'),
  ('networking', 'network kurma', 'jobs', 'intermediate', 'en', 'Networking opens new career paths.', 'Network kurma yeni kariyer yolları açar.'),
  ('cover letter', 'ön yazı', 'jobs', 'intermediate', 'en', 'Tailor your cover letter to each role.', 'Ön yazını her role göre uyarla.'),
  ('job fair', 'iş fuarı', 'jobs', 'intermediate', 'en', 'We met recruiters at a job fair.', 'Bir iş fuarında işe alım uzmanlarıyla tanıştık.'),
  ('contract', 'sözleşme', 'jobs', 'intermediate', 'en', 'Sign the contract after reading it.', 'Sözleşmeyi okuduktan sonra imzala.'),
  ('full-time', 'tam zamanlı', 'jobs', 'intermediate', 'en', 'She switched to a full-time role.', 'Tam zamanlı bir role geçti.'),
  ('part-time', 'yarı zamanlı', 'jobs', 'intermediate', 'en', 'He works part-time while studying.', 'Okurken yarı zamanlı çalışıyor.'),
  ('shift work', 'vardiyalı çalışma', 'jobs', 'intermediate', 'en', 'Shift work can disrupt sleep.', 'Vardiyalı çalışma uykuyu bozabilir.'),
  ('workplace', 'iş yeri', 'jobs', 'intermediate', 'en', 'Our workplace encourages feedback.', 'İş yerimiz geri bildirimi teşvik ediyor.'),
  ('HR department', 'insan kaynakları', 'jobs', 'intermediate', 'en', 'Contact HR about leave policy.', 'İzin politikası için insan kaynaklarına başvur.'),
  ('training session', 'eğitim oturumu', 'jobs', 'intermediate', 'en', 'A training session starts at nine.', 'Dokuzda bir eğitim oturumu başlıyor.'),
  ('mentorship', 'mentorluk', 'jobs', 'intermediate', 'en', 'Mentorship helped her grow quickly.', 'Mentorluk hızlı gelişmesine yardım etti.'),
  ('job security', 'iş güvencesi', 'jobs', 'intermediate', 'en', 'Job security matters to many workers.', 'İş güvencesi birçok çalışan için önemlidir.'),
  ('workplace safety', 'iş yeri güvenliği', 'jobs', 'intermediate', 'en', 'Workplace safety rules must be followed.', 'İş yeri güvenliği kurallarına uyulmalıdır.'),
  ('non-compete clause', 'rekabet yasağı maddesi', 'jobs', 'advanced', 'en', 'The non-compete clause lasts one year.', 'Rekabet yasağı maddesi bir yıl sürer.'),
  ('gig economy', 'gig ekonomisi', 'jobs', 'advanced', 'en', 'The gig economy offers flexible hours.', 'Gig ekonomisi esnek saatler sunar.');
