INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('umami', 'umami', 'foods', 'advanced', 'en', 'Mushrooms add umami to the broth.', 'Mantarlar et suyuna umami katar.'),
  ('emulsify', 'emülsiyon yapmak', 'foods', 'advanced', 'en', 'Emulsify oil and vinegar for dressing.', 'Sos için yağ ve sirkeyi emülsiyon yap.'),
  ('confit', 'confit', 'foods', 'advanced', 'en', 'Duck confit is slow-cooked in fat.', 'Ördek confit yağda yavaş pişirilir.'),
  ('sous vide', 'sous vide', 'foods', 'advanced', 'en', 'Sous vide keeps meat evenly cooked.', 'Sous vide eti eşit pişirir.'),
  ('molecular gastronomy', 'moleküler gastronomi', 'foods', 'advanced', 'en', 'Molecular gastronomy transforms textures.', 'Moleküler gastronomi dokuları dönüştürür.'),
  ('foodborne illness', 'gıda kaynaklı hastalık', 'foods', 'advanced', 'en', 'Proper storage prevents foodborne illness.', 'Doğru saklama gıda kaynaklı hastalığı önler.'),
  ('HACCP', 'HACCP', 'foods', 'advanced', 'en', 'Restaurants follow HACCP safety rules.', 'Restoranlar HACCP güvenlik kurallarını uygular.'),
  ('macronutrient', 'makro besin', 'foods', 'advanced', 'en', 'Athletes track each macronutrient closely.', 'Sporcular her makro besini yakından takip eder.'),
  ('micronutrient', 'mikro besin', 'foods', 'advanced', 'en', 'Leafy greens provide key micronutrients.', 'Yeşil yapraklı sebzeler önemli mikro besinler sağlar.'),
  ('glycemic index', 'glisemik indeks', 'foods', 'advanced', 'en', 'Foods with low glycemic index stabilize energy.', 'Düşük glisemik indeksli gıdalar enerjiyi dengeler.'),
  ('antioxidant', 'antioksidan', 'foods', 'advanced', 'en', 'Berries are rich in antioxidants.', 'Orman meyveleri antioksidan açısından zengindir.'),
  ('probiotic', 'probiyotik', 'foods', 'advanced', 'en', 'Probiotic foods support gut health.', 'Probiyotik gıdalar bağırsak sağlığını destekler.'),
  ('food insecurity', 'gıda güvensizliği', 'foods', 'advanced', 'en', 'Food insecurity rises during economic shocks.', 'Ekonomik şoklarda gıda güvensizliği artar.'),
  ('supply chain', 'tedarik zinciri', 'foods', 'advanced', 'en', 'Supply chain delays raised food prices.', 'Tedarik zinciri gecikmeleri gıda fiyatlarını artırdı.'),
  ('farm-to-table', 'çiftlikten sofraya', 'foods', 'advanced', 'en', 'Farm-to-table menus highlight local produce.', 'Çiftlikten sofraya menüler yerel ürünleri öne çıkarır.'),
  ('sustainable farming', 'sürdürülebilir tarım', 'foods', 'advanced', 'en', 'Sustainable farming protects soil health.', 'Sürdürülebilir tarım toprak sağlığını korur.'),
  ('food miles', 'gıda kilometresi', 'foods', 'advanced', 'en', 'Shorter food miles reduce emissions.', 'Daha kısa gıda kilometresi emisyonu azaltır.'),
  ('cross-contamination', 'çapraz bulaşma', 'foods', 'advanced', 'en', 'Separate boards to avoid cross-contamination.', 'Çapraz bulaşmayı önlemek için tahtaları ayır.'),
  ('pasteurization', 'pastörizasyon', 'foods', 'advanced', 'en', 'Pasteurization kills harmful bacteria in milk.', 'Pastörizasyon sütteki zararlı bakterileri öldürür.'),
  ('homogenization', 'homojenizasyon', 'foods', 'advanced', 'en', 'Homogenization keeps milk texture uniform.', 'Homojenizasyon süt dokusunu düzgün tutar.'),
  ('Maillard reaction', 'Maillard reaksiyonu', 'foods', 'advanced', 'en', 'The Maillard reaction browns roasted meat.', 'Maillard reaksiyonu kızarmış eti kahverengileştirir.'),
  ('dehydration', 'kurutma', 'foods', 'advanced', 'en', 'Dehydration preserves fruit for months.', 'Kurutma meyveyi aylarca korur.'),
  ('brining', 'salamura', 'foods', 'advanced', 'en', 'Brining keeps turkey moist while roasting.', 'Salamura hindiyi fırınlarken sulu tutar.'),
  ('reduction sauce', 'sos reduksiyonu', 'foods', 'advanced', 'en', 'A reduction sauce intensifies flavor.', 'Sos reduksiyonu lezzeti yoğunlaştırır.'),
  ('food fortification', 'gıda zenginleştirme', 'foods', 'advanced', 'en', 'Food fortification adds vitamins to flour.', 'Gıda zenginleştirme una vitamin ekler.'),
  ('ultra-processed', 'aşırı işlenmiş', 'foods', 'advanced', 'en', 'Ultra-processed snacks often hide excess salt.', 'Aşırı işlenmiş atıştırmalıklar genelde fazla tuz gizler.'),
  ('monoculture crop', 'tek tip ekin', 'foods', 'advanced', 'en', 'Monoculture crops increase pest risk.', 'Tek tip ekinler zararlı riskini artırır.'),
  ('food sovereignty', 'gıda egemenliği', 'foods', 'advanced', 'en', 'Communities seek food sovereignty through local farms.', 'Topluluklar yerel çiftliklerle gıda egemenliği arıyor.'),
  ('traceability', 'izlenebilirlik', 'foods', 'advanced', 'en', 'Traceability tracks meat from farm to store.', 'İzlenebilirlik eti çiftlikten dükkana takip eder.'),
  ('allergen labeling', 'alerjen etiketleme', 'foods', 'advanced', 'en', 'Allergen labeling lists nuts and dairy clearly.', 'Alerjen etiketleme kuruyemiş ve süt ürünlerini açıkça listeler.'),
  ('water', 'su', 'drinks', 'beginner', 'en', 'Drink water throughout the day.', 'Gün boyunca su iç.'),
  ('tea', 'çay', 'drinks', 'beginner', 'en', 'Turkish tea is served in small glasses.', 'Türk çayı küçük bardaklarda servis edilir.'),
  ('coffee', 'kahve', 'drinks', 'beginner', 'en', 'I need coffee to wake up.', 'Uyanmak için kahveye ihtiyacım var.'),
  ('milk', 'süt', 'drinks', 'beginner', 'en', 'Children drink milk for calcium.', 'Çocuklar kalsiyum için süt içer.'),
  ('juice', 'meyve suyu', 'drinks', 'beginner', 'en', 'Orange juice is popular at breakfast.', 'Portakal suyu kahvaltıda popülerdir.'),
  ('soda', 'gazlı içecek', 'drinks', 'beginner', 'en', 'Soda has a lot of sugar.', 'Gazlı içeceğin çok şekeri vardır.'),
  ('lemonade', 'limonata', 'drinks', 'beginner', 'en', 'Homemade lemonade tastes fresh.', 'Ev yapımı limonata taze tadılır.'),
  ('hot chocolate', 'sıcak çikolata', 'drinks', 'beginner', 'en', 'Hot chocolate warms cold evenings.', 'Sıcak çikolata soğuk akşamları ısıtır.'),
  ('smoothie', 'smoothie', 'drinks', 'beginner', 'en', 'Blend a banana smoothie for lunch.', 'Öğle yemeği için muzlu smoothie karıştır.'),
  ('beer', 'bira', 'drinks', 'beginner', 'en', 'He ordered a cold beer.', 'Soğuk bir bira sipariş etti.');
