INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('shirt', 'gömlek', 'clothes', 'beginner', 'en', 'He wore a clean white shirt.', 'Temiz beyaz bir gömlek giydi.'),
  ('pants', 'pantolon', 'clothes', 'beginner', 'en', 'These pants are too long.', 'Bu pantolon çok uzun.'),
  ('dress', 'elbise', 'clothes', 'beginner', 'en', 'She bought a blue dress.', 'Mavi bir elbise aldı.'),
  ('skirt', 'etek', 'clothes', 'beginner', 'en', 'The skirt has floral patterns.', 'Eteğin çiçek desenleri var.'),
  ('jacket', 'ceket', 'clothes', 'beginner', 'en', 'Take a jacket, it is windy.', 'Bir ceket al, rüzgarlı.'),
  ('coat', 'palto', 'clothes', 'beginner', 'en', 'Hang your coat by the door.', 'Paltonu kapının yanına as.'),
  ('shoes', 'ayakkabı', 'clothes', 'beginner', 'en', 'Comfortable shoes help on long walks.', 'Rahat ayakkabılar uzun yürüyüşlerde yardımcı olur.'),
  ('socks', 'çorap', 'clothes', 'beginner', 'en', 'I need warm socks for winter.', 'Kış için sıcak çoraplara ihtiyacım var.'),
  ('hat', 'şapka', 'clothes', 'beginner', 'en', 'Wear a hat in strong sun.', 'Güçlü güneşte şapka tak.'),
  ('scarf', 'atkı', 'clothes', 'beginner', 'en', 'A wool scarf keeps your neck warm.', 'Yün atkı boynunu sıcak tutar.'),
  ('gloves', 'eldiven', 'clothes', 'beginner', 'en', 'Put on gloves before going out.', 'Dışarı çıkmadan önce eldiven giy.'),
  ('belt', 'kemer', 'clothes', 'beginner', 'en', 'Tighten your belt one notch.', 'Kemerini bir delik sık.'),
  ('jeans', 'kot pantolon', 'clothes', 'beginner', 'en', 'Jeans are perfect for casual days.', 'Kot pantolon günlük günler için mükemmel.'),
  ('T-shirt', 'tişört', 'clothes', 'beginner', 'en', 'He packed a plain T-shirt.', 'Düz bir tişört paketledi.'),
  ('sweater', 'kazak', 'clothes', 'beginner', 'en', 'This sweater is soft and warm.', 'Bu kazak yumuşak ve sıcak.'),
  ('shorts', 'şort', 'clothes', 'beginner', 'en', 'Shorts are fine for the beach.', 'Şort plaj için uygundur.'),
  ('boots', 'bot', 'clothes', 'beginner', 'en', 'Wear boots in the rain.', 'Yağmurda bot giy.'),
  ('sandals', 'sandalet', 'clothes', 'beginner', 'en', 'Sandals are cool in summer heat.', 'Sandalet yaz sıcağında serindir.'),
  ('pajamas', 'pijama', 'clothes', 'beginner', 'en', 'Change into pajamas before bed.', 'Yatmadan önce pijamaya geç.'),
  ('underwear', 'iç çamaşırı', 'clothes', 'beginner', 'en', 'Pack extra underwear for the trip.', 'Gezi için fazladan iç çamaşırı koy.'),
  ('tie', 'kravat', 'clothes', 'beginner', 'en', 'He adjusted his tie before the meeting.', 'Toplantıdan önce kravatını düzeltti.'),
  ('suit', 'takım elbise', 'clothes', 'beginner', 'en', 'A dark suit looks formal.', 'Koyu takım elbise resmi görünür.'),
  ('button', 'düğme', 'clothes', 'beginner', 'en', 'A button fell off my coat.', 'Paltomdan bir düğme düştü.'),
  ('zipper', 'fermuar', 'clothes', 'beginner', 'en', 'The zipper stuck halfway.', 'Fermuar yarıda takıldı.'),
  ('pocket', 'cep', 'clothes', 'beginner', 'en', 'Keys are in my left pocket.', 'Anahtarlar sol cebimde.'),
  ('size', 'beden', 'clothes', 'beginner', 'en', 'What size shoes do you wear?', 'Kaç numara ayakkabı giyiyorsun?'),
  ('color', 'renk', 'clothes', 'beginner', 'en', 'Choose a color that suits you.', 'Sana uyan bir renk seç.'),
  ('fabric', 'kumaş', 'clothes', 'beginner', 'en', 'Cotton fabric breathes well.', 'Pamuk kumaş iyi nefes alır.'),
  ('laundry', 'çamaşır', 'clothes', 'beginner', 'en', 'Sort laundry by color.', 'Çamaşırı renge göre ayır.'),
  ('iron', 'ütü', 'clothes', 'beginner', 'en', 'Iron the shirt on low heat.', 'Gömleği düşük ısıda ütüle.'),
  ('wardrobe', 'gardırop', 'clothes', 'intermediate', 'en', 'Organize your wardrobe by season.', 'Gardırobunu mevsime göre düzenle.'),
  ('outfit', 'kıyafet kombinasyonu', 'clothes', 'intermediate', 'en', 'She planned her outfit for the event.', 'Etkinlik için kıyafet kombinasyonunu planladı.'),
  ('accessory', 'aksesuar', 'clothes', 'intermediate', 'en', 'A simple accessory completes the look.', 'Basit bir aksesuar görünümü tamamlar.'),
  ('tailor', 'terzi', 'clothes', 'intermediate', 'en', 'The tailor shortened the sleeves.', 'Terzi kolları kısalttı.'),
  ('alteration', 'düzeltme', 'clothes', 'intermediate', 'en', 'Minor alterations improve the fit.', 'Küçük düzeltmeler oturmayı iyileştirir.'),
  ('hem', 'paça', 'clothes', 'intermediate', 'en', 'The hem of the skirt was uneven.', 'Eteğin paçası düzgün değildi.'),
  ('seam', 'dikiş', 'clothes', 'intermediate', 'en', 'Check the seam for loose threads.', 'Dikişte gevşek iplikleri kontrol et.'),
  ('linen', 'keten', 'clothes', 'intermediate', 'en', 'Linen keeps you cool in heat.', 'Keten sıcakta serin tutar.'),
  ('wool', 'yün', 'clothes', 'intermediate', 'en', 'Wool sweaters shrink if washed hot.', 'Yün kazaklar sıcak yıkanırsa çeker.'),
  ('silk', 'ipek', 'clothes', 'intermediate', 'en', 'Silk feels smooth on the skin.', 'İpek ciltte pürüzsüz hissettirir.'),
  ('denim', 'denim', 'clothes', 'intermediate', 'en', 'Denim fades with frequent washing.', 'Denim sık yıkamayla soluyor.'),
  ('leather', 'deri', 'clothes', 'intermediate', 'en', 'Leather boots need regular care.', 'Deri botlar düzenli bakım gerektirir.'),
  ('waterproof', 'su geçirmez', 'clothes', 'intermediate', 'en', 'Buy a waterproof jacket for hiking.', 'Yürüyüş için su geçirmez ceket al.'),
  ('breathable', 'nefes alabilir', 'clothes', 'intermediate', 'en', 'Breathable fabrics reduce sweat.', 'Nefes alabilir kumaşlar terlemeyi azaltır.'),
  ('layering', 'katmanlama', 'clothes', 'intermediate', 'en', 'Layering works well in changing weather.', 'Katmanlama değişken havada iyi işler.'),
  ('business casual', 'iş günlük', 'clothes', 'intermediate', 'en', 'Business casual allows neat chinos.', 'İş günlük düzenli chino pantolonlara izin verir.'),
  ('formal wear', 'resmi kıyafet', 'clothes', 'intermediate', 'en', 'Formal wear is required at the gala.', 'Galada resmi kıyafet gereklidir.'),
  ('sportswear', 'spor giyim', 'clothes', 'intermediate', 'en', 'Sportswear dries quickly after workouts.', 'Spor giyim antrenman sonrası hızla kurur.'),
  ('fast fashion', 'hızlı moda', 'clothes', 'intermediate', 'en', 'Fast fashion creates textile waste.', 'Hızlı moda tekstil atığı oluşturur.'),
  ('sustainable fashion', 'sürdürülebilir moda', 'clothes', 'intermediate', 'en', 'Sustainable fashion uses ethical materials.', 'Sürdürülebilir moda etik malzemeler kullanır.'),
  ('secondhand', 'ikinci el', 'clothes', 'intermediate', 'en', 'Secondhand shops offer unique finds.', 'İkinci el dükkanlar benzersiz parçalar sunar.'),
  ('dry clean', 'kuru temizleme', 'clothes', 'intermediate', 'en', 'Dry clean the wool coat only.', 'Yün paltoyu sadece kuru temizle.'),
  ('stain', 'leke', 'clothes', 'intermediate', 'en', 'Treat the stain before it sets.', 'Leke oturmadan müdahale et.'),
  ('bleach', 'ağartıcı', 'clothes', 'intermediate', 'en', 'Do not bleach colored clothes.', 'Renkli kıyafetleri ağartma.'),
  ('detergent', 'deterjan', 'clothes', 'intermediate', 'en', 'Use mild detergent for delicates.', 'Hassas kumaşlar için hafif deterjan kullan.'),
  ('lint roller', 'tüy alıcı rulo', 'clothes', 'intermediate', 'en', 'A lint roller removes pet hair.', 'Tüy alıcı rulo evcil hayvan tüyünü temizler.'),
  ('measurement', 'ölçü', 'clothes', 'intermediate', 'en', 'Take accurate measurements before ordering.', 'Sipariş vermeden önce doğru ölçü al.'),
  ('unisex', 'unisex', 'clothes', 'intermediate', 'en', 'The brand released a unisex collection.', 'Marka unisex bir koleksiyon çıkardı.'),
  ('oversized', 'oversize', 'clothes', 'intermediate', 'en', 'Oversized hoodies feel cozy.', 'Oversize kapüşonlular rahat hissettirir.'),
  ('slim fit', 'slim fit', 'clothes', 'intermediate', 'en', 'Slim fit pants taper at the ankle.', 'Slim fit pantolon bilekte daralır.'),
  ('haute couture', 'haute couture', 'clothes', 'advanced', 'en', 'Haute couture pieces are made to order.', 'Haute couture parçalar sipariş üzerine yapılır.'),
  ('prêt-à-porter', 'hazır giyim', 'clothes', 'advanced', 'en', 'Prêt-à-porter lines reach wider markets.', 'Hazır giyim koleksiyonları daha geniş pazarlara ulaşır.'),
  ('capsule wardrobe', 'kapsül gardırop', 'clothes', 'advanced', 'en', 'A capsule wardrobe reduces daily choices.', 'Kapsül gardırop günlük seçimleri azaltır.'),
  ('textile engineering', 'tekstil mühendisliği', 'clothes', 'advanced', 'en', 'Textile engineering improves fabric durability.', 'Tekstil mühendisliği kumaş dayanıklılığını artırır.'),
  ('garment construction', 'giysi yapımı', 'clothes', 'advanced', 'en', 'Garment construction affects longevity.', 'Giysi yapımı ömrü etkiler.'),
  ('draping', 'drapaj', 'clothes', 'advanced', 'en', 'Designers use draping on mannequins.', 'Tasarımcılar mankenlerde drapaj kullanır.'),
  ('pattern grading', 'kalıp derecelendirme', 'clothes', 'advanced', 'en', 'Pattern grading scales sizes accurately.', 'Kalıp derecelendirme bedenleri doğru ölçekler.'),
  ('bias cut', 'çapraz kesim', 'clothes', 'advanced', 'en', 'Bias cut fabric drapes elegantly.', 'Çapraz kesim kumaş zarif dökülür.'),
  ('millinery', 'şapka yapımı', 'clothes', 'advanced', 'en', 'Millinery requires precise hand stitching.', 'Şapka yapımı hassas el dikişi gerektirir.'),
  ('colorfastness', 'renk haslığı', 'clothes', 'advanced', 'en', 'Test colorfastness before washing reds.', 'Kırmızıları yıkamadan önce renk haslığını test et.'),
  ('pilling', 'tüylenme', 'clothes', 'advanced', 'en', 'Cheap knits suffer from pilling.', 'Ucuz trikolar tüylenmeden muzdarip olur.'),
  ('moisture-wicking', 'nem emici', 'clothes', 'advanced', 'en', 'Moisture-wicking shirts dry fast during runs.', 'Nem emici tişörtler koşuda hızla kurur.'),
  ('Gore-Tex', 'Gore-Tex', 'clothes', 'advanced', 'en', 'Gore-Tex jackets block rain and wind.', 'Gore-Tex ceketler yağmur ve rüzgarı keser.'),
  ('ethical sourcing', 'etik tedarik', 'clothes', 'advanced', 'en', 'Ethical sourcing audits factory conditions.', 'Etik tedarik fabrika koşullarını denetler.'),
  ('circular fashion', 'döngüsel moda', 'clothes', 'advanced', 'en', 'Circular fashion recycles old garments.', 'Döngüsel moda eski giysileri geri dönüştürür.'),
  ('greenwashing', 'yeşil aklama', 'clothes', 'advanced', 'en', 'Some brands risk greenwashing claims.', 'Bazı markalar yeşil aklama iddiaları riski taşır.'),
  ('traceability', 'izlenebilirlik', 'clothes', 'advanced', 'en', 'Traceability tracks cotton from farm to shirt.', 'İzlenebilirlik pamuğu tarladan gömleğe takip eder.'),
  ('vegan leather', 'vegan deri', 'clothes', 'advanced', 'en', 'Vegan leather uses plant-based coatings.', 'Vegan deri bitki bazlı kaplamalar kullanır.'),
  ('upcycling', 'upcycling', 'clothes', 'advanced', 'en', 'Upcycling turns old jeans into bags.', 'Upcycling eski kotları çantaya dönüştürür.'),
  ('sartorial', 'giyimle ilgili', 'clothes', 'advanced', 'en', 'His sartorial taste favors classic cuts.', 'Giyim zevki klasik kesimleri tercih ediyor.'),
  ('proportional dressing', 'orantılı giyinme', 'clothes', 'advanced', 'en', 'Proportional dressing balances silhouette.', 'Orantılı giyinme silueti dengeler.'),
  ('monochrome styling', 'monokrom stil', 'clothes', 'advanced', 'en', 'Monochrome styling looks sleek and modern.', 'Monokrom stil şık ve modern görünür.'),
  ('archival fashion', 'arşiv modası', 'clothes', 'advanced', 'en', 'Collectors hunt rare archival fashion pieces.', 'Koleksiyoncular nadir arşiv modası parçalarını arar.'),
  ('fashion forecasting', 'moda öngörüsü', 'clothes', 'advanced', 'en', 'Fashion forecasting guides next season colors.', 'Moda öngörüsü gelecek sezon renklerini yönlendirir.'),
  ('lookbook', 'lookbook', 'clothes', 'advanced', 'en', 'The lookbook showcases the new line.', 'Lookbook yeni koleksiyonu sergiliyor.'),
  ('runway collection', 'podyum koleksiyonu', 'clothes', 'advanced', 'en', 'The runway collection debuted in Milan.', 'Podyum koleksiyonu Milano''da tanıtıldı.'),
  ('fashion merchandising', 'moda merchandising', 'clothes', 'advanced', 'en', 'Fashion merchandising plans store displays.', 'Moda merchandising mağaza vitrinlerini planlar.'),
  ('size inclusivity', 'beden kapsayıcılığı', 'clothes', 'advanced', 'en', 'Size inclusivity expands available ranges.', 'Beden kapsayıcılığı mevcut aralıkları genişletir.'),
  ('gender-neutral design', 'cinsiyetsiz tasarım', 'clothes', 'advanced', 'en', 'Gender-neutral design avoids rigid labels.', 'Cinsiyetsiz tasarım katı etiketlerden kaçınır.'),
  ('anti-fit philosophy', 'anti-fit felsefesi', 'clothes', 'advanced', 'en', 'Anti-fit philosophy rejects tight tailoring.', 'Anti-fit felsefesi dar terziliği reddeder.');