INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('adaptation strategy', 'uyum stratejisi', 'nature', 'advanced', 'en', 'Coastal cities need an adaptation strategy.', 'Kıyı şehirlerinin bir uyum stratejisine ihtiyacı var.'),
  ('biodiversity hotspot', 'biyoçeşitlilik noktası', 'nature', 'advanced', 'en', 'The region is a biodiversity hotspot.', 'Bölge bir biyoçeşitlilik noktasıdır.'),
  ('invasive species', 'istilacı tür', 'nature', 'advanced', 'en', 'Invasive species outcompete natives.', 'İstilacı türler yerli türlerle rekabet eder.'),
  ('phenology', 'fenoloji', 'nature', 'advanced', 'en', 'Phenology tracks seasonal biological events.', 'Fenoloji mevsimsel biyolojik olayları izler.'),
  ('symbiotic relationship', 'symbiyotik ilişki', 'nature', 'advanced', 'en', 'Lichens show a symbiotic relationship.', 'Likenler symbiyotik bir ilişki gösterir.'),
  ('watershed management', 'havza yönetimi', 'nature', 'advanced', 'en', 'Watershed management protects drinking water.', 'Havza yönetimi içme suyunu korur.'),
  ('rewilding', 'yeniden vahşileştirme', 'nature', 'advanced', 'en', 'Rewilding restores native predators.', 'Yeniden vahşileştirme yerli yırtıcıları geri getirir.'),
  ('net zero', 'net sıfır', 'nature', 'advanced', 'en', 'Many nations target net zero emissions.', 'Birçok ülke net sıfır emisyon hedefliyor.'),
  ('geoengineering', 'jeomühendislik', 'nature', 'advanced', 'en', 'Geoengineering raises ethical questions.', 'Jeomühendislik etik soruları gündeme getirir.'),
  ('intertidal zone', 'gelgit bölgesi', 'nature', 'advanced', 'en', 'Crabs thrive in the intertidal zone.', 'Yengeçler gelgit bölgesinde gelişir.'),
  ('old-growth forest', 'ilkel orman', 'nature', 'advanced', 'en', 'Old-growth forest stores vast carbon.', 'İlkel orman büyük miktarda karbon depolar.'),
  ('riparian buffer', 'kıyı tamponu', 'nature', 'advanced', 'en', 'A riparian buffer filters farm runoff.', 'Kıyı tamponu tarla akıntısını filtreler.'),
  ('ecological footprint', 'ekolojik ayak izi', 'nature', 'advanced', 'en', 'Urban lifestyles enlarge ecological footprint.', 'Kentsel yaşam tarzları ekolojik ayak izini büyütür.'),
  ('climate resilience', 'iklim dayanıklılığı', 'nature', 'advanced', 'en', 'Climate resilience plans protect coastal towns.', 'İklim dayanıklılığı planları kıyı kasabalarını korur.'),
  ('methane emissions', 'metan emisyonları', 'nature', 'advanced', 'en', 'Landfills release methane emissions.', 'Çöplükler metan emisyonları salar.'),
  ('photochemical smog', 'fotokimyasal duman', 'nature', 'advanced', 'en', 'Sunlight creates photochemical smog in cities.', 'Güneş ışığı şehirlerde fotokimyasal duman oluşturur.'),
  ('ecological indicator', 'ekolojik gösterge', 'nature', 'advanced', 'en', 'Frogs serve as an ecological indicator.', 'Kurbağalar ekolojik gösterge olarak işlev görür.'),
  ('transboundary pollution', 'sınır ötesi kirlilik', 'nature', 'advanced', 'en', 'Transboundary pollution crosses national borders.', 'Sınır ötesi kirlilik ulusal sınırları aşar.'),
  ('environmental stewardship', 'çevresel sorumluluk', 'nature', 'advanced', 'en', 'Environmental stewardship begins locally.', 'Çevresel sorumluluk yerelde başlar.'),
  ('planetary boundary', 'gezegen sınırı', 'nature', 'advanced', 'en', 'Scientists define key planetary boundaries.', 'Bilim insanları temel gezegen sınırlarını tanımlar.'),
  ('happy', 'mutlu', 'emotions', 'beginner', 'en', 'She felt happy after the good news.', 'İyi haberden sonra mutlu hissetti.'),
  ('sad', 'üzgün', 'emotions', 'beginner', 'en', 'He looked sad at the farewell.', 'Vedada üzgün görünüyordu.'),
  ('angry', 'kızgın', 'emotions', 'beginner', 'en', 'Do not speak when you are angry.', 'Kızgınken konuşma.'),
  ('scared', 'korkmuş', 'emotions', 'beginner', 'en', 'The child was scared of the dark.', 'Çocuk karanlıktan korkuyordu.'),
  ('excited', 'heyecanlı', 'emotions', 'beginner', 'en', 'We were excited about the trip.', 'Geziden heyecanlıydık.'),
  ('tired', 'yorgun', 'emotions', 'beginner', 'en', 'I am too tired to go out.', 'Dışarı çıkmak için çok yorgunum.'),
  ('nervous', 'gergin', 'emotions', 'beginner', 'en', 'She felt nervous before the exam.', 'Sınavdan önce gergin hissetti.'),
  ('calm', 'sakin', 'emotions', 'beginner', 'en', 'Deep breaths keep me calm.', 'Derin nefesler beni sakin tutar.'),
  ('proud', 'gururlu', 'emotions', 'beginner', 'en', 'Parents felt proud of their son.', 'Ebeveynler oğullarıyla gurur duydu.'),
  ('lonely', 'yalnız', 'emotions', 'beginner', 'en', 'He felt lonely in the new city.', 'Yeni şehirde yalnız hissetti.'),
  ('love', 'aşk', 'emotions', 'beginner', 'en', 'Love grows with trust and care.', 'Aşk güven ve ilgiyle büyür.'),
  ('hope', 'umut', 'emotions', 'beginner', 'en', 'Never lose hope during hard times.', 'Zor zamanlarda umudunu kaybetme.'),
  ('joy', 'sevinç', 'emotions', 'beginner', 'en', 'Their joy filled the whole room.', 'Sevinçleri tüm odayı doldurdu.'),
  ('fear', 'korku', 'emotions', 'beginner', 'en', 'Fear can stop you from trying.', 'Korku denemeni engelleyebilir.'),
  ('surprise', 'sürpriz', 'emotions', 'beginner', 'en', 'The party was a lovely surprise.', 'Parti güzel bir sürprizdi.'),
  ('worry', 'endişe', 'emotions', 'beginner', 'en', 'Worry keeps her awake at night.', 'Endişe onu gece uyutmayor.'),
  ('relief', 'rahatlama', 'emotions', 'beginner', 'en', 'Relief washed over him after the call.', 'Aramadan sonra rahatlama onu sardı.'),
  ('shame', 'utanç', 'emotions', 'beginner', 'en', 'Shame made her face turn red.', 'Utanç yüzünün kızarmasına neden oldu.'),
  ('guilt', 'suçluluk', 'emotions', 'beginner', 'en', 'He felt guilt after the argument.', 'Tartışmadan sonra suçluluk hissetti.'),
  ('jealous', 'kıskanç', 'emotions', 'beginner', 'en', 'She felt jealous of their success.', 'Başarılarına kıskançlık duydu.'),
  ('grateful', 'minnettar', 'emotions', 'beginner', 'en', 'I am grateful for your help.', 'Yardımın için minnettarım.'),
  ('bored', 'sıkılmış', 'emotions', 'beginner', 'en', 'The lecture made students bored.', 'Ders öğrencileri sıktı.'),
  ('confused', 'kafası karışık', 'emotions', 'beginner', 'en', 'New rules left him confused.', 'Yeni kurallar onu kafası karışık bıraktı.'),
  ('confident', 'kendinden emin', 'emotions', 'beginner', 'en', 'Practice made her more confident.', 'Pratik onu daha kendinden emin yaptı.'),
  ('shy', 'utangaç', 'emotions', 'beginner', 'en', 'The shy boy hid behind his mother.', 'Utangaç çocuk annesinin arkasına saklandı.'),
  ('curious', 'meraklı', 'emotions', 'beginner', 'en', 'Curious minds ask many questions.', 'Meraklı zihinler çok soru sorar.'),
  ('peaceful', 'huzurlu', 'emotions', 'beginner', 'en', 'The garden felt peaceful at dawn.', 'Bahçe şafakta huzurlu hissettiriyordu.'),
  ('hurt', 'incinmiş', 'emotions', 'beginner', 'en', 'Her words left him hurt.', 'Sözleri onu incitti.'),
  ('smile', 'gülümseme', 'emotions', 'beginner', 'en', 'A warm smile changed the mood.', 'Sıcak bir gülümseme havayı değiştirdi.'),
  ('cry', 'ağlamak', 'emotions', 'beginner', 'en', 'It is okay to cry sometimes.', 'Bazen ağlamak normaldir.'),
  ('anxious', 'kaygılı', 'emotions', 'intermediate', 'en', 'She felt anxious before the interview.', 'Görüşmeden önce kaygılı hissetti.'),
  ('frustrated', 'hayal kırıklığına uğramış', 'emotions', 'intermediate', 'en', 'Delays left commuters frustrated.', 'Gecikmeler yolcuları hayal kırıklığına uğrattı.'),
  ('embarrassed', 'mahcup', 'emotions', 'intermediate', 'en', 'He was embarrassed by his mistake.', 'Hatasından mahcup oldu.'),
  ('disappointed', 'hayal kırıklığına uğramış', 'emotions', 'intermediate', 'en', 'Fans were disappointed by the score.', 'Taraftarlar skordan hayal kırıklığına uğradı.'),
  ('overwhelmed', 'bunalmış', 'emotions', 'intermediate', 'en', 'Too many tasks left her overwhelmed.', 'Çok fazla görev onu bunaltı.'),
  ('content', 'memnun', 'emotions', 'intermediate', 'en', 'Simple routines keep him content.', 'Basit rutinler onu memnun tutuyor.'),
  ('nostalgic', 'nostaljik', 'emotions', 'intermediate', 'en', 'Old photos made her nostalgic.', 'Eski fotoğraflar onu nostaljik yaptı.'),
  ('optimistic', 'iyimser', 'emotions', 'intermediate', 'en', 'Stay optimistic despite setbacks.', 'Aksiliklere rağmen iyimser kal.'),
  ('pessimistic', 'kötümser', 'emotions', 'intermediate', 'en', 'Pessimistic thoughts drain energy.', 'Kötümser düşünceler enerjiyi tüketir.'),
  ('empathy', 'empati', 'emotions', 'intermediate', 'en', 'Empathy helps resolve conflicts.', 'Empati anlaşmazlıkları çözmeye yardım eder.'),
  ('sympathy', 'sempati', 'emotions', 'intermediate', 'en', 'They expressed sympathy for the family.', 'Aileye sempati gösterdiler.'),
  ('compassion', 'merhamet', 'emotions', 'intermediate', 'en', 'Compassion guides her volunteer work.', 'Merhamet gönüllü çalışmasını yönlendirir.'),
  ('resentment', 'kin', 'emotions', 'intermediate', 'en', 'Resentment grew after unfair treatment.', 'Adaletsiz muameleden sonra kin büyüdü.'),
  ('regret', 'pişmanlık', 'emotions', 'intermediate', 'en', 'He spoke with deep regret.', 'Derin pişmanlıkla konuştu.'),
  ('enthusiasm', 'heves', 'emotions', 'intermediate', 'en', 'Her enthusiasm inspired the team.', 'Hevesi takımı motive etti.'),
  ('motivation', 'motivasyon', 'emotions', 'intermediate', 'en', 'Clear goals boost motivation.', 'Net hedefler motivasyonu artırır.'),
  ('insecurity', 'güvensizlik', 'emotions', 'intermediate', 'en', 'Insecurity often hides behind anger.', 'Güvensizlik genelde öfkenin arkasında gizlenir.'),
  ('self-esteem', 'özgüven', 'emotions', 'intermediate', 'en', 'Praise can raise self-esteem.', 'Övgü özgüveni artırabilir.'),
  ('mood swing', 'ruh hali değişimi', 'emotions', 'intermediate', 'en', 'Lack of sleep causes mood swings.', 'Uyku eksikliği ruh hali değişimine neden olur.'),
  ('stress relief', 'stres giderme', 'emotions', 'intermediate', 'en', 'Walking offers quick stress relief.', 'Yürümek hızlı stres giderme sağlar.'),
  ('emotional support', 'duygusal destek', 'emotions', 'intermediate', 'en', 'Friends provide emotional support.', 'Arkadaşlar duygusal destek sağlar.'),
  ('heartbroken', 'kalbi kırık', 'emotions', 'intermediate', 'en', 'She felt heartbroken after the breakup.', 'Ayrılıktan sonra kalbi kırık hissetti.'),
  ('thrilled', 'coşkun', 'emotions', 'intermediate', 'en', 'They were thrilled to hear the news.', 'Haberi duyunca coşkundular.'),
  ('irritated', 'sinirli', 'emotions', 'intermediate', 'en', 'Noise from construction irritated neighbors.', 'İnşaat gürültüsü komşuları sinirlendirdi.'),
  ('gratitude', 'minnettarlık', 'emotions', 'intermediate', 'en', 'Gratitude improves daily outlook.', 'Minnettarlık günlük bakış açısını iyileştirir.'),
  ('patience', 'sabır', 'emotions', 'intermediate', 'en', 'Patience helps during long waits.', 'Sabır uzun beklemelerde yardımcı olur.'),
  ('envy', 'kıskançlık', 'emotions', 'intermediate', 'en', 'Envy can poison friendships.', 'Kıskançlık dostlukları zehirleyebilir.'),
  ('affection', 'sevgi', 'emotions', 'intermediate', 'en', 'Small gestures show affection.', 'Küçük jestler sevgiyi gösterir.'),
  ('melancholy', 'melankoli', 'emotions', 'intermediate', 'en', 'Rainy days bring a quiet melancholy.', 'Yağmurlu günler sessiz bir melankoli getirir.'),
  ('serenity', 'sükunet', 'emotions', 'intermediate', 'en', 'Meditation brought her serenity.', 'Meditasyon ona sükunet getirdi.'),
  ('catharsis', 'arınma', 'emotions', 'advanced', 'en', 'Writing offered a sense of catharsis.', 'Yazmak bir arınma hissi sundu.'),
  ('ambivalence', 'belirsizlik', 'emotions', 'advanced', 'en', 'She felt ambivalence about moving abroad.', 'Yurt dışına taşınma konusunda belirsizlik hissetti.'),
  ('euphoria', 'öfori', 'emotions', 'advanced', 'en', 'Victory brought a wave of euphoria.', 'Zafer bir öfori dalgası getirdi.'),
  ('despair', 'çaresizlik', 'emotions', 'advanced', 'en', 'Support pulled him out of despair.', 'Destek onu çaresizlikten çıkardı.'),
  ('existential dread', 'varoluşsal korku', 'emotions', 'advanced', 'en', 'Late nights sometimes trigger existential dread.', 'Geç saatler bazen varoluşsal korkuyu tetikler.'),
  ('cognitive dissonance', 'bilişsel çelişki', 'emotions', 'advanced', 'en', 'Cognitive dissonance follows conflicting beliefs.', 'Bilişsel çelişki çatışan inançları takip eder.'),
  ('emotional regulation', 'duygusal düzenleme', 'emotions', 'advanced', 'en', 'Therapy teaches emotional regulation skills.', 'Terapi duygusal düzenleme becerileri öğretir.'),
  ('alexithymia', 'alexithymia', 'emotions', 'advanced', 'en', 'Alexithymia makes feelings hard to name.', 'Alexithymia duyguları adlandırmayı zorlaştırır.'),
  ('rumination', 'sürekli düşünme', 'emotions', 'advanced', 'en', 'Rumination deepens anxiety over time.', 'Sürekli düşünme zamanla kaygıyı derinleştirir.'),
  ('affective empathy', 'duygusal empati', 'emotions', 'advanced', 'en', 'Affective empathy mirrors others'' pain.', 'Duygusal empati başkalarının acısını yansıtır.'),
  ('cognitive empathy', 'bilişsel empati', 'emotions', 'advanced', 'en', 'Cognitive empathy understands another perspective.', 'Bilişsel empati başka bir bakış açısını anlar.'),
  ('emotional labor', 'duygusal emek', 'emotions', 'advanced', 'en', 'Customer service involves heavy emotional labor.', 'Müşteri hizmetleri yoğun duygusal emek içerir.'),
  ('gaslighting', 'gaslighting', 'emotions', 'advanced', 'en', 'Gaslighting makes victims doubt reality.', 'Gaslighting kurbanların gerçeği sorgulamasına neden olur.'),
  ('trauma response', 'travma tepkisi', 'emotions', 'advanced', 'en', 'A loud bang triggered a trauma response.', 'Yüksek bir patlama travma tepkisini tetikledi.'),
  ('hypervigilance', 'aşırı tetikte olma', 'emotions', 'advanced', 'en', 'Hypervigilance exhausts the nervous system.', 'Aşırı tetikte olma sinir sistemini yorar.'),
  ('emotional numbness', 'duygusal uyuşukluk', 'emotions', 'advanced', 'en', 'Burnout can cause emotional numbness.', 'Tükenmişlik duygusal uyuşukluğa neden olabilir.'),
  ('schadenfreude', 'schadenfreude', 'emotions', 'advanced', 'en', 'Schadenfreude is pleasure in others'' misfortune.', 'Schadenfreude başkalarının talihsizliğinden zevk almaktır.'),
  ('sublimation', 'sublimasyon', 'emotions', 'advanced', 'en', 'Art can channel anger through sublimation.', 'Sanat öfkeyi sublimasyon yoluyla yönlendirebilir.'),
  ('projection', 'yansıtma', 'emotions', 'advanced', 'en', 'Projection blames others for inner feelings.', 'Yansıtma iç duyguları başkalarına yükler.'),
  ('emotional resilience', 'duygusal dayanıklılık', 'emotions', 'advanced', 'en', 'Emotional resilience grows with practice.', 'Duygusal dayanıklılık pratikle gelişir.');