INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('artist', 'sanatçı', 'jobs', 'beginner', 'en', 'The artist sold a painting online.', 'Sanatçı çevrimiçi bir tablo sattı.'),
  ('writer', 'yazar', 'jobs', 'beginner', 'en', 'The writer published a new novel.', 'Yazar yeni bir roman yayınladı.'),
  ('dentist', 'diş hekimi', 'jobs', 'beginner', 'en', 'I visit the dentist twice a year.', 'Yılda iki kez diş hekimine giderim.'),
  ('police officer', 'polis memuru', 'jobs', 'beginner', 'en', 'A police officer directed traffic.', 'Bir polis memuru trafiği yönlendirdi.'),
  ('firefighter', 'itfaiyeci', 'jobs', 'beginner', 'en', 'Firefighters rescued people from the fire.', 'İtfaiyeciler yangından insanları kurtardı.'),
  ('receptionist', 'resepsiyonist', 'jobs', 'beginner', 'en', 'The receptionist greeted every visitor.', 'Resepsiyonist her ziyaretçiyi karşıladı.'),
  ('manager', 'yönetici', 'jobs', 'beginner', 'en', 'Our manager holds weekly meetings.', 'Yöneticimiz haftalık toplantılar yapar.'),
  ('salesperson', 'satış elemanı', 'jobs', 'beginner', 'en', 'The salesperson helped me choose a laptop.', 'Satış elemanı dizüstü bilgisayar seçmeme yardım etti.'),
  ('barber', 'berber', 'jobs', 'beginner', 'en', 'I get a haircut at the barber every month.', 'Her ay berberde saç kestiririm.'),
  ('photographer', 'fotoğrafçı', 'jobs', 'beginner', 'en', 'The photographer captured the wedding.', 'Fotoğrafçı düğünü fotoğrafladı.'),
  ('journalist', 'gazeteci', 'jobs', 'beginner', 'en', 'The journalist wrote about local news.', 'Gazeteci yerel haberler hakkında yazdı.'),
  ('architect', 'mimar', 'jobs', 'beginner', 'en', 'An architect designed the new library.', 'Bir mimar yeni kütüphaneyi tasarladı.'),
  ('plumber', 'tesisatçı', 'jobs', 'beginner', 'en', 'We called a plumber for the leak.', 'Sızıntı için bir tesisatçı çağırdık.'),
  ('electrician', 'elektrikçi', 'jobs', 'beginner', 'en', 'The electrician rewired the kitchen.', 'Elektrikçi mutfağın kablolarını yeniledi.'),
  ('scientist', 'bilim insanı', 'jobs', 'beginner', 'en', 'The scientist published her research.', 'Bilim insanı araştırmasını yayınladı.'),
  ('translator', 'çevirmen', 'jobs', 'beginner', 'en', 'A translator helped at the meeting.', 'Toplantıda bir çevirmen yardım etti.'),
  ('overtime', 'fazla mesai', 'jobs', 'intermediate', 'en', 'Overtime pay is higher on holidays.', 'Tatillerde fazla mesai ücreti daha yüksektir.'),
  ('benefits', 'yan haklar', 'jobs', 'intermediate', 'en', 'The job offers health benefits.', 'İş sağlık yan hakları sunuyor.'),
  ('payroll', 'bordro', 'jobs', 'intermediate', 'en', 'Payroll runs on the last day of the month.', 'Bordro ayın son günü işlenir.'),
  ('onboarding', 'işe alıştırma', 'jobs', 'intermediate', 'en', 'Onboarding lasts two weeks here.', 'Burada işe alıştırma iki hafta sürer.'),
  ('probation', 'deneme süresi', 'jobs', 'intermediate', 'en', 'New hires have a three-month probation.', 'Yeni işe alınanların üç aylık deneme süresi vardır.'),
  ('performance review', 'performans değerlendirmesi', 'jobs', 'intermediate', 'en', 'My performance review is in December.', 'Performans değerlendirmem aralıkta.'),
  ('team lead', 'takım lideri', 'jobs', 'intermediate', 'en', 'The team lead assigns daily tasks.', 'Takım lideri günlük görevleri dağıtır.'),
  ('job description', 'iş tanımı', 'jobs', 'intermediate', 'en', 'Read the job description carefully.', 'İş tanımını dikkatlice oku.'),
  ('reference letter', 'referans mektubu', 'jobs', 'intermediate', 'en', 'She asked for a reference letter.', 'Referans mektubu istedi.'),
  ('networking', 'network kurma', 'jobs', 'intermediate', 'en', 'Networking opens new career paths.', 'Network kurma yeni kariyer yolları açar.'),
  ('cover letter', 'ön yazı', 'jobs', 'intermediate', 'en', 'Tailor your cover letter to each role.', 'Ön yazını her role göre uyarla.'),
  ('job fair', 'iş fuarı', 'jobs', 'intermediate', 'en', 'We met recruiters at a job fair.', 'Bir iş fuarında işe alım uzmanlarıyla tanıştık.'),
  ('contract', 'sözleşme', 'jobs', 'intermediate', 'en', 'Sign the contract after reading it.', 'Sözleşmeyi okuduktan sonra imzala.'),
  ('full-time', 'tam zamanlı', 'jobs', 'intermediate', 'en', 'She switched to a full-time role.', 'Tam zamanlı bir role geçti.'),
  ('part-time', 'yarı zamanlı', 'jobs', 'intermediate', 'en', 'He works part-time while studying.', 'Okurken yarı zamanlı çalışıyor.'),
  ('shift work', 'vardiyalı çalışma', 'jobs', 'intermediate', 'en', 'Shift work can disrupt sleep.', 'Vardiyalı çalışma uykuyu bozabilir.'),
  ('workplace', 'iş yeri', 'jobs', 'intermediate', 'en', 'Our workplace encourages feedback.', 'İş yerimiz geri bildirimi teşvik ediyor.'),
  ('HR department', 'insan kaynakları', 'jobs', 'intermediate', 'en', 'Contact HR about leave policy.', 'İzin politikası için insan kaynaklarına başvur.'),
  ('training session', 'eğitim oturumu', 'jobs', 'intermediate', 'en', 'A training session starts at nine.', 'Dokuzda bir eğitim oturumu başlıyor.'),
  ('mentorship', 'mentorluk', 'jobs', 'intermediate', 'en', 'Mentorship helped her grow quickly.', 'Mentorluk hızlı gelişmesine yardım etti.'),
  ('job security', 'iş güvencesi', 'jobs', 'intermediate', 'en', 'Job security matters to many workers.', 'İş güvencesi birçok çalışan için önemlidir.'),
  ('workplace safety', 'iş yeri güvenliği', 'jobs', 'intermediate', 'en', 'Workplace safety rules must be followed.', 'İş yeri güvenliği kurallarına uyulmalıdır.'),
  ('non-compete clause', 'rekabet yasağı maddesi', 'jobs', 'advanced', 'en', 'The non-compete clause lasts one year.', 'Rekabet yasağı maddesi bir yıl sürer.'),
  ('gig economy', 'gig ekonomisi', 'jobs', 'advanced', 'en', 'The gig economy offers flexible hours.', 'Gig ekonomisi esnek saatler sunar.'),
  ('intellectual property', 'fikri mülkiyet', 'jobs', 'advanced', 'en', 'Contracts define intellectual property rights.', 'Sözleşmeler fikri mülkiyet haklarını tanımlar.'),
  ('due diligence', 'durum tespiti', 'jobs', 'advanced', 'en', 'Investors perform due diligence before funding.', 'Yatırımcılar fonlamadan önce durum tespiti yapar.'),
  ('corporate governance', 'kurumsal yönetim', 'jobs', 'advanced', 'en', 'Strong corporate governance builds trust.', 'Güçlü kurumsal yönetim güven oluşturur.'),
  ('succession planning', 'halefiyet planlaması', 'jobs', 'advanced', 'en', 'Succession planning prepares future leaders.', 'Halefiyet planlaması gelecek liderleri hazırlar.'),
  ('organizational culture', 'örgüt kültürü', 'jobs', 'advanced', 'en', 'Organizational culture shapes daily behavior.', 'Örgüt kültürü günlük davranışı şekillendirir.'),
  ('KPI', 'KPI', 'jobs', 'advanced', 'en', 'Managers track KPIs every quarter.', 'Yöneticiler her çeyrek KPI''ları takip eder.'),
  ('stakeholder', 'paydaş', 'jobs', 'advanced', 'en', 'Stakeholders approved the merger plan.', 'Paydaşlar birleşme planını onayladı.'),
  ('merger', 'birleşme', 'jobs', 'advanced', 'en', 'The merger created a larger company.', 'Birleşme daha büyük bir şirket oluşturdu.'),
  ('acquisition', 'satın alma', 'jobs', 'advanced', 'en', 'The acquisition expanded market share.', 'Satın alma pazar payını genişletti.'),
  ('downsizing', 'küçülme', 'jobs', 'advanced', 'en', 'Downsizing eliminated several departments.', 'Küçülme birkaç departmanı kaldırdı.'),
  ('restructuring', 'yeniden yapılandırma', 'jobs', 'advanced', 'en', 'Restructuring aimed to cut overhead.', 'Yeniden yapılandırma genel giderleri kesmeyi hedefledi.'),
  ('equity stake', 'hisse payı', 'jobs', 'advanced', 'en', 'Founders kept a large equity stake.', 'Kurucular büyük bir hisse payını tuttu.'),
  ('vesting schedule', 'hak kazanma takvimi', 'jobs', 'advanced', 'en', 'The vesting schedule spans four years.', 'Hak kazanma takvimi dört yıl sürer.'),
  ('non-disclosure agreement', 'gizlilik sözleşmesi', 'jobs', 'advanced', 'en', 'Employees signed a non-disclosure agreement.', 'Çalışanlar gizlilik sözleşmesi imzaladı.'),
  ('arbitration', 'tahkim', 'jobs', 'advanced', 'en', 'The contract requires arbitration for disputes.', 'Sözleşme anlaşmazlıklar için tahkim gerektirir.'),
  ('compliance officer', 'uyum görevlisi', 'jobs', 'advanced', 'en', 'The compliance officer audits internal rules.', 'Uyum görevlisi iç kuralları denetler.'),
  ('occupational hazard', 'mesleki tehlike', 'jobs', 'advanced', 'en', 'Construction has many occupational hazards.', 'İnşaatın birçok mesleki tehlikesi vardır.'),
  ('glass ceiling', 'cam tavan', 'jobs', 'advanced', 'en', 'She broke the glass ceiling in her firm.', 'Firmasında cam tavanı kırdı.'),
  ('pay gap', 'ücret farkı', 'jobs', 'advanced', 'en', 'Reports highlight the gender pay gap.', 'Raporlar cinsiyet ücret farkını vurguluyor.'),
  ('industrial action', 'sendikal eylem', 'jobs', 'advanced', 'en', 'Industrial action delayed production.', 'Sendikal eylem üretimi geciktirdi.'),
  ('apple', 'elma', 'foods', 'beginner', 'en', 'I eat an apple every morning.', 'Her sabah bir elma yerim.'),
  ('bread', 'ekmek', 'foods', 'beginner', 'en', 'Fresh bread smells wonderful.', 'Taze ekmek harika kokuyor.'),
  ('cheese', 'peynir', 'foods', 'beginner', 'en', 'She added cheese to the sandwich.', 'Sandviçe peynir ekledi.'),
  ('egg', 'yumurta', 'foods', 'beginner', 'en', 'Boil the eggs for eight minutes.', 'Yumurtaları sekiz dakika haşla.'),
  ('rice', 'pirinç', 'foods', 'beginner', 'en', 'We serve rice with grilled chicken.', 'Izgara tavukla pirinç servis ediyoruz.'),
  ('chicken', 'tavuk', 'foods', 'beginner', 'en', 'Roast chicken is my favorite meal.', 'Fırın tavuk en sevdiğim yemek.'),
  ('fish', 'balık', 'foods', 'beginner', 'en', 'Grilled fish is healthy and light.', 'Izgara balık sağlıklı ve hafiftir.'),
  ('tomato', 'domates', 'foods', 'beginner', 'en', 'Slice the tomato for the salad.', 'Salata için domatesi dilimle.'),
  ('potato', 'patates', 'foods', 'beginner', 'en', 'Mashed potato goes well with steak.', 'Patates püresi biftekle iyi gider.'),
  ('onion', 'soğan', 'foods', 'beginner', 'en', 'Chop the onion finely.', 'Soğanı ince doğra.'),
  ('carrot', 'havuç', 'foods', 'beginner', 'en', 'Carrots are rich in vitamins.', 'Havuç vitamin açısından zengindir.'),
  ('banana', 'muz', 'foods', 'beginner', 'en', 'A banana is a quick snack.', 'Muz hızlı bir atıştırmalıktır.'),
  ('orange', 'portakal', 'foods', 'beginner', 'en', 'Squeeze fresh orange juice.', 'Taze portakal suyu sık.'),
  ('grape', 'üzüm', 'foods', 'beginner', 'en', 'These grapes are very sweet.', 'Bu üzümler çok tatlı.'),
  ('strawberry', 'çilek', 'foods', 'beginner', 'en', 'Strawberries taste best in summer.', 'Çilekler yazın en iyi tadılır.'),
  ('watermelon', 'karpuz', 'foods', 'beginner', 'en', 'Watermelon is refreshing on hot days.', 'Karpuz sıcak günlerde ferahlatıcıdır.'),
  ('lemon', 'limon', 'foods', 'beginner', 'en', 'Add lemon to the tea.', 'Çaya limon ekle.'),
  ('garlic', 'sarımsak', 'foods', 'beginner', 'en', 'Garlic gives the soup more flavor.', 'Sarımsak çorbaya daha fazla lezzet verir.'),
  ('pepper', 'biber', 'foods', 'beginner', 'en', 'Red pepper adds color to the dish.', 'Kırmızı biber yemeğe renk katar.'),
  ('salt', 'tuz', 'foods', 'beginner', 'en', 'Add a pinch of salt.', 'Bir tutam tuz ekle.'),
  ('sugar', 'şeker', 'foods', 'beginner', 'en', 'Too much sugar is unhealthy.', 'Çok şeker sağlıksızdır.'),
  ('butter', 'tereyağı', 'foods', 'beginner', 'en', 'Spread butter on warm toast.', 'Sıcak tostun üzerine tereyağı sür.'),
  ('yogurt', 'yoğurt', 'foods', 'beginner', 'en', 'Greek yogurt is thick and creamy.', 'Yunan yoğurdu koyu ve kremalıdır.'),
  ('honey', 'bal', 'foods', 'beginner', 'en', 'Honey sweetens tea naturally.', 'Bal çayı doğal olarak tatlandırır.'),
  ('olive oil', 'zeytinyağı', 'foods', 'beginner', 'en', 'Drizzle olive oil over the salad.', 'Salatanın üzerine zeytinyağı gezdir.'),
  ('pasta', 'makarna', 'foods', 'beginner', 'en', 'We cook pasta for dinner tonight.', 'Bu akşam akşam yemeği için makarna pişiriyoruz.'),
  ('soup', 'çorba', 'foods', 'beginner', 'en', 'Hot soup warms you in winter.', 'Sıcak çorba kışın ısıtır.'),
  ('salad', 'salata', 'foods', 'beginner', 'en', 'A green salad is light and fresh.', 'Yeşil salata hafif ve tazedir.'),
  ('meat', 'et', 'foods', 'beginner', 'en', 'They avoid red meat for health.', 'Sağlık için kırmızı etten kaçınıyorlar.'),
  ('lentil', 'mercimek', 'foods', 'beginner', 'en', 'Lentil soup is popular here.', 'Mercimek çorbası burada popülerdir.'),
  ('appetizer', 'meze', 'foods', 'intermediate', 'en', 'We ordered appetizers before the main course.', 'Ana yemekten önce meze sipariş ettik.'),
  ('marinate', 'marine etmek', 'foods', 'intermediate', 'en', 'Marinate the meat overnight.', 'Eti bir gece marine et.'),
  ('seasoning', 'baharat', 'foods', 'intermediate', 'en', 'Use seasoning sparingly at first.', 'Başta baharatı az kullan.'),
  ('gluten-free', 'glütensiz', 'foods', 'intermediate', 'en', 'This bakery sells gluten-free bread.', 'Bu fırın glütensiz ekmek satıyor.'),
  ('organic', 'organik', 'foods', 'intermediate', 'en', 'Organic vegetables cost a bit more.', 'Organik sebzeler biraz daha pahalı.'),
  ('preservative', 'koruyucu madde', 'foods', 'intermediate', 'en', 'Check labels for preservatives.', 'Etiketlerde koruyucu maddeleri kontrol et.'),
  ('fermentation', 'fermentasyon', 'foods', 'intermediate', 'en', 'Fermentation gives yogurt its tang.', 'Fermentasyon yoğurda ekşiliğini verir.'),
  ('pastry', 'hamur işi', 'foods', 'intermediate', 'en', 'The pastry was flaky and buttery.', 'Hamur işi gevrek ve tereyağlıydı.'),
  ('grill', 'ızgara', 'foods', 'intermediate', 'en', 'Grill the vegetables until tender.', 'Sebzeleri yumuşayana kadar ızgarada pişir.'),
  ('simmer', 'kısık ateşte pişirmek', 'foods', 'intermediate', 'en', 'Simmer the sauce for twenty minutes.', 'Sosu yirmi dakika kısık ateşte pişir.');