INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('friend', 'arkadaş', 'relationships', 'beginner', 'en', 'She is my closest friend.', 'O en yakın arkadaşım.'),
  ('family', 'aile', 'relationships', 'beginner', 'en', 'Family dinners happen every Sunday.', 'Aile yemekleri her pazar olur.'),
  ('mother', 'anne', 'relationships', 'beginner', 'en', 'My mother calls me every week.', 'Annem beni her hafta arar.'),
  ('father', 'baba', 'relationships', 'beginner', 'en', 'His father taught him to ride a bike.', 'Babası ona bisiklete binmeyi öğretti.'),
  ('sister', 'kız kardeş', 'relationships', 'beginner', 'en', 'My sister lives in another city.', 'Kız kardeşim başka bir şehirde yaşıyor.'),
  ('brother', 'erkek kardeş', 'relationships', 'beginner', 'en', 'My brother plays guitar well.', 'Erkek kardeşim iyi gitar çalar.'),
  ('son', 'oğul', 'relationships', 'beginner', 'en', 'Their son starts school this year.', 'Oğulları bu yıl okula başlıyor.'),
  ('daughter', 'kız evlat', 'relationships', 'beginner', 'en', 'Their daughter loves painting.', 'Kız evlatları resim yapmayı seviyor.'),
  ('husband', 'koca', 'relationships', 'beginner', 'en', 'Her husband cooks on weekends.', 'Kocası hafta sonları yemek yapar.'),
  ('wife', 'eş', 'relationships', 'beginner', 'en', 'His wife works as a nurse.', 'Eşi hemşire olarak çalışıyor.'),
  ('baby', 'bebek', 'relationships', 'beginner', 'en', 'The baby slept through the night.', 'Bebek gece boyunca uyudu.'),
  ('grandmother', 'büyükanne', 'relationships', 'beginner', 'en', 'Grandmother told us old stories.', 'Büyükanne bize eski hikayeler anlattı.'),
  ('grandfather', 'büyükbaba', 'relationships', 'beginner', 'en', 'Grandfather walks in the park daily.', 'Büyükbaba her gün parkta yürür.'),
  ('uncle', 'amca/dayı', 'relationships', 'beginner', 'en', 'My uncle visited from abroad.', 'Amcam yurt dışından ziyarete geldi.'),
  ('aunt', 'teyze/hala', 'relationships', 'beginner', 'en', 'Aunt Mary baked a cake for us.', 'Teyze Mary bize kek yaptı.'),
  ('cousin', 'kuzen', 'relationships', 'beginner', 'en', 'We played with cousins at the reunion.', 'Buluşmada kuzenlerle oynadık.'),
  ('neighbor', 'komşu', 'relationships', 'beginner', 'en', 'Our neighbor watered our plants.', 'Komşumuz bitkilerimizi suladı.'),
  ('partner', 'partner', 'relationships', 'beginner', 'en', 'She introduced her partner to us.', 'Partnerini bize tanıttı.'),
  ('boyfriend', 'erkek arkadaş', 'relationships', 'beginner', 'en', 'Her boyfriend sent flowers.', 'Erkek arkadaşı çiçek gönderdi.'),
  ('girlfriend', 'kız arkadaş', 'relationships', 'beginner', 'en', 'His girlfriend studies medicine.', 'Kız arkadaşı tıp okuyor.'),
  ('classmate', 'sınıf arkadaşı', 'relationships', 'beginner', 'en', 'A classmate helped with homework.', 'Bir sınıf arkadaşı ev ödevinde yardım etti.'),
  ('colleague', 'iş arkadaşı', 'relationships', 'beginner', 'en', 'Colleagues joined the celebration.', 'İş arkadaşları kutlamaya katıldı.'),
  ('trust', 'güven', 'relationships', 'beginner', 'en', 'Trust is the base of friendship.', 'Güven dostluğun temelidir.'),
  ('love', 'sevgi', 'relationships', 'beginner', 'en', 'They show love through small acts.', 'Küçük davranışlarla sevgi gösteriyorlar.'),
  ('respect', 'saygı', 'relationships', 'beginner', 'en', 'Respect each other''s opinions.', 'Birbirinizin görüşlerine saygı gösterin.'),
  ('support', 'destek', 'relationships', 'beginner', 'en', 'Friends offer support in hard times.', 'Arkadaşlar zor zamanlarda destek sunar.'),
  ('argument', 'tartışma', 'relationships', 'beginner', 'en', 'They had a small argument yesterday.', 'Dün küçük bir tartışma yaşadılar.'),
  ('apology', 'özür', 'relationships', 'beginner', 'en', 'A sincere apology heals hurt feelings.', 'Samimi bir özür incinen duyguları iyileştirir.'),
  ('gift', 'hediye', 'relationships', 'beginner', 'en', 'She gave a thoughtful gift.', 'Düşünceli bir hediye verdi.'),
  ('invitation', 'davet', 'relationships', 'beginner', 'en', 'We sent an invitation to neighbors.', 'Komşulara davet gönderdik.'),
  ('relationship', 'ilişki', 'relationships', 'intermediate', 'en', 'Healthy relationships need communication.', 'Sağlıklı ilişkiler iletişim gerektirir.'),
  ('commitment', 'bağlılık', 'relationships', 'intermediate', 'en', 'Commitment grows over shared experiences.', 'Bağlılık paylaşılan deneyimlerle büyür.'),
  ('breakup', 'ayrılık', 'relationships', 'intermediate', 'en', 'The breakup was painful but necessary.', 'Ayrılık acı vericiydi ama gerekliydi.'),
  ('reconciliation', 'barışma', 'relationships', 'intermediate', 'en', 'Reconciliation took honest conversations.', 'Barışma dürüst konuşmalar gerektirdi.'),
  ('long-distance', 'uzak mesafe', 'relationships', 'intermediate', 'en', 'Long-distance couples schedule video calls.', 'Uzak mesafe çiftler görüntülü arama planlar.'),
  ('boundaries', 'sınırlar', 'relationships', 'intermediate', 'en', 'Clear boundaries protect mental health.', 'Net sınırlar ruh sağlığını korur.'),
  ('compromise', 'uzlaşma', 'relationships', 'intermediate', 'en', 'Marriage often requires compromise.', 'Evlilik genelde uzlaşma gerektirir.'),
  ('intimacy', 'yakınlık', 'relationships', 'intermediate', 'en', 'Emotional intimacy builds slowly.', 'Duygusal yakınlık yavaşça oluşur.'),
  ('jealousy', 'kıskançlık', 'relationships', 'intermediate', 'en', 'Jealousy can damage trust quickly.', 'Kıskançlık güveni hızla zedeleyebilir.'),
  ('forgiveness', 'affetme', 'relationships', 'intermediate', 'en', 'Forgiveness does not erase memory.', 'Affetme hafızayı silmez.'),
  ('loyalty', 'sadakat', 'relationships', 'intermediate', 'en', 'Loyalty shows in difficult moments.', 'Sadakat zor anlarda görülür.'),
  ('misunderstanding', 'yanlış anlama', 'relationships', 'intermediate', 'en', 'A misunderstanding caused the fight.', 'Yanlış anlama kavgaya neden oldu.'),
  ('family gathering', 'aile buluşması', 'relationships', 'intermediate', 'en', 'The family gathering lasted all day.', 'Aile buluşması bütün gün sürdü.'),
  ('in-laws', 'kayınvalide/kayınpeder', 'relationships', 'intermediate', 'en', 'She gets along well with her in-laws.', 'Kayınvalide ve kayınpederiyle iyi anlaşıyor.'),
  ('stepparent', 'üvey ebeveyn', 'relationships', 'intermediate', 'en', 'A stepparent joined the family last year.', 'Geçen yıl bir üvey ebeveyn aileye katıldı.'),
  ('blended family', 'karma aile', 'relationships', 'intermediate', 'en', 'A blended family needs patience and rules.', 'Karma aile sabır ve kurallar gerektirir.'),
  ('single parent', 'bekar ebeveyn', 'relationships', 'intermediate', 'en', 'Single parents juggle work and childcare.', 'Bekar ebeveynler iş ve çocuk bakımını dengeler.'),
  ('co-parenting', 'ortak ebeveynlik', 'relationships', 'intermediate', 'en', 'Co-parenting works with clear schedules.', 'Ortak ebeveynlik net programlarla işler.'),
  ('engagement', 'nişan', 'relationships', 'intermediate', 'en', 'They announced their engagement online.', 'Nişanlarını çevrimiçi duyurdular.'),
  ('household chores', 'ev işleri', 'relationships', 'intermediate', 'en', 'Share household chores fairly.', 'Ev işlerini adil paylaşın.'),
  ('quality time', 'kaliteli zaman', 'relationships', 'intermediate', 'en', 'Quality time matters more than gifts.', 'Kaliteli zaman hediyelerden daha önemlidir.'),
  ('active listening', 'aktif dinleme', 'relationships', 'intermediate', 'en', 'Active listening prevents many fights.', 'Aktif dinleme birçok kavgayı önler.'),
  ('conflict resolution', 'çatışma çözümü', 'relationships', 'intermediate', 'en', 'Conflict resolution skills help couples.', 'Çatışma çözümü becerileri çiftlere yardım eder.'),
  ('trust issue', 'güven sorunu', 'relationships', 'intermediate', 'en', 'Past lies created a trust issue.', 'Geçmiş yalanlar güven sorunu yarattı.'),
  ('social circle', 'sosyal çevre', 'relationships', 'intermediate', 'en', 'Her social circle changed after moving.', 'Taşındıktan sonra sosyal çevresi değişti.'),
  ('mentor', 'mentor', 'relationships', 'intermediate', 'en', 'A mentor guided his early career.', 'Bir mentor erken kariyerinde yol gösterdi.'),
  ('acquaintance', 'tanıdık', 'relationships', 'intermediate', 'en', 'An acquaintance introduced them.', 'Bir tanıdık onları tanıştırdı.'),
  ('best friend', 'en iyi arkadaş', 'relationships', 'intermediate', 'en', 'My best friend knows all my secrets.', 'En iyi arkadaşım tüm sırlarımı biliyor.'),
  ('roommate', 'ev arkadaşı', 'relationships', 'intermediate', 'en', 'Roommates split rent and bills.', 'Ev arkadaşları kira ve faturaları paylaşır.'),
  ('pen pal', 'mektup arkadaşı', 'relationships', 'intermediate', 'en', 'She kept a pen pal for years.', 'Yıllarca bir mektup arkadaşı tuttu.'),
  ('attachment style', 'bağlanma stili', 'relationships', 'advanced', 'en', 'Attachment style shapes adult relationships.', 'Bağlanma stili yetişkin ilişkilerini şekillendirir.'),
  ('secure attachment', 'güvenli bağlanma', 'relationships', 'advanced', 'en', 'Secure attachment fosters stable bonds.', 'Güvenli bağlanma kararlı bağları destekler.'),
  ('anxious attachment', 'kaygılı bağlanma', 'relationships', 'advanced', 'en', 'Anxious attachment fears abandonment.', 'Kaygılı bağlanma terk edilmekten korkar.'),
  ('avoidant attachment', 'kaçınan bağlanma', 'relationships', 'advanced', 'en', 'Avoidant attachment keeps emotional distance.', 'Kaçınan bağlanma duygusal mesafe korur.'),
  ('codependency', 'bağımlılık', 'relationships', 'advanced', 'en', 'Codependency blurs personal boundaries.', 'Bağımlılık kişisel sınırları bulanıklaştırır.'),
  ('emotional availability', 'duygusal erişilebilirlik', 'relationships', 'advanced', 'en', 'Emotional availability deepens trust.', 'Duygusal erişilebilirlik güveni derinleştirir.'),
  ('love language', 'sevgi dili', 'relationships', 'advanced', 'en', 'Learn your partner''s love language.', 'Partnerinin sevgi dilini öğren.'),
  ('narcissistic behavior', 'narsist davranış', 'relationships', 'advanced', 'en', 'Narcissistic behavior ignores others'' needs.', 'Narsist davranış başkalarının ihtiyaçlarını görmezden gelir.'),
  ('toxic relationship', 'toksik ilişki', 'relationships', 'advanced', 'en', 'A toxic relationship drains self-esteem.', 'Toksik ilişki özgüveni tüketir.'),
  ('emotional abuse', 'duygusal istismar', 'relationships', 'advanced', 'en', 'Emotional abuse often hides behind jokes.', 'Duygusal istismar genelde şakaların arkasında gizlenir.'),
  ('manipulation', 'manipülasyon', 'relationships', 'advanced', 'en', 'Manipulation distorts another person''s choices.', 'Manipülasyon başka birinin seçimlerini çarpıtır.'),
  ('triangulation', 'üçgenleme', 'relationships', 'advanced', 'en', 'Triangulation pulls a third person into conflict.', 'Üçgenleme üçüncü bir kişiyi çatışmaya çeker.'),
  ('stonewalling', 'duvar örme', 'relationships', 'advanced', 'en', 'Stonewalling shuts down difficult talks.', 'Duvar örme zor konuşmaları kapatır.'),
  ('contempt', 'aşağılama', 'relationships', 'advanced', 'en', 'Contempt predicts relationship failure.', 'Aşağılama ilişki başarısızlığını öngörür.'),
  ('repair attempt', 'onarım girişimi', 'relationships', 'advanced', 'en', 'A repair attempt can stop escalation.', 'Bir onarım girişimi tırmanmayı durdurabilir.'),
  ('interpersonal dynamics', 'kişilerarası dinamikler', 'relationships', 'advanced', 'en', 'Interpersonal dynamics shift in groups.', 'Kişilerarası dinamikler gruplarda değişir.'),
  ('social reciprocity', 'sosyal karşılıklılık', 'relationships', 'advanced', 'en', 'Social reciprocity balances give and take.', 'Sosyal karşılıklılık vermeyi ve almayı dengeler.'),
  ('kinship', 'akrabalık', 'relationships', 'advanced', 'en', 'Kinship ties remain strong in rural areas.', 'Akrabalık bağları kırsal bölgelerde güçlü kalır.'),
  ('chosen family', 'seçilmiş aile', 'relationships', 'advanced', 'en', 'Friends can become a chosen family.', 'Arkadaşlar seçilmiş aile olabilir.'),
  ('intergenerational trauma', 'nesiller arası travma', 'relationships', 'advanced', 'en', 'Intergenerational trauma affects family patterns.', 'Nesiller arası travma aile kalıplarını etkiler.'),
  ('marital counseling', 'evlilik danışmanlığı', 'relationships', 'advanced', 'en', 'Marital counseling improved their communication.', 'Evlilik danışmanlığı iletişimlerini iyileştirdi.'),
  ('premarital agreement', 'evlilik öncesi anlaşma', 'relationships', 'advanced', 'en', 'They signed a premarital agreement.', 'Evlilik öncesi anlaşma imzaladılar.'),
  ('polyamory', 'poliamori', 'relationships', 'advanced', 'en', 'Polyamory requires honest multi-partner talks.', 'Poliamori dürüst çok partnerli konuşmalar gerektirir.'),
  ('asexuality', 'aseksüellik', 'relationships', 'advanced', 'en', 'Asexuality is a valid identity spectrum.', 'Aseksüellik geçerli bir kimlik spektrumudur.'),
  ('misattunement', 'uyumsuzluk', 'relationships', 'advanced', 'en', 'Parent-child misattunement causes distress.', 'Ebeveyn-çocuk uyumsuzluğu sıkıntı yaratır.'),
  ('differentiation of self', 'benlik farklılaşması', 'relationships', 'advanced', 'en', 'Differentiation of self reduces fusion in couples.', 'Benlik farklılaşması çiftlerde kaynaşmayı azaltır.'),
  ('relational aggression', 'ilişkisel saldırganlık', 'relationships', 'advanced', 'en', 'Relational aggression spreads rumors quietly.', 'İlişkisel saldırganlık dedikoduyu sessizce yayar.'),
  ('social exclusion', 'sosyal dışlanma', 'relationships', 'advanced', 'en', 'Social exclusion hurts adolescent wellbeing.', 'Sosyal dışlanma ergen refahını incitir.'),
  ('parasocial relationship', 'parasosyal ilişki', 'relationships', 'advanced', 'en', 'Fans form a parasocial relationship with stars.', 'Hayranlar yıldızlarla parasosyal ilişki kurar.');