INSERT INTO vocabulary_games (word, meaning, category, difficulty, language, example_sentence, example_translation)
VALUES
  ('liminal emotion', 'eşik duygusu', 'emotions', 'advanced', 'en', 'Graduation brings a liminal emotion of change.', 'Mezuniyet değişimin eşik duygusunu getirir.'),
  ('bittersweet', 'acı-tatlı', 'emotions', 'advanced', 'en', 'Farewells often feel bittersweet.', 'Vedalar genelde acı-tatlı hissettirir.'),
  ('emotional contagion', 'duygusal bulaşma', 'emotions', 'advanced', 'en', 'Laughter spreads through emotional contagion.', 'Kahkaha duygusal bulaşmayla yayılır.'),
  ('affect regulation', 'duygu düzenleme', 'emotions', 'advanced', 'en', 'Children learn affect regulation from caregivers.', 'Çocuklar duygu düzenlemeyi bakıcılardan öğrenir.'),
  ('moral outrage', 'ahlaki öfke', 'emotions', 'advanced', 'en', 'Injustice sparked moral outrage online.', 'Adaletsizlik çevrimiçi ahlaki öfke yarattı.'),
  ('compassion fatigue', 'merhamet yorgunluğu', 'emotions', 'advanced', 'en', 'Nurses risk compassion fatigue.', 'Hemşireler merhamet yorgunluğu riski taşır.'),
  ('emotional granularity', 'duygusal ayrıntılılık', 'emotions', 'advanced', 'en', 'Emotional granularity improves self-awareness.', 'Duygusal ayrıntılılık öz farkındalığı artırır.'),
  ('post-traumatic growth', 'travma sonrası büyüme', 'emotions', 'advanced', 'en', 'Some report post-traumatic growth after hardship.', 'Bazıları zorluktan sonra travma sonrası büyüme bildirir.'),
  ('emotional validation', 'duygusal onaylama', 'emotions', 'advanced', 'en', 'Emotional validation calms heated talks.', 'Duygusal onaylama hararetli konuşmaları sakinleştirir.'),
  ('dysthymia', 'distimi', 'emotions', 'advanced', 'en', 'Dysthymia involves chronic low mood.', 'Distimi kronik düşük ruh hali içerir.'),
  ('school', 'okul', 'education', 'beginner', 'en', 'School starts at eight o''clock.', 'Okul saat sekizde başlar.'),
  ('teacher', 'öğretmen', 'education', 'beginner', 'en', 'Our teacher explains lessons clearly.', 'Öğretmenimiz dersleri net anlatıyor.'),
  ('student', 'öğrenci', 'education', 'beginner', 'en', 'Every student needs a notebook.', 'Her öğrencinin bir deftere ihtiyacı var.'),
  ('class', 'sınıf', 'education', 'beginner', 'en', 'The class meets in room twelve.', 'Sınıf on iki numaralı odada buluşuyor.'),
  ('book', 'kitap', 'education', 'beginner', 'en', 'Read the book before the test.', 'Sınavdan önce kitabı oku.'),
  ('pen', 'kalem', 'education', 'beginner', 'en', 'Borrow a pen if you forgot yours.', 'Kalemini unuttuysan bir kalem ödünç al.'),
  ('pencil', 'kurşun kalem', 'education', 'beginner', 'en', 'Use a pencil for the diagram.', 'Şema için kurşun kalem kullan.'),
  ('homework', 'ev ödevi', 'education', 'beginner', 'en', 'Finish your homework before dinner.', 'Akşam yemeğinden önce ev ödevini bitir.'),
  ('exam', 'sınav', 'education', 'beginner', 'en', 'The math exam is on Friday.', 'Matematik sınavı cuma.'),
  ('grade', 'not', 'education', 'beginner', 'en', 'She earned a high grade.', 'Yüksek bir not aldı.'),
  ('lesson', 'ders', 'education', 'beginner', 'en', 'Today''s lesson covers verbs.', 'Bugünkü ders fiilleri kapsıyor.'),
  ('desk', 'sıra', 'education', 'beginner', 'en', 'Keep your desk tidy.', 'Sıranı düzenli tut.'),
  ('board', 'tahta', 'education', 'beginner', 'en', 'The teacher wrote on the board.', 'Öğretmen tahtaya yazdı.'),
  ('library', 'kütüphane', 'education', 'beginner', 'en', 'Study quietly in the library.', 'Kütüphanede sessizce çalış.'),
  ('subject', 'ders', 'education', 'beginner', 'en', 'Math is my favorite subject.', 'Matematik en sevdiğim ders.'),
  ('question', 'soru', 'education', 'beginner', 'en', 'Raise your hand to ask a question.', 'Soru sormak için elini kaldır.'),
  ('answer', 'cevap', 'education', 'beginner', 'en', 'Write the answer in full sentences.', 'Cevabı tam cümlelerle yaz.'),
  ('study', 'çalışmak', 'education', 'beginner', 'en', 'Study a little every day.', 'Her gün biraz çalış.'),
  ('learn', 'öğrenmek', 'education', 'beginner', 'en', 'Children learn languages quickly.', 'Çocuklar dilleri hızlı öğrenir.'),
  ('read', 'okumak', 'education', 'beginner', 'en', 'Read the instructions carefully.', 'Talimatları dikkatlice oku.'),
  ('write', 'yazmak', 'education', 'beginner', 'en', 'Write your name at the top.', 'Adını en üste yaz.'),
  ('spell', 'hecelemek', 'education', 'beginner', 'en', 'Can you spell your surname?', 'Soyadını heceleyebilir misin?'),
  ('dictionary', 'sözlük', 'education', 'beginner', 'en', 'Use a dictionary for new words.', 'Yeni kelimeler için sözlük kullan.'),
  ('notebook', 'defter', 'education', 'beginner', 'en', 'Copy notes into your notebook.', 'Notları defterine kopyala.'),
  ('break', 'teneffüs', 'education', 'beginner', 'en', 'We play outside during break.', 'Teneffüste dışarıda oynuyoruz.'),
  ('uniform', 'üniforma', 'education', 'beginner', 'en', 'Students wear a blue uniform.', 'Öğrenciler mavi üniforma giyer.'),
  ('principal', 'müdür', 'education', 'beginner', 'en', 'The principal spoke at assembly.', 'Müdür toplantıda konuştu.'),
  ('classmate', 'sınıf arkadaşı', 'education', 'beginner', 'en', 'My classmate shared her notes.', 'Sınıf arkadaşım notlarını paylaştı.'),
  ('schedule', 'program', 'education', 'beginner', 'en', 'Check the schedule for room changes.', 'Oda değişiklikleri için programı kontrol et.'),
  ('quiz', 'kısa sınav', 'education', 'beginner', 'en', 'We have a short quiz tomorrow.', 'Yarın kısa bir sınavımız var.'),
  ('curriculum', 'müfredat', 'education', 'intermediate', 'en', 'The curriculum includes coding basics.', 'Müfredat kodlama temellerini içeriyor.'),
  ('syllabus', 'ders programı', 'education', 'intermediate', 'en', 'The syllabus lists all assignments.', 'Ders programı tüm ödevleri listeler.'),
  ('lecture', 'ders', 'education', 'intermediate', 'en', 'The lecture lasted ninety minutes.', 'Ders doksan dakika sürdü.'),
  ('seminar', 'seminer', 'education', 'intermediate', 'en', 'Students discuss texts in the seminar.', 'Öğrenciler seminerde metinleri tartışır.'),
  ('thesis', 'tez', 'education', 'intermediate', 'en', 'She is writing her master''s thesis.', 'Yüksek lisans tezini yazıyor.'),
  ('research', 'araştırma', 'education', 'intermediate', 'en', 'Research requires reliable sources.', 'Araştırma güvenilir kaynaklar gerektirir.'),
  ('citation', 'atıf', 'education', 'intermediate', 'en', 'Include a citation for each quote.', 'Her alıntı için atıf ekle.'),
  ('plagiarism', 'intihal', 'education', 'intermediate', 'en', 'Plagiarism leads to serious penalties.', 'İntihal ciddi cezalara yol açar.'),
  ('scholarship', 'burs', 'education', 'intermediate', 'en', 'He won a scholarship for excellence.', 'Başarı için burs kazandı.'),
  ('tuition', 'öğrenim ücreti', 'education', 'intermediate', 'en', 'Tuition fees rise each year.', 'Öğrenim ücretleri her yıl artıyor.'),
  ('enrollment', 'kayıt', 'education', 'intermediate', 'en', 'Enrollment closes at the end of August.', 'Kayıt ağustos sonunda kapanır.'),
  ('attendance', 'devam', 'education', 'intermediate', 'en', 'Attendance affects your final grade.', 'Devam final notunu etkiler.'),
  ('deadline', 'son teslim tarihi', 'education', 'intermediate', 'en', 'Submit essays before the deadline.', 'Denemeleri son teslim tarihinden önce gönder.'),
  ('peer review', 'akran değerlendirmesi', 'education', 'intermediate', 'en', 'Peer review improves draft quality.', 'Akran değerlendirmesi taslak kalitesini artırır.'),
  ('rubric', 'değerlendirme ölçütü', 'education', 'intermediate', 'en', 'Check the rubric before submitting.', 'Göndermeden önce değerlendirme ölçütünü kontrol et.'),
  ('extracurricular', 'ders dışı', 'education', 'intermediate', 'en', 'Extracurricular clubs meet after school.', 'Ders dışı kulüpler okul sonrası buluşur.'),
  ('literacy', 'okuryazarlık', 'education', 'intermediate', 'en', 'Early literacy programs help young kids.', 'Erken okuryazarlık programları küçük çocuklara yardım eder.'),
  ('numeracy', 'sayısal okuryazarlık', 'education', 'intermediate', 'en', 'Numeracy skills support daily budgeting.', 'Sayısal okuryazarlık günlük bütçelemeyi destekler.'),
  ('STEM', 'STEM', 'education', 'intermediate', 'en', 'STEM fields need creative problem solvers.', 'STEM alanları yaratıcı problem çözücülere ihtiyaç duyar.'),
  ('humanities', 'beşeri bilimler', 'education', 'intermediate', 'en', 'Humanities explore culture and history.', 'Beşeri bilimler kültür ve tarihi inceler.'),
  ('vocational training', 'mesleki eğitim', 'education', 'intermediate', 'en', 'Vocational training prepares skilled workers.', 'Mesleki eğitim nitelikli işçiler yetiştirir.'),
  ('online learning', 'çevrimiçi öğrenme', 'education', 'intermediate', 'en', 'Online learning offers flexible schedules.', 'Çevrimiçi öğrenme esnek programlar sunar.'),
  ('blended learning', 'harmanlanmış öğrenme', 'education', 'intermediate', 'en', 'Blended learning mixes video and class time.', 'Harmanlanmış öğrenme video ve sınıf süresini karıştırır.'),
  ('formative assessment', 'biçimlendirici değerlendirme', 'education', 'intermediate', 'en', 'Formative assessment guides daily teaching.', 'Biçimlendirici değerlendirme günlük öğretimi yönlendirir.'),
  ('summative assessment', 'özet değerlendirme', 'education', 'intermediate', 'en', 'Final exams are summative assessment.', 'Final sınavları özet değerlendirmedir.'),
  ('learning objective', 'öğrenme hedefi', 'education', 'intermediate', 'en', 'Each lesson states a learning objective.', 'Her ders bir öğrenme hedefi belirtir.'),
  ('critical thinking', 'eleştirel düşünme', 'education', 'intermediate', 'en', 'Critical thinking questions assumptions.', 'Eleştirel düşünme varsayımları sorgular.'),
  ('study group', 'çalışma grubu', 'education', 'intermediate', 'en', 'Our study group meets on Wednesdays.', 'Çalışma grubumuz çarşamba buluşuyor.'),
  ('office hours', 'danışma saati', 'education', 'intermediate', 'en', 'Visit professors during office hours.', 'Danışma saatinde profesörleri ziyaret et.'),
  ('dean', 'dekan', 'education', 'intermediate', 'en', 'The dean approved the new program.', 'Dekan yeni programı onayladı.'),
  ('pedagogy', 'pedagoji', 'education', 'advanced', 'en', 'Modern pedagogy favors active learning.', 'Modern pedagoji aktif öğrenmeyi tercih eder.'),
  ('andragogy', 'andragoji', 'education', 'advanced', 'en', 'Andragogy focuses on adult learners.', 'Andragoji yetişkin öğrenenlere odaklanır.'),
  ('constructivism', 'yapılandırmacılık', 'education', 'advanced', 'en', 'Constructivism builds knowledge through experience.', 'Yapılandırmacılık bilgiyi deneyimle inşa eder.'),
  ('metacognition', 'üstbiliş', 'education', 'advanced', 'en', 'Metacognition improves study strategies.', 'Üstbiliş çalışma stratejilerini iyileştirir.'),
  ('scaffolding', 'iskele kurma', 'education', 'advanced', 'en', 'Teachers use scaffolding for complex tasks.', 'Öğretmenler karmaşık görevler için iskele kurma kullanır.'),
  ('differentiated instruction', 'farklılaştırılmış öğretim', 'education', 'advanced', 'en', 'Differentiated instruction meets diverse needs.', 'Farklılaştırılmış öğretim çeşitli ihtiyaçları karşılar.'),
  ('inclusive education', 'kapsayıcı eğitim', 'education', 'advanced', 'en', 'Inclusive education welcomes all abilities.', 'Kapsayıcı eğitim tüm yetenekleri kucaklar.'),
  ('learning analytics', 'öğrenme analitiği', 'education', 'advanced', 'en', 'Learning analytics track student progress online.', 'Öğrenme analitiği öğrenci ilerlemesini çevrimiçi izler.'),
  ('competency-based education', 'yetkinlik temelli eğitim', 'education', 'advanced', 'en', 'Competency-based education measures skills gained.', 'Yetkinlik temelli eğitim kazanılan becerileri ölçer.'),
  ('epistemology', 'epistemoloji', 'education', 'advanced', 'en', 'Epistemology asks how we know truth.', 'Epistemoloji gerçeği nasıl bildiğimizi sorar.'),
  ('heuristic', 'sezgisel yöntem', 'education', 'advanced', 'en', 'A useful heuristic speeds problem solving.', 'Faydalı bir sezgisel yöntem problem çözmeyi hızlandırır.'),
  ('cognitive load theory', 'bilişsel yük teorisi', 'education', 'advanced', 'en', 'Cognitive load theory limits slide text.', 'Bilişsel yük teorisi slayt metnini sınırlar.'),
  ('spaced repetition', 'aralıklı tekrar', 'education', 'advanced', 'en', 'Spaced repetition boosts long-term memory.', 'Aralıklı tekrar uzun süreli hafızayı güçlendirir.'),
  ('interdisciplinary', 'disiplinler arası', 'education', 'advanced', 'en', 'Interdisciplinary courses blend science and art.', 'Disiplinler arası dersler bilim ve sanatı birleştirir.'),
  ('doctoral candidacy', 'doktora adaylığı', 'education', 'advanced', 'en', 'Doctoral candidacy follows qualifying exams.', 'Doktora adaylığı yeterlilik sınavlarını takip eder.'),
  ('dissertation defense', 'tez savunması', 'education', 'advanced', 'en', 'Her dissertation defense lasts several hours.', 'Her tez savunması birkaç saat sürer.'),
  ('grant funding', 'hibe fonu', 'education', 'advanced', 'en', 'Grant funding supports university research.', 'Hibe fonu üniversite araştırmasını destekler.'),
  ('tenure track', 'kadrolu akademik yol', 'education', 'advanced', 'en', 'She joined a tenure track position.', 'Kadrolu akademik yola geçen bir pozisyona girdi.'),
  ('open educational resources', 'açık eğitim kaynakları', 'education', 'advanced', 'en', 'Open educational resources reduce textbook costs.', 'Açık eğitim kaynakları ders kitabı maliyetlerini düşürür.'),
  ('MOOC', 'MOOC', 'education', 'advanced', 'en', 'A MOOC reached learners worldwide.', 'Bir MOOC dünya çapında öğrenenlere ulaştı.'),
  ('flipped classroom', 'ters yüz sınıf', 'education', 'advanced', 'en', 'The flipped classroom assigns videos at home.', 'Ters yüz sınıf evde video ödevi verir.'),
  ('experiential learning', 'deneyimsel öğrenme', 'education', 'advanced', 'en', 'Experiential learning uses real-world projects.', 'Deneyimsel öğrenme gerçek dünya projeleri kullanır.'),
  ('standardized testing', 'standart test', 'education', 'advanced', 'en', 'Standardized testing draws ongoing debate.', 'Standart test süregelen tartışma yaratır.'),
  ('achievement gap', 'başarı farkı', 'education', 'advanced', 'en', 'Policies aim to close the achievement gap.', 'Politikalar başarı farkını kapatmayı hedefler.'),
  ('socioeconomic disparity', 'sosyoekonomik eşitsizlik', 'education', 'advanced', 'en', 'Socioeconomic disparity affects school access.', 'Sosyoekonomik eşitsizlik okula erişimi etkiler.'),
  ('neuroeducation', 'nöroeğitim', 'education', 'advanced', 'en', 'Neuroeducation links brain science to teaching.', 'Nöroeğitim beyin bilimini öğretime bağlar.'),
  ('formative feedback loop', 'biçimlendirici geri bildirim döngüsü', 'education', 'advanced', 'en', 'A formative feedback loop guides revision.', 'Biçimlendirici geri bildirim döngüsü revizyonu yönlendirir.'),
  ('academic integrity', 'akademik dürüstlük', 'education', 'advanced', 'en', 'Academic integrity forbids cheating.', 'Akademik dürüstlük kopya çekmeyi yasaklar.'),
  ('institutional review board', 'kurumsal inceleme kurulu', 'education', 'advanced', 'en', 'Research needs institutional review board approval.', 'Araştırma kurumsal inceleme kurulu onayı gerektirir.');