-- Idempotent custom_quizzes seed (run once; duplicates skipped if re-run manually)
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('daily life', 'intermediate', 'My ___ takes forty minutes.', 'mortgage', 'insurance', 'commute', 'tenant', 'C'),
  ('daily life', 'intermediate', 'The project ___ is Friday.', 'renovation', 'deadline', 'chore chart', 'housewarming', 'B'),
  ('daily life', 'advanced', '___ makes small rooms feel cramped.', 'overwhelmed', 'Clutter', 'frugal', 'mindful', 'B'),
  ('daily life', 'advanced', 'A ___ lifestyle avoids waste.', 'Resilience', 'frugal', 'procrastinate', 'spontaneous', 'B'),
  ('daily life', 'advanced', 'Be ___ of how you spend time.', 'Sustainable', 'Intentional living', 'Minimalism', 'mindful', 'D'),
  ('daily life', 'advanced', 'She felt ___ by daily tasks.', 'Delegation', 'Prioritization', 'overwhelmed', 'burnout', 'C'),
  ('daily life', 'advanced', 'Do not ___ on important chores.', 'Habit stacking', 'procrastinate', 'Financial literacy', 'Decision fatigue', 'B'),
  ('animals', 'beginner', 'A ___ is singing outside.', 'dog', 'bird', 'cat', 'cow', 'B'),
  ('animals', 'beginner', 'The ___ sleeps on the sofa.', 'fish', 'cat', 'duck', 'horse', 'B'),
  ('animals', 'beginner', 'The ___ eats grass in the field.', 'rabbit', 'chicken', 'Sheep', 'cow', 'D'),
  ('animals', 'beginner', 'My ___ loves to play fetch.', 'mouse', 'goat', 'dog', 'pig', 'C'),
  ('animals', 'beginner', 'We saw colorful ___ at the aquarium.', 'wolf', 'fish', 'bear', 'fox', 'B'),
  ('animals', 'intermediate', '___ helps prey hide from predators.', 'mammal', 'Camouflage', 'endangered', 'habitat', 'B'),
  ('animals', 'intermediate', 'Tigers are an ___ species.', 'nocturnal', 'endangered', 'migration', 'predator', 'B'),
  ('animals', 'intermediate', 'Bird ___ follows seasonal routes.', 'den', 'migration', 'antlers', 'nest', 'B'),
  ('animals', 'intermediate', 'Owls are ___ hunters.', 'beak', 'nocturnal', 'paw', 'gills', 'B'),
  ('animals', 'intermediate', 'The ___ stalked its prey silently.', 'scales', 'feathers', 'wildlife', 'predator', 'D'),
  ('animals', 'advanced', 'Dog ___ began thousands of years ago.', 'symbiosis', 'domestication', 'instinct', 'territorial', 'B'),
  ('animals', 'advanced', 'The island has unique ___.', 'venomous', 'mutualism', 'biodiversity', 'fauna', 'D'),
  ('animals', 'advanced', 'Bears enter ___ in late autumn.', 'echolocation', 'metamorphosis', 'hibernation', 'parasitism', 'C'),
  ('animals', 'advanced', 'Migration is driven by ___.', 'bioluminescence', 'instinct', 'Invasive species', 'keystone species', 'B'),
  ('animals', 'advanced', 'Clownfish and anemones show ___.', 'Anthropogenic', 'symbiosis', 'genetic diversity', 'poaching', 'B'),
  ('drinks', 'beginner', 'Drink ___ throughout the day.', 'milk', 'water', 'tea', 'coffee', 'B'),
  ('drinks', 'beginner', 'Turkish ___ is served in small glasses.', 'Soda', 'tea', 'juice', 'lemonade', 'B'),
  ('drinks', 'beginner', 'I need ___ to wake up.', 'Hot chocolate', 'beer', 'smoothie', 'coffee', 'D'),
  ('drinks', 'beginner', 'Children drink ___ for calcium.', 'Mineral water', 'cocktail', 'milk', 'wine', 'C'),
  ('drinks', 'beginner', 'Orange ___ is popular at breakfast.', 'Sparkling water', 'juice', 'Espresso', 'Herbal tea', 'B'),
  ('drinks', 'intermediate', '___ the tea for five minutes.', 'Distill', 'Brew', 'steep', 'ferment', 'B'),
  ('drinks', 'intermediate', 'Let the leaves ___ in hot water.', 'decaf', 'steep', 'Carbonated', 'bitters', 'B'),
  ('drinks', 'intermediate', 'They ___ grapes to make wine.', 'garnish', 'mocktail', 'infusion', 'ferment', 'D'),
  ('drinks', 'intermediate', '___ spirits in copper stills.', 'Tonic water', 'Cold brew', 'Distill', 'Single origin', 'C'),
  ('drinks', 'intermediate', '___ drinks feel fizzy.', 'Sake', 'Carbonated', 'Rooibos', 'Matcha', 'B'),
  ('drinks', 'advanced', '___ describes texture in wine.', 'Oxidation', 'Mouthfeel', 'tannins', 'Terroir', 'B'),
  ('drinks', 'advanced', 'High ___ make wine taste dry.', 'Mixology', 'tannins', 'Fortified wine', 'palate cleanser', 'B'),
  ('drinks', 'advanced', '___ shapes grape character.', 'astringency', 'extraction yield', 'Microfoam', 'Terroir', 'D'),
  ('drinks', 'advanced', '___ can spoil opened wine.', 'proof', 'Barrel aging', 'Oxidation', 'Dry hopping', 'C'),
  ('drinks', 'advanced', '___ contains added spirits.', 'hangover', 'Fortified wine', 'Blood alcohol level', 'Responsible drinking', 'B'),
  ('relationships', 'beginner', 'She is my closest ___.', 'father', 'friend', 'Family', 'mother', 'B'),
  ('relationships', 'beginner', '___ dinners happen every Sunday.', 'brother', 'Family', 'sister', 'son', 'B'),
  ('relationships', 'beginner', 'My ___ calls me every week.', 'daughter', 'wife', 'husband', 'mother', 'D');