-- Idempotent custom_quizzes seed (run once; duplicates skipped if re-run manually)
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('emotions', 'advanced', 'Support pulled him out of ___.', 'Gaslighting', 'emotional labor', 'despair', 'Cognitive empathy', 'C'),
  ('emotions', 'advanced', 'Late nights sometimes trigger ___.', 'trauma response', 'existential dread', 'emotional numbness', 'Hypervigilance', 'B'),
  ('education', 'beginner', '___ starts at eight o''clock.', 'class', 'School', 'teacher', 'student', 'B'),
  ('education', 'beginner', 'Our ___ explains lessons clearly.', 'pen', 'teacher', 'book', 'pencil', 'B'),
  ('education', 'beginner', 'Every ___ needs a notebook.', 'homework', 'grade', 'exam', 'student', 'D'),
  ('education', 'beginner', 'The ___ meets in room twelve.', 'board', 'desk', 'class', 'lesson', 'C'),
  ('education', 'beginner', 'Read the ___ before the test.', 'library', 'book', 'question', 'subject', 'B'),
  ('education', 'intermediate', 'The ___ includes coding basics.', 'seminar', 'curriculum', 'syllabus', 'lecture', 'B'),
  ('education', 'intermediate', 'The ___ lists all assignments.', 'Research', 'syllabus', 'thesis', 'citation', 'B'),
  ('education', 'intermediate', 'The ___ lasted ninety minutes.', 'Plagiarism', 'Tuition', 'scholarship', 'lecture', 'D'),
  ('education', 'intermediate', 'Students discuss texts in the ___.', 'deadline', 'Attendance', 'seminar', 'Enrollment', 'C'),
  ('education', 'intermediate', 'She is writing her master''s ___.', 'Peer review', 'thesis', 'Extracurricular', 'rubric', 'B'),
  ('education', 'advanced', 'Modern ___ favors active learning.', 'Metacognition', 'pedagogy', 'Andragogy', 'Constructivism', 'B'),
  ('education', 'advanced', '___ focuses on adult learners.', 'Differentiated instruction', 'Andragogy', 'scaffolding', 'Inclusive education', 'B'),
  ('education', 'advanced', '___ builds knowledge through experience.', 'Learning analytics', 'Epistemology', 'Competency-based education', 'Constructivism', 'D'),
  ('education', 'advanced', '___ improves study strategies.', 'Spaced repetition', 'Cognitive load theory', 'Metacognition', 'heuristic', 'C'),
  ('education', 'advanced', 'Teachers use ___ for complex tasks.', 'Interdisciplinary', 'scaffolding', 'dissertation defense', 'Doctoral candidacy', 'B'),
  ('clothes', 'beginner', 'He wore a clean white ___.', 'skirt', 'shirt', 'pants', 'dress', 'B'),
  ('clothes', 'beginner', 'These ___ are too long.', 'coat', 'pants', 'jacket', 'shoes', 'B'),
  ('clothes', 'beginner', 'She bought a blue ___.', 'socks', 'scarf', 'hat', 'dress', 'D'),
  ('clothes', 'beginner', 'The ___ has floral patterns.', 'Jeans', 'belt', 'skirt', 'gloves', 'C'),
  ('clothes', 'beginner', 'Take a ___, it is windy.', 'T-shirt', 'jacket', 'Shorts', 'sweater', 'B'),
  ('clothes', 'intermediate', 'Organize your ___ by season.', 'tailor', 'wardrobe', 'outfit', 'accessory', 'B'),
  ('clothes', 'intermediate', 'She planned her ___ for the event.', 'hem', 'outfit', 'alteration', 'seam', 'B'),
  ('clothes', 'intermediate', 'A simple ___ completes the look.', 'Linen', 'Silk', 'Wool', 'accessory', 'D'),
  ('clothes', 'intermediate', 'The ___ shortened the sleeves.', 'waterproof', 'Leather', 'tailor', 'Denim', 'C'),
  ('clothes', 'intermediate', 'The ___ of the skirt was uneven.', 'Sportswear', 'hem', 'Formal wear', 'Fast fashion', 'B'),
  ('clothes', 'advanced', '___ pieces are made to order.', 'Textile engineering', 'Haute couture', 'Prêt-à-porter', 'capsule wardrobe', 'B'),
  ('clothes', 'advanced', '___ lines reach wider markets.', 'draping', 'Prêt-à-porter', 'Garment construction', 'Pattern grading', 'B'),
  ('clothes', 'advanced', 'A ___ reduces daily choices.', 'Bias cut', 'colorfastness', 'Millinery', 'capsule wardrobe', 'D'),
  ('clothes', 'advanced', '___ improves fabric durability.', 'Gore-Tex', 'Moisture-wicking', 'Textile engineering', 'pilling', 'C'),
  ('clothes', 'advanced', '___ affects longevity.', 'Ethical sourcing', 'Garment construction', 'greenwashing', 'Circular fashion', 'B'),
  ('daily life', 'beginner', 'My ___ rings at six every morning.', 'grocery', 'alarm', 'breakfast', 'errand', 'B'),
  ('daily life', 'beginner', 'I always eat ___ before work.', 'neighbor', 'breakfast', 'laundry', 'schedule', 'B'),
  ('daily life', 'beginner', 'We buy ___ items every Friday.', 'mailbox', 'wallet', 'grocery', 'keys', 'C'),
  ('daily life', 'beginner', 'I do ___ on Sundays.', 'doorbell', 'laundry', 'pillow', 'curtain', 'B'),
  ('daily life', 'beginner', 'Our ___ brought us soup.', 'toothbrush', 'neighbor', 'blanket', 'soap', 'B'),
  ('daily life', 'intermediate', 'The kitchen ___ broke yesterday.', 'commute', 'appliance', 'appointment', 'budget', 'B'),
  ('daily life', 'intermediate', 'She rescheduled her doctor ___.', 'routine', 'appointment', 'deadline', 'subscription', 'B'),
  ('daily life', 'intermediate', 'We stick to a monthly ___.', 'utility bill', 'landlord', 'maintenance', 'budget', 'D');