-- Idempotent custom_quizzes seed (run once; duplicates skipped if re-run manually)
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('nature', 'beginner', 'The old ___ shades the bench.', 'mountain', 'tree', 'flower', 'river', 'B'),
  ('nature', 'beginner', 'She picked a red ___.', 'lake', 'flower', 'forest', 'ocean', 'B'),
  ('nature', 'beginner', 'The ___ flows to the sea.', 'beach', 'cloud', 'sky', 'river', 'D'),
  ('nature', 'beginner', 'Snow covers the ___ peak.', 'wind', 'Snow', 'mountain', 'rain', 'C'),
  ('nature', 'beginner', 'We walked through a quiet ___.', 'sun', 'forest', 'star', 'moon', 'B'),
  ('nature', 'intermediate', '___ keeps nature resilient.', 'Erosion', 'Biodiversity', 'flood', 'Pollution', 'B'),
  ('nature', 'intermediate', '___ shapes regional plant life.', 'Recycle', 'greenhouse gas', 'renewable energy', 'Climate', 'D'),
  ('nature', 'intermediate', '___ dried the riverbed.', 'Habitat loss', 'Conservation', 'Drought', 'carbon footprint', 'C'),
  ('nature', 'intermediate', 'Heavy rain caused a ___.', 'wildfire', 'flood', 'tide', 'Monsoon', 'B'),
  ('nature', 'intermediate', '___ washed soil down the slope.', 'coral reef', 'Erosion', 'glacier', 'wetland', 'B'),
  ('nature', 'advanced', 'Scientists debate the start of the ___.', 'keystone species', 'Anthropocene', 'biogeochemical cycle', 'Ecological succession', 'B'),
  ('nature', 'advanced', 'The carbon cycle is a ___.', 'albedo effect', 'biogeochemical cycle', 'trophic cascade', 'Ocean acidification', 'B'),
  ('nature', 'advanced', '___ rebuilds burned forests.', 'desertification', 'mitigation', 'carbon sequestration', 'Ecological succession', 'D'),
  ('nature', 'advanced', 'Beavers act as a ___.', 'Invasive species', 'biodiversity hotspot', 'keystone species', 'adaptation strategy', 'C'),
  ('nature', 'advanced', 'Wolf reintroduction caused a ___.', 'Phenology', 'trophic cascade', 'Watershed management', 'symbiotic relationship', 'B'),
  ('hardware', 'beginner', 'My phone ___ is low.', 'battery', 'button', 'cable', 'charger', 'A'),
  ('hardware', 'beginner', 'This ___ feels comfortable to type on.', 'mouse', 'keyboard', 'speaker', 'screen', 'B'),
  ('hardware', 'beginner', 'I forgot my ___ at home.', 'router', 'printer', 'charger', 'monitor', 'C'),
  ('hardware', 'beginner', 'The ___ is cracked and needs repair.', 'battery', 'cable', 'screen', 'button', 'C'),
  ('hardware', 'intermediate', 'A faster ___ speeds up everyday work on your PC.', 'processor', 'driver', 'BIOS', 'touchpad', 'A'),
  ('hardware', 'intermediate', 'Games need a strong ___ for smooth graphics.', 'graphics card', 'power supply', 'SATA cable', 'optical drive', 'A'),
  ('hardware', 'intermediate', '4K ___ shows sharper images on a large monitor.', 'refresh rate', 'resolution', 'form factor', 'pixel density', 'B'),
  ('hardware', 'intermediate', 'Add more ___ to run heavy applications smoothly.', 'RAM', 'NVMe', 'BIOS', 'HDMI port', 'A'),
  ('hardware', 'advanced', 'Low ___ matters in competitive online games.', 'throughput', 'latency', 'jitter', 'bandwidth', 'B'),
  ('hardware', 'advanced', 'Update the router ___ regularly for security patches.', 'chipset', 'firmware', 'capacitor', 'hypervisor', 'B'),
  ('hardware', 'advanced', 'Streaming video uses a lot of ___.', 'bandwidth', 'TDP', 'VRM', 'PCIe lane', 'A'),
  ('hardware', 'advanced', 'An old CPU can create a ___ for the GPU and limit frame rates.', 'chipset', 'bottleneck', 'hypervisor', 'failover', 'B'),
  ('emotions', 'beginner', 'She felt ___ after the good news.', 'scared', 'happy', 'sad', 'angry', 'B'),
  ('emotions', 'beginner', 'He looked ___ at the farewell.', 'tired', 'sad', 'excited', 'nervous', 'B'),
  ('emotions', 'beginner', 'Do not speak when you are ___.', 'calm', 'lonely', 'proud', 'angry', 'D'),
  ('emotions', 'beginner', 'The child was ___ of the dark.', 'joy', 'hope', 'scared', 'Love', 'C'),
  ('emotions', 'beginner', 'We were ___ about the trip.', 'Fear', 'excited', 'Worry', 'surprise', 'B'),
  ('emotions', 'intermediate', 'She felt ___ before the interview.', 'disappointed', 'anxious', 'frustrated', 'embarrassed', 'B'),
  ('emotions', 'intermediate', 'Delays left commuters ___.', 'content', 'frustrated', 'overwhelmed', 'nostalgic', 'B'),
  ('emotions', 'intermediate', 'He was ___ by his mistake.', 'optimistic', 'Empathy', 'Pessimistic', 'embarrassed', 'D'),
  ('emotions', 'intermediate', 'Fans were ___ by the score.', 'Resentment', 'Compassion', 'disappointed', 'sympathy', 'C'),
  ('emotions', 'intermediate', 'Too many tasks left her ___.', 'regret', 'overwhelmed', 'motivation', 'enthusiasm', 'B'),
  ('emotions', 'advanced', 'Writing offered a sense of ___.', 'despair', 'catharsis', 'ambivalence', 'euphoria', 'B'),
  ('emotions', 'advanced', 'She felt ___ about moving abroad.', 'Cognitive dissonance', 'ambivalence', 'existential dread', 'emotional regulation', 'B'),
  ('emotions', 'advanced', 'Victory brought a wave of ___.', 'Alexithymia', 'Affective empathy', 'Rumination', 'euphoria', 'D');