INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('nature', 'beginner', 'The old ___ shades the bench.', 'mountain', 'tree', 'flower', 'river', 'B'),
  ('nature', 'beginner', 'She picked a red ___.', 'lake', 'flower', 'forest', 'ocean', 'B'),
  ('nature', 'beginner', 'The ___ flows to the sea.', 'beach', 'cloud', 'sky', 'river', 'D'),
  ('nature', 'beginner', 'Snow covers the ___ peak.', 'wind', 'Snow', 'mountain', 'rain', 'C'),
  ('nature', 'beginner', 'We walked through a quiet ___.', 'sun', 'forest', 'star', 'moon', 'B'),
  ('nature', 'intermediate', '___ keeps nature resilient.', 'Erosion', 'Biodiversity', 'flood', 'Pollution', 'B'),
  ('nature', 'intermediate', '___ shapes regional plant life.', 'Recycle', 'greenhouse gas', 'renewable energy', 'Climate', 'D'),
  ('nature', 'intermediate', '___ dried the riverbed.', 'Habitat loss', 'Conservation', 'Drought', 'carbon footprint', 'C'),
  ('nature', 'intermediate', 'Heavy rain caused a ___.', 'wildfire', 'flood', 'tide', 'Monsoon', 'B'),
  ('nature', 'intermediate', '___ washed soil down the slope.', 'coral reef', 'Erosion', 'glacier', 'wetland', 'B'),
  ('nature', 'advanced', 'Scientists debate the start of the ___.', 'keystone species', 'Anthropocene', 'biogeochemical cycle', 'Ecological succession', 'B'),
  ('nature', 'advanced', 'The carbon cycle is a ___.', 'albedo effect', 'biogeochemical cycle', 'trophic cascade', 'Ocean acidification', 'B'),
  ('nature', 'advanced', '___ rebuilds burned forests.', 'desertification', 'mitigation', 'carbon sequestration', 'Ecological succession', 'D'),
  ('nature', 'advanced', 'Beavers act as a ___.', 'Invasive species', 'biodiversity hotspot', 'keystone species', 'adaptation strategy', 'C'),
  ('nature', 'advanced', 'Wolf reintroduction caused a ___.', 'Phenology', 'trophic cascade', 'Watershed management', 'symbiotic relationship', 'B'),
  ('hardware', 'beginner', 'My phone ___ is low.', 'battery', 'button', 'cable', 'charger', 'A'),
  ('hardware', 'beginner', 'This ___ feels comfortable to type on.', 'mouse', 'keyboard', 'speaker', 'screen', 'B'),
  ('hardware', 'beginner', 'I forgot my ___ at home.', 'router', 'printer', 'charger', 'monitor', 'C'),
  ('hardware', 'beginner', 'The ___ is cracked and needs repair.', 'battery', 'cable', 'screen', 'button', 'C'),
  ('hardware', 'intermediate', 'A faster ___ speeds up everyday work on your PC.', 'processor', 'driver', 'BIOS', 'touchpad', 'A'),
  ('hardware', 'intermediate', 'Games need a strong ___ for smooth graphics.', 'graphics card', 'power supply', 'SATA cable', 'optical drive', 'A'),
  ('hardware', 'intermediate', '4K ___ shows sharper images on a large monitor.', 'refresh rate', 'resolution', 'form factor', 'pixel density', 'B'),
  ('hardware', 'intermediate', 'Add more ___ to run heavy applications smoothly.', 'RAM', 'NVMe', 'BIOS', 'HDMI port', 'A'),
  ('hardware', 'advanced', 'Low ___ matters in competitive online games.', 'throughput', 'latency', 'jitter', 'bandwidth', 'B'),
  ('hardware', 'advanced', 'Update the router ___ regularly for security patches.', 'chipset', 'firmware', 'capacitor', 'hypervisor', 'B'),
  ('hardware', 'advanced', 'Streaming video uses a lot of ___.', 'bandwidth', 'TDP', 'VRM', 'PCIe lane', 'A'),
  ('hardware', 'advanced', 'An old CPU can create a ___ for the GPU and limit frame rates.', 'chipset', 'bottleneck', 'hypervisor', 'failover', 'B'),
  ('emotions', 'beginner', 'She felt ___ after the good news.', 'scared', 'happy', 'sad', 'angry', 'B'),
  ('emotions', 'beginner', 'He looked ___ at the farewell.', 'tired', 'sad', 'excited', 'nervous', 'B'),
  ('emotions', 'beginner', 'Do not speak when you are ___.', 'calm', 'lonely', 'proud', 'angry', 'D'),
  ('emotions', 'beginner', 'The child was ___ of the dark.', 'joy', 'hope', 'scared', 'Love', 'C'),
  ('emotions', 'beginner', 'We were ___ about the trip.', 'Fear', 'excited', 'Worry', 'surprise', 'B'),
  ('emotions', 'intermediate', 'She felt ___ before the interview.', 'disappointed', 'anxious', 'frustrated', 'embarrassed', 'B'),
  ('emotions', 'intermediate', 'Delays left commuters ___.', 'content', 'frustrated', 'overwhelmed', 'nostalgic', 'B'),
  ('emotions', 'intermediate', 'He was ___ by his mistake.', 'optimistic', 'Empathy', 'Pessimistic', 'embarrassed', 'D'),
  ('emotions', 'intermediate', 'Fans were ___ by the score.', 'Resentment', 'Compassion', 'disappointed', 'sympathy', 'C'),
  ('emotions', 'intermediate', 'Too many tasks left her ___.', 'regret', 'overwhelmed', 'motivation', 'enthusiasm', 'B'),
  ('emotions', 'advanced', 'Writing offered a sense of ___.', 'despair', 'catharsis', 'ambivalence', 'euphoria', 'B'),
  ('emotions', 'advanced', 'She felt ___ about moving abroad.', 'Cognitive dissonance', 'ambivalence', 'existential dread', 'emotional regulation', 'B'),
  ('emotions', 'advanced', 'Victory brought a wave of ___.', 'Alexithymia', 'Affective empathy', 'Rumination', 'euphoria', 'D');
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('emotions', 'advanced', 'Support pulled him out of ___.', 'Gaslighting', 'emotional labor', 'despair', 'Cognitive empathy', 'C'),
  ('emotions', 'advanced', 'Late nights sometimes trigger ___.', 'trauma response', 'existential dread', 'emotional numbness', 'Hypervigilance', 'B'),
  ('education', 'beginner', '___ starts at eight o''clock.', 'class', 'School', 'teacher', 'student', 'B'),
  ('education', 'beginner', 'Our ___ explains lessons clearly.', 'pen', 'teacher', 'book', 'pencil', 'B'),
  ('education', 'beginner', 'Every ___ needs a notebook.', 'homework', 'grade', 'exam', 'student', 'D'),
  ('education', 'beginner', 'The ___ meets in room twelve.', 'board', 'desk', 'class', 'lesson', 'C'),
  ('education', 'beginner', 'Read the ___ before the test.', 'library', 'book', 'question', 'subject', 'B'),
  ('education', 'intermediate', 'The ___ includes coding basics.', 'seminar', 'curriculum', 'syllabus', 'lecture', 'B'),
  ('education', 'intermediate', 'The ___ lists all assignments.', 'Research', 'syllabus', 'thesis', 'citation', 'B'),
  ('education', 'intermediate', 'The ___ lasted ninety minutes.', 'Plagiarism', 'Tuition', 'scholarship', 'lecture', 'D'),
  ('education', 'intermediate', 'Students discuss texts in the ___.', 'deadline', 'Attendance', 'seminar', 'Enrollment', 'C'),
  ('education', 'intermediate', 'She is writing her master''s ___.', 'Peer review', 'thesis', 'Extracurricular', 'rubric', 'B'),
  ('education', 'advanced', 'Modern ___ favors active learning.', 'Metacognition', 'pedagogy', 'Andragogy', 'Constructivism', 'B'),
  ('education', 'advanced', '___ focuses on adult learners.', 'Differentiated instruction', 'Andragogy', 'scaffolding', 'Inclusive education', 'B'),
  ('education', 'advanced', '___ builds knowledge through experience.', 'Learning analytics', 'Epistemology', 'Competency-based education', 'Constructivism', 'D'),
  ('education', 'advanced', '___ improves study strategies.', 'Spaced repetition', 'Cognitive load theory', 'Metacognition', 'heuristic', 'C'),
  ('education', 'advanced', 'Teachers use ___ for complex tasks.', 'Interdisciplinary', 'scaffolding', 'dissertation defense', 'Doctoral candidacy', 'B'),
  ('clothes', 'beginner', 'He wore a clean white ___.', 'skirt', 'shirt', 'pants', 'dress', 'B'),
  ('clothes', 'beginner', 'These ___ are too long.', 'coat', 'pants', 'jacket', 'shoes', 'B'),
  ('clothes', 'beginner', 'She bought a blue ___.', 'socks', 'scarf', 'hat', 'dress', 'D'),
  ('clothes', 'beginner', 'The ___ has floral patterns.', 'Jeans', 'belt', 'skirt', 'gloves', 'C'),
  ('clothes', 'beginner', 'Take a ___, it is windy.', 'T-shirt', 'jacket', 'Shorts', 'sweater', 'B'),
  ('clothes', 'intermediate', 'Organize your ___ by season.', 'tailor', 'wardrobe', 'outfit', 'accessory', 'B'),
  ('clothes', 'intermediate', 'She planned her ___ for the event.', 'hem', 'outfit', 'alteration', 'seam', 'B'),
  ('clothes', 'intermediate', 'A simple ___ completes the look.', 'Linen', 'Silk', 'Wool', 'accessory', 'D'),
  ('clothes', 'intermediate', 'The ___ shortened the sleeves.', 'waterproof', 'Leather', 'tailor', 'Denim', 'C'),
  ('clothes', 'intermediate', 'The ___ of the skirt was uneven.', 'Sportswear', 'hem', 'Formal wear', 'Fast fashion', 'B'),
  ('clothes', 'advanced', '___ pieces are made to order.', 'Textile engineering', 'Haute couture', 'Prêt-à-porter', 'capsule wardrobe', 'B'),
  ('clothes', 'advanced', '___ lines reach wider markets.', 'draping', 'Prêt-à-porter', 'Garment construction', 'Pattern grading', 'B'),
  ('clothes', 'advanced', 'A ___ reduces daily choices.', 'Bias cut', 'colorfastness', 'Millinery', 'capsule wardrobe', 'D'),
  ('clothes', 'advanced', '___ improves fabric durability.', 'Gore-Tex', 'Moisture-wicking', 'Textile engineering', 'pilling', 'C'),
  ('clothes', 'advanced', '___ affects longevity.', 'Ethical sourcing', 'Garment construction', 'greenwashing', 'Circular fashion', 'B'),
  ('daily life', 'beginner', 'My ___ rings at six every morning.', 'grocery', 'alarm', 'breakfast', 'errand', 'B'),
  ('daily life', 'beginner', 'I always eat ___ before work.', 'neighbor', 'breakfast', 'laundry', 'schedule', 'B'),
  ('daily life', 'beginner', 'We buy ___ items every Friday.', 'mailbox', 'wallet', 'grocery', 'keys', 'C'),
  ('daily life', 'beginner', 'I do ___ on Sundays.', 'doorbell', 'laundry', 'pillow', 'curtain', 'B'),
  ('daily life', 'beginner', 'Our ___ brought us soup.', 'toothbrush', 'neighbor', 'blanket', 'soap', 'B'),
  ('daily life', 'intermediate', 'The kitchen ___ broke yesterday.', 'commute', 'appliance', 'appointment', 'budget', 'B'),
  ('daily life', 'intermediate', 'She rescheduled her doctor ___.', 'routine', 'appointment', 'deadline', 'subscription', 'B'),
  ('daily life', 'intermediate', 'We stick to a monthly ___.', 'utility bill', 'landlord', 'maintenance', 'budget', 'D');
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('daily life', 'intermediate', 'My ___ takes forty minutes.', 'mortgage', 'insurance', 'commute', 'tenant', 'C'),
  ('daily life', 'intermediate', 'The project ___ is Friday.', 'renovation', 'deadline', 'chore chart', 'housewarming', 'B'),
  ('daily life', 'advanced', '___ makes small rooms feel cramped.', 'overwhelmed', 'Clutter', 'frugal', 'mindful', 'B'),
  ('daily life', 'advanced', 'A ___ lifestyle avoids waste.', 'Resilience', 'frugal', 'procrastinate', 'spontaneous', 'B'),
  ('daily life', 'advanced', 'Be ___ of how you spend time.', 'Sustainable', 'Intentional living', 'Minimalism', 'mindful', 'D'),
  ('daily life', 'advanced', 'She felt ___ by daily tasks.', 'Delegation', 'Prioritization', 'overwhelmed', 'burnout', 'C'),
  ('daily life', 'advanced', 'Do not ___ on important chores.', 'Habit stacking', 'procrastinate', 'Financial literacy', 'Decision fatigue', 'B'),
  ('animals', 'beginner', 'A ___ is singing outside.', 'dog', 'bird', 'cat', 'cow', 'B'),
  ('animals', 'beginner', 'The ___ sleeps on the sofa.', 'fish', 'cat', 'duck', 'horse', 'B'),
  ('animals', 'beginner', 'The ___ eats grass in the field.', 'rabbit', 'chicken', 'Sheep', 'cow', 'D'),
  ('animals', 'beginner', 'My ___ loves to play fetch.', 'mouse', 'goat', 'dog', 'pig', 'C'),
  ('animals', 'beginner', 'We saw colorful ___ at the aquarium.', 'wolf', 'fish', 'bear', 'fox', 'B'),
  ('animals', 'intermediate', '___ helps prey hide from predators.', 'mammal', 'Camouflage', 'endangered', 'habitat', 'B'),
  ('animals', 'intermediate', 'Tigers are an ___ species.', 'nocturnal', 'endangered', 'migration', 'predator', 'B'),
  ('animals', 'intermediate', 'Bird ___ follows seasonal routes.', 'den', 'migration', 'antlers', 'nest', 'B'),
  ('animals', 'intermediate', 'Owls are ___ hunters.', 'beak', 'nocturnal', 'paw', 'gills', 'B'),
  ('animals', 'intermediate', 'The ___ stalked its prey silently.', 'scales', 'feathers', 'wildlife', 'predator', 'D'),
  ('animals', 'advanced', 'Dog ___ began thousands of years ago.', 'symbiosis', 'domestication', 'instinct', 'territorial', 'B'),
  ('animals', 'advanced', 'The island has unique ___.', 'venomous', 'mutualism', 'biodiversity', 'fauna', 'D'),
  ('animals', 'advanced', 'Bears enter ___ in late autumn.', 'echolocation', 'metamorphosis', 'hibernation', 'parasitism', 'C'),
  ('animals', 'advanced', 'Migration is driven by ___.', 'bioluminescence', 'instinct', 'Invasive species', 'keystone species', 'B'),
  ('animals', 'advanced', 'Clownfish and anemones show ___.', 'Anthropogenic', 'symbiosis', 'genetic diversity', 'poaching', 'B'),
  ('drinks', 'beginner', 'Drink ___ throughout the day.', 'milk', 'water', 'tea', 'coffee', 'B'),
  ('drinks', 'beginner', 'Turkish ___ is served in small glasses.', 'Soda', 'tea', 'juice', 'lemonade', 'B'),
  ('drinks', 'beginner', 'I need ___ to wake up.', 'Hot chocolate', 'beer', 'smoothie', 'coffee', 'D'),
  ('drinks', 'beginner', 'Children drink ___ for calcium.', 'Mineral water', 'cocktail', 'milk', 'wine', 'C'),
  ('drinks', 'beginner', 'Orange ___ is popular at breakfast.', 'Sparkling water', 'juice', 'Espresso', 'Herbal tea', 'B'),
  ('drinks', 'intermediate', '___ the tea for five minutes.', 'Distill', 'Brew', 'steep', 'ferment', 'B'),
  ('drinks', 'intermediate', 'Let the leaves ___ in hot water.', 'decaf', 'steep', 'Carbonated', 'bitters', 'B'),
  ('drinks', 'intermediate', 'They ___ grapes to make wine.', 'garnish', 'mocktail', 'infusion', 'ferment', 'D'),
  ('drinks', 'intermediate', '___ spirits in copper stills.', 'Tonic water', 'Cold brew', 'Distill', 'Single origin', 'C'),
  ('drinks', 'intermediate', '___ drinks feel fizzy.', 'Sake', 'Carbonated', 'Rooibos', 'Matcha', 'B'),
  ('drinks', 'advanced', '___ describes texture in wine.', 'Oxidation', 'Mouthfeel', 'tannins', 'Terroir', 'B'),
  ('drinks', 'advanced', 'High ___ make wine taste dry.', 'Mixology', 'tannins', 'Fortified wine', 'palate cleanser', 'B'),
  ('drinks', 'advanced', '___ shapes grape character.', 'astringency', 'extraction yield', 'Microfoam', 'Terroir', 'D'),
  ('drinks', 'advanced', '___ can spoil opened wine.', 'proof', 'Barrel aging', 'Oxidation', 'Dry hopping', 'C'),
  ('drinks', 'advanced', '___ contains added spirits.', 'hangover', 'Fortified wine', 'Blood alcohol level', 'Responsible drinking', 'B'),
  ('relationships', 'beginner', 'She is my closest ___.', 'father', 'friend', 'Family', 'mother', 'B'),
  ('relationships', 'beginner', '___ dinners happen every Sunday.', 'brother', 'Family', 'sister', 'son', 'B'),
  ('relationships', 'beginner', 'My ___ calls me every week.', 'daughter', 'wife', 'husband', 'mother', 'D');
INSERT INTO custom_quizzes (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option)
VALUES
  ('relationships', 'beginner', 'His ___ taught him to ride a bike.', 'Grandfather', 'Grandmother', 'father', 'baby', 'C'),
  ('relationships', 'beginner', 'My ___ lives in another city.', 'uncle', 'sister', 'cousin', 'Aunt', 'B'),
  ('relationships', 'intermediate', '___ grows over shared experiences.', 'boundaries', 'Commitment', 'Long-distance', 'compromise', 'B'),
  ('relationships', 'intermediate', 'The ___ was painful but necessary.', 'intimacy', 'Forgiveness', 'Jealousy', 'breakup', 'D'),
  ('relationships', 'intermediate', '___ took honest conversations.', 'family gathering', 'misunderstanding', 'Reconciliation', 'Loyalty', 'C'),
  ('relationships', 'intermediate', '___ couples schedule video calls.', 'in-laws', 'Long-distance', 'blended family', 'stepparent', 'B'),
  ('relationships', 'intermediate', 'Clear ___ protect mental health.', 'Co-parenting', 'boundaries', 'single parent', 'engagement', 'B'),
  ('relationships', 'advanced', '___ shapes adult relationships.', 'Avoidant attachment', 'Attachment style', 'Secure attachment', 'Anxious attachment', 'B'),
  ('relationships', 'advanced', '___ fosters stable bonds.', 'Emotional availability', 'Secure attachment', 'Codependency', 'love language', 'B'),
  ('relationships', 'advanced', '___ fears abandonment.', 'Narcissistic behavior', 'Emotional abuse', 'toxic relationship', 'Anxious attachment', 'D'),
  ('relationships', 'advanced', '___ keeps emotional distance.', 'Stonewalling', 'Triangulation', 'Avoidant attachment', 'Manipulation', 'C'),
  ('relationships', 'advanced', '___ blurs personal boundaries.', 'Contempt', 'Codependency', 'Interpersonal dynamics', 'repair attempt', 'B'),
  ('jobs', 'beginner', 'The ___ filed our taxes.', 'driver', 'accountant', 'chef', 'doctor', 'B'),
  ('jobs', 'beginner', 'The ___ prepared a special menu.', 'lawyer', 'chef', 'engineer', 'nurse', 'B'),
  ('jobs', 'beginner', 'The ___ checked my blood pressure.', 'pilot', 'cashier', 'teacher', 'doctor', 'D'),
  ('jobs', 'beginner', 'The bus ___ was very friendly.', 'farmer', 'mechanic', 'driver', 'waiter', 'C'),
  ('jobs', 'beginner', 'She works as a software ___.', 'builder', 'engineer', 'writer', 'artist', 'B'),
  ('jobs', 'intermediate', 'My ___ covered my shift.', 'internship', 'colleague', 'deadline', 'freelancer', 'B'),
  ('jobs', 'intermediate', 'We met the client ___ early.', 'Remote work', 'deadline', 'promotion', 'resignation', 'B'),
  ('jobs', 'intermediate', 'He completed a summer ___.', 'probation', 'Onboarding', 'internship', 'Payroll', 'C'),
  ('jobs', 'intermediate', 'She got a ___ last month.', 'performance review', 'promotion', 'job description', 'team lead', 'B'),
  ('jobs', 'intermediate', '___ saves commuting time.', 'Networking', 'Remote work', 'reference letter', 'cover letter', 'B'),
  ('jobs', 'advanced', 'Annual ___ affects bonus pay.', 'mediator', 'appraisal', 'entrepreneur', 'liability', 'B'),
  ('jobs', 'advanced', 'The ___ launched a startup.', 'Redundancy', 'entrepreneur', 'Outsourcing', 'Severance pay', 'B'),
  ('jobs', 'advanced', 'Employers limit ___ with clear policies.', 'whistleblower', 'gig economy', 'non-compete clause', 'liability', 'D'),
  ('jobs', 'advanced', 'A ___ resolved the workplace dispute.', 'corporate governance', 'due diligence', 'mediator', 'intellectual property', 'C'),
  ('jobs', 'advanced', '___ reduced internal costs.', 'Succession planning', 'Outsourcing', 'KPI', 'Organizational culture', 'B'),
  ('health', 'beginner', 'See a ___ if fever lasts.', 'pain', 'doctor', 'hospital', 'medicine', 'B'),
  ('health', 'beginner', 'The ___ is near the park.', 'headache', 'hospital', 'fever', 'cough', 'B'),
  ('health', 'beginner', 'Take your ___ after meals.', 'cold', 'injury', 'Flu', 'medicine', 'D'),
  ('health', 'beginner', 'She felt ___ in her knee.', 'heart', 'blood', 'pain', 'bandage', 'C'),
  ('health', 'beginner', 'A high ___ needs rest.', 'lung', 'fever', 'muscle', 'bone', 'B'),
  ('health', 'intermediate', 'High ___ needs monitoring.', 'Insulin', 'blood pressure', 'cholesterol', 'Diabetes', 'B'),
  ('health', 'intermediate', 'Diet affects ___ levels.', 'antibiotic', 'cholesterol', 'prescription', 'side effect', 'B'),
  ('health', 'intermediate', '___ requires regular checkups.', 'Physical therapy', 'MRI scan', 'X-ray', 'Diabetes', 'D'),
  ('health', 'intermediate', '___ helps control blood sugar.', 'Chronic pain', 'inflammation', 'Insulin', 'immune system', 'C'),
  ('health', 'intermediate', 'The doctor wrote a ___.', 'Mental health', 'prescription', 'Depression', 'anxiety', 'B'),
  ('health', 'advanced', '___ complicates treatment plans.', 'biomarker', 'Comorbidity', 'prognosis', 'Pathology', 'B'),
  ('health', 'advanced', 'The ___ improved after therapy.', 'antibody', 'prognosis', 'placebo effect', 'Autoimmune', 'B'),
  ('health', 'advanced', '___ confirmed the diagnosis.', 'Metabolism', 'Epidemiology', 'homeostasis', 'Pathology', 'D');